dist: trusty
sudo: false
language: cpp
addons:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - gcc-7
    - g++-7
    - libboost-all-dev
    - libsuitesparse-dev
matrix:
  include:
    - os: linux
      compiler: gcc-7
      script:
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j2
      env:
        - MATRIX_EVAL="export CC=gcc-7 && CXX=g++-7"

    # - os: osx
    #   compiler: clang
    #   script: cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install suite-sparse; fi
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
