######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 29 20:45:52 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /opt/local/include/eigen3

QT += opengl
CONFIG += release
# CONFIG += debug

# QMAKE_CXXFLAGS += -D_D_GLIBCXX_DEBUG

# Input
HEADERS += CSGTree.hh CSGTree.inl CSGTreeModel.hh \
           FEMView.hh CSGWindow.hh \
           GlobalTypes.hh \
           CSGWindowController.hh \
           Geometry.hh \
           AnalysisSettings.hh \
           AnalysisForm.hh QuadraturePointsSpinBox.hh \
           Quadrature.hh MeshlessFEM.hh ElementGrid.hh

SOURCES += CSGFEM.cc CSGTreeModel.cc FEMView.cc CSGWindow.cc \
           CSGWindowController.cc AnalysisForm.cc Quadrature.cc
