######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 29 20:45:52 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /opt/local/include/eigen3 /opt/local/include/qjson
INCLUDEPATH += . /opt/local/include /opt/local/include/freetype2
INCLUDEPATH += /Applications/MATLAB_R2010b.app/extern/include/
LIBS += -L/Applications/MATLAB_R2010b.app/bin/maci64/ -leng -lmx -lmat
LIBS += -L/opt/local/lib -lqjson -lftgl
LIBS += -framework OpenCL

QT += opengl
CONFIG += release
# CONFIG += debug

QMAKE_CXXFLAGS += -DOS_OBJECT_USE_OBJC=0
QMAKE_CFLAGS +=   -DOS_OBJECT_USE_OBJC=0 -std=c99

# QMAKE_CXXFLAGS += -D_D_GLIBCXX_DEBUG

# Input
HEADERS += CSGTree.hh CSGTree.inl CSGTreeModel.hh \
           FEMView.hh CSGWindow.hh \
           GlobalTypes.hh \
           CSGWindowController.hh \
           Geometry.hh \
           AnalysisSettings.hh \
           AnalysisForm.hh QuadraturePointsSpinBox.hh \
           Quadrature.hh MeshlessFEM.hh Grid.hh ElementGrid.hh \
           MatlabInterface/MatlabInterface.h QMatlabInterface.hh \
           QCommandLine.hh Solver.hh Fields.hh ModelForm.hh \
           MarchingSquaresGrid.hh ShaderCompiler.hh \
           MSHWriter.hh colors.hh ViewSettingsWidget.hh ViewSettings.hh \
           CSGFile.hh SPHKernels.hh \
           cl-helper.h


SOURCES += CSGFEM.cc CSGTreeModel.cc FEMView.cc CSGWindow.cc \
           CSGWindowController.cc AnalysisForm.cc Quadrature.cc \
           MatlabInterface/MatlabInterface.cpp QMatlabInterface.cc \
           ModelForm.cc MarchingSquaresGrid.cc ShaderCompiler.cc \
           ViewSettingsWidget.cc Geometry.cc \
           cl-helper.c
