######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 29 20:45:52 2013
######################################################################

TEMPLATE = app
LANGUAGE = C++
# TARGET = 
DEPENDPATH += .
INCLUDEPATH += /Library/gurobi550/mac64/include/
INCLUDEPATH += . /opt/local/include/eigen3
INCLUDEPATH += . /opt/local/include /opt/local/include/freetype2
INCLUDEPATH += /Applications/MATLAB_R2013a.app/extern/include/
LIBS += -L/Applications/MATLAB_R2013a.app/bin/maci64/ -leng -lmx -lmat
LIBS += -L/opt/local/lib -lftgl
# Bring in umfpack and dependencies (BLAS)
LIBS += -lumfpack -lSuiteSparse -framework Accelerate
LIBS += -L/Library/gurobi550/mac64/lib/ -lgurobi55
LIBS += -framework OpenCL
# Hack to circumvent bug when MOC tries to parse certain boost macros
QMAKE_MOC = $$QMAKE_MOC -DBOOST_NO_TEMPLATE_PARTIAL_SPECIALIZATION

QT += opengl
CONFIG += release precompile_header
PRECOMPILED_HEADER = precompile.hh
# CONFIG += debug

QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.7

# clang++ version
QMAKE_CXXFLAGS += -DOS_OBJECT_USE_OBJC=0 -std=c++11 -stdlib=libc++ -Winvalid-pch
QMAKE_CXXFLAGS += -isystem /opt/local/include/QtGui/ -isystem /opt/local/include/eigen3/
# QMAKE_CFLAGS +=   -DOS_OBJECT_USE_OBJC=0 -std=c99
LIBS += -stdlib=libc++

# # g++ version:
# QMAKE_CXXFLAGS += -DOS_OBJECT_USE_OBJC=0 -std=gnu++11
# QMAKE_CFLAGS +=   -DOS_OBJECT_USE_OBJC=0 -std=c99

# QMAKE_CXXFLAGS += -D_D_GLIBCXX_DEBUG

# Input
HEADERS += precompile.hh CSGTree.hh CSGTree.inl CSGTreeModel.hh \
           FEMView.hh Flipbook.hh CSGWindow.hh \
           GlobalTypes.hh \
           CSGWindowController.hh \
           Geometry.hh \
           AnalysisSettings.hh \
           AnalysisForm.hh QuadraturePointsSpinBox.hh \
           Quadrature.hh MeshlessFEM.hh Grid.hh ElementGrid.hh \
           MatlabInterface/MatlabInterface.h QMatlabInterface.hh \
           QCommandLine.hh Solver.hh Fields.hh ModelForm.hh \
           MarchingSquaresGrid.hh ShaderCompiler.hh \
           MSHWriter.hh colors.hh ViewSettingsWidget.hh ViewSettings.hh \
           CSGFile.hh SPHKernels.hh \
           ResultsCollector.hh ResultsWindow/ResultsWindow.hh \
           ResultsWindow/ResultsWindowController.hh \
           ResultsWindow/ResultTreeView.hh ResultsWindow/FlipbookDialog.hh \
           cl-helper.h


SOURCES += CSGFEM.cc CSGTreeModel.cc FEMView.cc CSGWindow.cc \
           CSGWindowController.cc AnalysisForm.cc Quadrature.cc \
           MeshlessFEM.cc \
           MatlabInterface/MatlabInterface.cpp QMatlabInterface.cc \
           ModelForm.cc MarchingSquaresGrid.cc ShaderCompiler.cc \
           ViewSettingsWidget.cc Geometry.cc \
           ResultsWindow/ResultsWindow.cc ResultsWindow/ResultsWindowController.cc \
           ResultsWindow/FlipbookDialog.cc \
           cl-helper.c

# Install the resources. The executable expects to find them in
# "$(executable_dir)/../Resources" since this is compatible with the way a Mac
# OS X bundle is organized.
# The rules below install the resources when "Make install" is run.
macx {
    # Mac-OSX Specific bundle creation. 

    # Unfortunately, qmake appears to be broken... the below commands create
    # targets in the makefile that copy the files, but the targets never get
    # called...
    # KERNEL_FILES.files = Kernels
    # KERNEL_FILES.path = Contents/Resources
    # SHADER_FILES.files = Shaders
    # SHADER_FILES.path = Contents/Resources
    # FONT_FILES.files = fonts
    # FONT_FILES.path = Contents/Resources
    # QMAKE_BUNDLE_DATA += KERNEL_FILES SHADER_FILES FONT_FILES

    KERNEL_FILES.files = Kernels
    KERNEL_FILES.path = $$OUT_PWD/CSGFEM.app/Contents/Resources
    SHADER_FILES.files = Shaders
    SHADER_FILES.path = $$OUT_PWD/CSGFEM.app/Contents/Resources
    FONT_FILES.files = fonts
    FONT_FILES.path = $$OUT_PWD/CSGFEM.app/Contents/Resources
    INSTALLS += KERNEL_FILES SHADER_FILES FONT_FILES
}
