#include <iostream>
#include <algorithm>
#include <vector>
#include <queue>
#include "MeshlessFEM.hh"
#include "ResultsCollector.hh"

using namespace std;

// Element node ordering:
// 3         2
//  +-------+
//  |       |
//  |       |
//  |       |
//  +-------+
// 0         1

template<typename Model>
class MeshlessFEM<Model>::PerElementStiffnessDensity
{
public:
    typedef Eigen::Matrix<Real, 8, 8> value_type;
    // D: (d00, d01, d10, d11, d22)
    PerElementStiffnessDensity(const DType &d, const Model &model)
        : m_model(model), m_d(d) { clear(); setDimensions(Vector::Zero()); }

    void clear() {
        result = value_type::Zero();
    }

    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
        m_fullCellIntegralCached = false;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        Real x = ref_sample[0], y = ref_sample[1];

        // The following formulas are automatically generated by
        // Derivations/2DStiffness.mpl
        // .5 scaling for d22 is to account for engineering stress * strain
        // double counting the off-diagonals.
        Real d00 = m_d[0], d01 = m_d[1], d10 = m_d[1], d11 = m_d[2], d22 = .5 * m_d[3];
        Real invW = 1.0 / m_dimensions[0];
        Real invH = 1.0 / m_dimensions[1];

        result(0, 0) += weight * (invW * invW * y * y * d00 - 2 * invW * invW * d00 * y + invW * invW * d00 + invH * invH * d22 - 2 * invH * invH * d22 * x + invH * invH * x * x * d22);
        result(0, 1) += weight * (invW * d01 * invH - invW * d01 * invH * x - invW * d01 * invH * y + invW * y * d01 * invH * x + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(0, 2) += weight * (2 * invW * invW * d00 * y - invW * invW * y * y * d00 - invW * invW * d00 - invH * invH * x * x * d22 + invH * invH * d22 * x);
        result(0, 3) += weight * (-invW * y * d01 * invH * x + invW * d01 * invH * x + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(0, 4) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(0, 5) += weight * (invW * y * d01 * invH * x - invW * d01 * invH * x + invH * x * d22 * invW * y - invW * d22 * invH * y);
        result(0, 6) += weight * (-invW * invW * y * y * d00 + invW * invW * d00 * y + 2 * invH * invH * d22 * x - invH * invH * x * x * d22 - invH * invH * d22);
        result(0, 7) += weight * (invW * d01 * invH * y - invW * d01 * invH - invW * y * d01 * invH * x + invW * d01 * invH * x - invH * x * d22 * invW * y + invW * d22 * invH * y);
        result(1, 0) += weight * (invH * d10 * invW - invH * x * d10 * invW - invH * d10 * invW * y + invH * x * d10 * invW * y + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(1, 1) += weight * (invH * invH * d11 - 2 * invH * invH * d11 * x + invH * invH * x * x * d11 + invW * invW * y * y * d22 - 2 * invW * invW * d22 * y + invW * invW * d22);
        result(1, 2) += weight * (invH * d10 * invW * y - invH * d10 * invW - invH * x * d10 * invW * y + invH * x * d10 * invW - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(1, 3) += weight * (-invH * invH * x * x * d11 + invH * invH * d11 * x + 2 * invW * invW * d22 * y - invW * invW * y * y * d22 - invW * invW * d22);
        result(1, 4) += weight * (invH * x * d10 * invW * y - invH * d10 * invW * y + invH * x * d22 * invW * y - invW * d22 * invH * x);
        result(1, 5) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(1, 6) += weight * (-invH * x * d10 * invW * y + invH * d10 * invW * y + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(1, 7) += weight * (2 * invH * invH * d11 * x - invH * invH * x * x * d11 - invH * invH * d11 - invW * invW * y * y * d22 + invW * invW * d22 * y);
        result(2, 0) += weight * (2 * invW * invW * d00 * y - invW * invW * y * y * d00 - invW * invW * d00 - invH * invH * x * x * d22 + invH * invH * d22 * x);
        result(2, 1) += weight * (invW * d01 * invH * y - invW * d01 * invH - invW * y * d01 * invH * x + invW * d01 * invH * x - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(2, 2) += weight * (invW * invW * y * y * d00 - 2 * invW * invW * d00 * y + invW * invW * d00 + invH * invH * x * x * d22);
        result(2, 3) += weight * (-invW * d01 * invH * x + invW * y * d01 * invH * x - invW * d22 * invH * x + invH * x * d22 * invW * y);
        result(2, 4) += weight * (invW * invW * d00 * y - invW * invW * y * y * d00 - invH * invH * x * x * d22);
        result(2, 5) += weight * (invW * d01 * invH * x - invW * y * d01 * invH * x - invH * x * d22 * invW * y);
        result(2, 6) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(2, 7) += weight * (invW * d01 * invH - invW * d01 * invH * x - invW * d01 * invH * y + invW * y * d01 * invH * x + invH * x * d22 * invW * y);
        result(3, 0) += weight * (-invH * x * d10 * invW * y + invH * x * d10 * invW + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(3, 1) += weight * (-invH * invH * x * x * d11 + invH * invH * d11 * x + 2 * invW * invW * d22 * y - invW * invW * y * y * d22 - invW * invW * d22);
        result(3, 2) += weight * (-invH * x * d10 * invW + invH * x * d10 * invW * y - invW * d22 * invH * x + invH * x * d22 * invW * y);
        result(3, 3) += weight * (invH * invH * x * x * d11 + invW * invW * y * y * d22 - 2 * invW * invW * d22 * y + invW * invW * d22);
        result(3, 4) += weight * (-invH * x * d10 * invW * y + invW * d22 * invH * x - invH * x * d22 * invW * y);
        result(3, 5) += weight * (-invH * invH * x * x * d11 + invW * invW * d22 * y - invW * invW * y * y * d22);
        result(3, 6) += weight * (invH * x * d10 * invW * y + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(3, 7) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(4, 0) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(4, 1) += weight * (invW * y * d01 * invH * x - invW * d01 * invH * y + invH * x * d22 * invW * y - invW * d22 * invH * x);
        result(4, 2) += weight * (invW * invW * d00 * y - invW * invW * y * y * d00 - invH * invH * x * x * d22);
        result(4, 3) += weight * (-invW * y * d01 * invH * x + invW * d22 * invH * x - invH * x * d22 * invW * y);
        result(4, 4) += weight * (invW * invW * y * y * d00 + invH * invH * x * x * d22);
        result(4, 5) += weight * (invW * y * d01 * invH * x + invH * x * d22 * invW * y);
        result(4, 6) += weight * (-invW * invW * y * y * d00 + invH * invH * d22 * x - invH * invH * x * x * d22);
        result(4, 7) += weight * (invW * d01 * invH * y - invW * y * d01 * invH * x - invH * x * d22 * invW * y);
        result(5, 0) += weight * (invH * x * d10 * invW * y - invH * x * d10 * invW + invH * x * d22 * invW * y - invW * d22 * invH * y);
        result(5, 1) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(5, 2) += weight * (invH * x * d10 * invW - invH * x * d10 * invW * y - invH * x * d22 * invW * y);
        result(5, 3) += weight * (-invH * invH * x * x * d11 + invW * invW * d22 * y - invW * invW * y * y * d22);
        result(5, 4) += weight * (invH * x * d10 * invW * y + invH * x * d22 * invW * y);
        result(5, 5) += weight * (invH * invH * x * x * d11 + invW * invW * y * y * d22);
        result(5, 6) += weight * (-invH * x * d10 * invW * y + invW * d22 * invH * y - invH * x * d22 * invW * y);
        result(5, 7) += weight * (invH * invH * d11 * x - invH * invH * x * x * d11 - invW * invW * y * y * d22);
        result(6, 0) += weight * (-invW * invW * y * y * d00 + invW * invW * d00 * y + 2 * invH * invH * d22 * x - invH * invH * x * x * d22 - invH * invH * d22);
        result(6, 1) += weight * (-invW * y * d01 * invH * x + invW * d01 * invH * y + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(6, 2) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(6, 3) += weight * (invW * y * d01 * invH * x + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(6, 4) += weight * (-invW * invW * y * y * d00 + invH * invH * d22 * x - invH * invH * x * x * d22);
        result(6, 5) += weight * (-invW * y * d01 * invH * x + invW * d22 * invH * y - invH * x * d22 * invW * y);
        result(6, 6) += weight * (invW * invW * y * y * d00 + invH * invH * d22 - 2 * invH * invH * d22 * x + invH * invH * x * x * d22);
        result(6, 7) += weight * (-invW * d01 * invH * y + invW * y * d01 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(7, 0) += weight * (invH * d10 * invW * y - invH * d10 * invW - invH * x * d10 * invW * y + invH * x * d10 * invW - invH * x * d22 * invW * y + invW * d22 * invH * y);
        result(7, 1) += weight * (2 * invH * invH * d11 * x - invH * invH * x * x * d11 - invH * invH * d11 - invW * invW * y * y * d22 + invW * invW * d22 * y);
        result(7, 2) += weight * (invH * d10 * invW - invH * x * d10 * invW - invH * d10 * invW * y + invH * x * d10 * invW * y + invH * x * d22 * invW * y);
        result(7, 3) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(7, 4) += weight * (invH * d10 * invW * y - invH * x * d10 * invW * y - invH * x * d22 * invW * y);
        result(7, 5) += weight * (invH * invH * d11 * x - invH * invH * x * x * d11 - invW * invW * y * y * d22);
        result(7, 6) += weight * (-invH * d10 * invW * y + invH * x * d10 * invW * y - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(7, 7) += weight * (invH * invH * d11 - 2 * invH * invH * d11 * x + invH * invH * x * x * d11 + invW * invW * y * y * d22);
    }

    // Analytic result for a full cell
    Real fullCellIntegral(size_t i, size_t j) {
        if (!m_fullCellIntegralCached) {
            // The following formulas are automatically generated by
            // Derivations/Integrations.mpl
            // .5 scaling for d22 is to account for engineering stress * strain
            // double counting the off-diagonals.
            Real d00 = m_d[0], d01 = m_d[1], d10 = m_d[1], d11 = m_d[2], d22 = .5 * m_d[3];

            Real w = m_dimensions[0];
            Real h = m_dimensions[1];
            Real invVol = 1.0 / (w * h);
            Real wSq = w * w;
            Real hSq = h * h;

            fullCellResult(0, 0) = invVol * (d00 * hSq + d22 * wSq) / 3.0;
            fullCellResult(0, 1) = d01 / 4.0 + d22 / 4.0;
            fullCellResult(0, 2) = -invVol * (2.0 * d00 * hSq - d22 * wSq) / 6.0;
            fullCellResult(0, 3) = d01 / 4.0 - d22 / 4.0;
            fullCellResult(0, 4) = -invVol * (d00 * hSq + d22 * wSq) / 6.0;
            fullCellResult(0, 5) = -d01 / 4.0 - d22 / 4.0;
            fullCellResult(0, 6) = invVol * (d00 * hSq - 2.0 * d22 * wSq) / 6.0;
            fullCellResult(0, 7) = -d01 / 4.0 + d22 / 4.0;
            fullCellResult(1, 0) = d10 / 4.0 + d22 / 4.0;
            fullCellResult(1, 1) = invVol * (d11 * wSq + d22 * hSq) / 3.0;
            fullCellResult(1, 2) = -d10 / 4.0 + d22 / 4.0;
            fullCellResult(1, 3) = invVol * (d11 * wSq - 2.0 * d22 * hSq) / 6.0;
            fullCellResult(1, 4) = -d10 / 4.0 - d22 / 4.0;
            fullCellResult(1, 5) = -invVol * (d11 * wSq + d22 * hSq) / 6.0;
            fullCellResult(1, 6) = d10 / 4.0 - d22 / 4.0;
            fullCellResult(1, 7) = -invVol * (2.0 * d11 * wSq - d22 * hSq) / 6.0;
            fullCellResult(2, 0) = -invVol * (2.0 * d00 * hSq - d22 * wSq) / 6.0;
            fullCellResult(2, 1) = -d01 / 4.0 + d22 / 4.0;
            fullCellResult(2, 2) = invVol * (d00 * hSq + d22 * wSq) / 3.0;
            fullCellResult(2, 3) = -d01 / 4.0 - d22 / 4.0;
            fullCellResult(2, 4) = invVol * (d00 * hSq - 2.0 * d22 * wSq) / 6.0;
            fullCellResult(2, 5) = d01 / 4.0 - d22 / 4.0;
            fullCellResult(2, 6) = -invVol * (d00 * hSq + d22 * wSq) / 6.0;
            fullCellResult(2, 7) = d01 / 4.0 + d22 / 4.0;
            fullCellResult(3, 0) = d10 / 4.0 - d22 / 4.0;
            fullCellResult(3, 1) = invVol * (d11 * wSq - 2.0 * d22 * hSq) / 6.0;
            fullCellResult(3, 2) = -d10 / 4.0 - d22 / 4.0;
            fullCellResult(3, 3) = invVol * (d11 * wSq + d22 * hSq) / 3.0;
            fullCellResult(3, 4) = -d10 / 4.0 + d22 / 4.0;
            fullCellResult(3, 5) = -invVol * (2.0 * d11 * wSq - d22 * hSq) / 6.0;
            fullCellResult(3, 6) = d10 / 4.0 + d22 / 4.0;
            fullCellResult(3, 7) = -invVol * (d11 * wSq + d22 * hSq) / 6.0;
            fullCellResult(4, 0) = -invVol * (d00 * hSq + d22 * wSq) / 6.0;
            fullCellResult(4, 1) = -d01 / 4.0 - d22 / 4.0;
            fullCellResult(4, 2) = invVol * (d00 * hSq - 2.0 * d22 * wSq) / 6.0;
            fullCellResult(4, 3) = -d01 / 4.0 + d22 / 4.0;
            fullCellResult(4, 4) = invVol * (d00 * hSq + d22 * wSq) / 3.0;
            fullCellResult(4, 5) = d01 / 4.0 + d22 / 4.0;
            fullCellResult(4, 6) = -invVol * (2.0 * d00 * hSq - d22 * wSq) / 6.0;
            fullCellResult(4, 7) = d01 / 4.0 - d22 / 4.0;
            fullCellResult(5, 0) = -d10 / 4.0 - d22 / 4.0;
            fullCellResult(5, 1) = -invVol * (d11 * wSq + d22 * hSq) / 6.0;
            fullCellResult(5, 2) = d10 / 4.0 - d22 / 4.0;
            fullCellResult(5, 3) = -invVol * (2.0 * d11 * wSq - d22 * hSq) / 6.0;
            fullCellResult(5, 4) = d10 / 4.0 + d22 / 4.0;
            fullCellResult(5, 5) = invVol * (d11 * wSq + d22 * hSq) / 3.0;
            fullCellResult(5, 6) = -d10 / 4.0 + d22 / 4.0;
            fullCellResult(5, 7) = invVol * (d11 * wSq - 2.0 * d22 * hSq) / 6.0;
            fullCellResult(6, 0) = invVol * (d00 * hSq - 2.0 * d22 * wSq) / 6.0;
            fullCellResult(6, 1) = d01 / 4.0 - d22 / 4.0;
            fullCellResult(6, 2) = -invVol * (d00 * hSq + d22 * wSq) / 6.0;
            fullCellResult(6, 3) = d01 / 4.0 + d22 / 4.0;
            fullCellResult(6, 4) = -invVol * (2.0 * d00 * hSq - d22 * wSq) / 6.0;
            fullCellResult(6, 5) = -d01 / 4.0 + d22 / 4.0;
            fullCellResult(6, 6) = invVol * (d00 * hSq + d22 * wSq) / 3.0;
            fullCellResult(6, 7) = -d01 / 4.0 - d22 / 4.0;
            fullCellResult(7, 0) = -d10 / 4.0 + d22 / 4.0;
            fullCellResult(7, 1) = -invVol * (2.0 * d11 * wSq - d22 * hSq) / 6.0;
            fullCellResult(7, 2) = d10 / 4.0 + d22 / 4.0;
            fullCellResult(7, 3) = -invVol * (d11 * wSq + d22 * hSq) / 6.0;
            fullCellResult(7, 4) = d10 / 4.0 - d22 / 4.0;
            fullCellResult(7, 5) = invVol * (d11 * wSq - 2.0 * d22 * hSq) / 6.0;
            fullCellResult(7, 6) = -d10 / 4.0 - d22 / 4.0;
            fullCellResult(7, 7) = invVol * (d11 * wSq + d22 * hSq) / 3.0;

            m_fullCellIntegralCached = true;
        }

        return fullCellResult(i, j);
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 8) && (j < 8));
        return result(i, j);
    }

private:
    const Model &m_model;
    const DType &m_d;
    Vector m_dimensions;
    bool m_fullCellIntegralCached;

    value_type result, fullCellResult;
};

template<typename Model>
class MeshlessFEM<Model>::PerElementLaplacianDensity
{
public:
    typedef Eigen::Matrix<Real, 4, 4> value_type;
    PerElementLaplacianDensity(const Model &model)
        : m_model(model) { clear(); }

    void clear() { result = value_type::Zero(); }

    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        Real x = ref_sample[0], y = ref_sample[1];

        // The following formulas are automatically generated by
        // Derivations/2DStiffness.mpl
        // .5 scaling for d22 is to account for engineering stress * strain
        // double counting the off-diagonals.
        Real invW = 1.0 / m_dimensions[0];
        Real invH = 1.0 / m_dimensions[1];

        result(0, 0) += weight * (invW * invW - 2 * invW * invW * y + invW * invW * y * y + invH * invH - 2 * invH * invH * x + invH * invH * x * x);
        result(0, 1) += weight * (2 * invW * invW * y - invW * invW * y * y - invW * invW - invH * invH * x * x + invH * invH * x);
        result(0, 2) += weight * (invW * invW * y * y - invW * invW * y + invH * invH * x * x - invH * invH * x);
        result(0, 3) += weight * (-invW * invW * y * y + invW * invW * y + 2 * invH * invH * x - invH * invH * x * x - invH * invH);
        result(1, 0) += weight * (2 * invW * invW * y - invW * invW * y * y - invW * invW - invH * invH * x * x + invH * invH * x);
        result(1, 1) += weight * (invW * invW - 2 * invW * invW * y + invW * invW * y * y + invH * invH * x * x);
        result(1, 2) += weight * (invW * invW * y - invW * invW * y * y - invH * invH * x * x);
        result(1, 3) += weight * (invW * invW * y * y - invW * invW * y + invH * invH * x * x - invH * invH * x);
        result(2, 0) += weight * (invW * invW * y * y - invW * invW * y + invH * invH * x * x - invH * invH * x);
        result(2, 1) += weight * (invW * invW * y - invW * invW * y * y - invH * invH * x * x);
        result(2, 2) += weight * (invW * invW * y * y + invH * invH * x * x);
        result(2, 3) += weight * (-invW * invW * y * y + invH * invH * x - invH * invH * x * x);
        result(3, 0) += weight * (-invW * invW * y * y + invW * invW * y + 2 * invH * invH * x - invH * invH * x * x - invH * invH);
        result(3, 1) += weight * (invW * invW * y * y - invW * invW * y + invH * invH * x * x - invH * invH * x);
        result(3, 2) += weight * (-invW * invW * y * y + invH * invH * x - invH * invH * x * x);
        result(3, 3) += weight * (invW * invW * y * y + invH * invH - 2 * invH * invH * x + invH * invH * x * x);
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 8) && (j < 8));
        return result(i, j);
    }

private:
    const Model &m_model;
    Vector m_dimensions;

    value_type result;
};

// Averaged (not integrated) grad phi over the element.
template<typename Model>
class MeshlessFEM<Model>::PerElementGradPhi
{
public:
    // D: (d00, d01, d10, d11, d22)
    PerElementGradPhi(const Model &model)
        : m_model(model) { clear(); setDimensions(Vector::Zero()); }

    void clear() {
        result = GradPhis::Zero();
    }

    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
        m_fullCellIntegralCached = false;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        // Multiply integrand by indicator function
        if (!m_model.isInside(sample))
            return;

        Real x = ref_sample[0], y = ref_sample[1];
        // phi0 = (1 - x) * (1 - y) => grad phi0 = (invW (y - 1), invH (x - 1))
        // phi1 =      x  * (1 - y) => grad phi1 = (invW (1 - y), invH (   -x))
        // phi2 =      x  *      y  => grad phi2 = (invW (    y), invH (    x))
        // phi3 = (1 - x) *      y  => grad phi3 = (invW (   -y), invH (1 - x))
        Real invW = 1.0 / m_dimensions[0];
        Real invH = 1.0 / m_dimensions[1];
        Real xWeight = weight * invW;
        Real yWeight = weight * invH;

        result(0, 0) += xWeight * (y - 1); result(0, 1) += yWeight * (x - 1);
        result(1, 0) += xWeight * (1 - y); result(1, 1) += yWeight * (   -x);
        result(2, 0) += xWeight * (    y); result(2, 1) += yWeight * (    x);
        result(3, 0) += xWeight * (   -y); result(3, 1) += yWeight * (1 - x);
    }

    // Analytic result for a full cell
    const GradPhis &fullCellIntegral() {
        if (!m_fullCellIntegralCached) {
            Real hinvW = 0.5 / m_dimensions[0];
            Real hinvH = 0.5 / m_dimensions[1];

            fullCellResult(0, 0) = -hinvW; fullCellResult(0, 1) = -hinvH;
            fullCellResult(1, 0) =  hinvW; fullCellResult(1, 1) = -hinvH;
            fullCellResult(2, 0) =  hinvW; fullCellResult(2, 1) =  hinvH;
            fullCellResult(3, 0) = -hinvW; fullCellResult(3, 1) =  hinvH;

            m_fullCellIntegralCached = true;
        }

        return fullCellResult;
    }

    void finalize(Real rho = 1.0) {
        // We accumulated the integral, not the average--divide by the
        // integration domain.
        result /= rho * m_dimensions[0] * m_dimensions[1];
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 8) && (j < 8));
        return result(i, j);
    }

    // Allow type cast to GradPhi
    operator const GradPhis &() const {
        return result;
    }

private:
    const Model &m_model;
    GradPhis result, fullCellResult;
    bool m_fullCellIntegralCached;
    Vector m_dimensions;
    Real m_volume;
};

template<typename Model>
class MeshlessFEM<Model>::PerElementMassMatrixDensity
{
public:
    typedef Eigen::Matrix<Real, 4, 4> value_type;
    PerElementMassMatrixDensity(const Model &model, Real density,
                                   MassMatrixType type = MASS_QUARTER_CELL)
        : m_model(model), m_density(density), m_type(type)
    {
        clear();
    }

    void clear() {
        result = value_type::Zero();
        m_element_mass = 0.0;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        m_element_mass += weight * m_density;

        Real x = ref_sample[0], y = ref_sample[1];
        // Node ordering: 3 2
        //                0 1
        Eigen::Matrix<Real, 4, 1> phi;
        phi[0] = (1 - x) * (1 - y);
        phi[1] =      x  * (1 - y);
        phi[2] =      x  *      y ;
        phi[3] = (1 - x) *      y ;

        for (size_t i = 0; i < 4; ++i) {
            for (size_t j = 0; j < 4; ++j) {
                result(i, j) += weight * m_density * phi[i] * phi[j];
            }
        }
    }

    Real operator()(size_t i, size_t j) const {
        Real val = 0.0;
        if (m_type == MASS_LUMPED) {
            if (i == j) {
                // Lumped mass puts sum of entire row on the diagonal
                val = result(i, 0) + result(i, 1) + result(i, 2) + result(i, 3);
            }
        }
        else if (m_type == MASS_QUARTER_CELL) {
            if (i == j) {
                val = .25 * m_element_mass;
            }
        }
        else if (m_type == MASS_FULL) {
            val = result(i, j);
        }
        else {
            assert(false);
        }
        return val;
    }

private:
    const Model &m_model;
    Real m_density;
    MassMatrixType m_type;

    value_type result;
    Real m_element_mass;
};

template<typename Model>
void MeshlessFEM<Model>::m_assembleStiffnessMatrix(TMatrix &K)
{
    // Simple (i, j v) stiffness matrix generation
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();
    K.m = K.n = 2 * elemGrid.numNodes();
    PerElementStiffnessDensity stiff(m_d, model());
    CornerVec cornerIndices;

    K.clear();
    size_t nnz = 64 * elemGrid.numElements();
    K.nz.reserve(nnz);

    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        BBox_t b = elemGrid.elementBoundingBox(e);
        elemGrid.elementCorners(e, cornerIndices);
        stiff.setDimensions(b.dimensions());
        if ((m_exactFullElements && elemGrid.elementIsFull(e))
                || m_antialiasedElements) {
            Real rho = elemGrid.elementOverlap(e);
            for (size_t i = 0; i < 4; ++i) {
                size_t vi = cornerIndices[i];
                for (size_t j = 0; j < 4; ++j) {
                    size_t vj = cornerIndices[j];
                    // xx, xy, yy, yx
                    K.addNZ(2 * vi    , 2 * vj    , rho * stiff.fullCellIntegral(2 * i    , 2 * j    ));
                    K.addNZ(2 * vi    , 2 * vj + 1, rho * stiff.fullCellIntegral(2 * i    , 2 * j + 1));
                    K.addNZ(2 * vi + 1, 2 * vj + 1, rho * stiff.fullCellIntegral(2 * i + 1, 2 * j + 1));
                    K.addNZ(2 * vi + 1, 2 * vj    , rho * stiff.fullCellIntegral(2 * i + 1, 2 * j    ));
                }
            }
        }
        else {
            stiff.clear();
            q.integrate(stiff, b);
            for (size_t i = 0; i < 4; ++i) {
                size_t vi = cornerIndices[i];
                for (size_t j = 0; j < 4; ++j) {
                    size_t vj = cornerIndices[j];
                    // xx, xy, yy, yx
                    K.addNZ(2 * vi    , 2 * vj    , stiff(2 * i    , 2 * j    ));
                    K.addNZ(2 * vi    , 2 * vj + 1, stiff(2 * i    , 2 * j + 1));
                    K.addNZ(2 * vi + 1, 2 * vj + 1, stiff(2 * i + 1, 2 * j + 1));
                    K.addNZ(2 * vi + 1, 2 * vj    , stiff(2 * i + 1, 2 * j    ));
                }
            }
        }
    }
}

template<typename Model>
void MeshlessFEM<Model>::m_assembleLaplacianMatrix(TMatrix &L)
{
    // Simple (i, j v) laplacian matrix generation
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();
    L.m = L.n = elemGrid.numNodes();
    PerElementLaplacianDensity lap(model());
    CornerVec cornerIndices;

    L.clear();
    size_t nnz = 16 * elemGrid.numElements();
    L.nz.reserve(nnz);

    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        lap.clear();
        BBox_t b = elemGrid.elementBoundingBox(e);
        lap.setDimensions(b.dimensions());
        q.integrate(lap, b);
        elemGrid.elementCorners(e, cornerIndices);
        for (size_t i = 0; i < 4; ++i) {
            size_t vi = cornerIndices[i];
            for (size_t j = 0; j < 4; ++j) {
                size_t vj = cornerIndices[j];
                L.addNZ(vi, vj, lap(i, j));
            }
        }
    }
}


// Compute the quantities needed to evaluate (average) strain/stress/energy from
// displacement.
template<typename Model>
void MeshlessFEM<Model>::m_computePerElementDisplacementStrainMap()
{
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();
    PerElementGradPhi gradPhi(model());

    size_t numElements = elemGrid.numElements();
    if (m_elementData.size() != numElements) {
        m_elementData.resize(numElements);
    }

    if (m_antialiasedElements) {
        for (size_t e = 0; e < numElements; ++e) {
            BBox_t b = elemGrid.elementBoundingBox(e);
            gradPhi.setDimensions(b.dimensions());
            Real rho = elemGrid.elementOverlap(e);
            m_elementData[e].setGradPhis(rho * gradPhi.fullCellIntegral());
            m_elementData[e].setVolume(b.volume());
        }
    }
    else {
        for (size_t e = 0; e < numElements; ++e) {
            BBox_t b = elemGrid.elementBoundingBox(e);
            gradPhi.setDimensions(b.dimensions());
            m_elementData[e].setVolume(b.volume());
            if (m_exactFullElements && (elemGrid.elementIsFull(e))) {
                m_elementData[e].setGradPhis(gradPhi.fullCellIntegral());
            }
            else {
                gradPhi.clear();
                q.integrate(gradPhi, b);
                // TODO: remove rho, or document so we know gradPhi is no
                // longer an average over the cell, but rather an average over
                // the non-void cell portion.
                Real rho = elemGrid.elementOverlap(e);
                gradPhi.finalize(rho);
                m_elementData[e].setGradPhis(gradPhi);
            }
        }
    }

    m_displacementStrainCached = true;
}

template<typename Model>
typename MeshlessFEM<Model>::SMField
MeshlessFEM<Model>::elementStressTensors(const VField &displacement)
{
    if (!m_displacementStrainCached)
        m_computePerElementDisplacementStrainMap();
    size_t numElements = elementGrid().numElements();
    assert(m_elementData.size() == numElements);

    SMField stressTensorField(numElements);

    const ElementGrid2D<Model> &elemGrid = elementGrid();
    for (size_t e = 0; e < numElements; ++e) {
        CornerVec cornerIndices;
        elemGrid.elementCorners(e, cornerIndices);
        typename SMField::SymmetricMatrix tensor = stressTensorField(e);
        m_elementData[e].displacementToStress(displacement, cornerIndices, m_d,
                                              tensor);
    }

    return stressTensorField;
}

////////////////////////////////////////////////////////////////////////////////
/*! Compute the stress tensor L2 norms (maximum eigenvalue magnitude)
//  @param[in]  signedNorm  preserve signs of eigenvalues (so element
//                          compression gives negative stress "norm").
//                          Defaults to false.
//  @return     per-element scalar field of stress tensor norms
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
typename MeshlessFEM<Model>::SField
MeshlessFEM<Model>::computeStressTensorNorms(const SMField &stressField,
                                             bool signedNorm)
{
    size_t numMats = stressField.domainSize();
    VField eigenvalues = m_solvers.solver()->symm2x2Eigenvalues(stressField);
    assert(eigenvalues.domainSize() == numMats);
    SField result(numMats);

    if (signedNorm) {
        for (size_t i = 0; i < numMats; ++i) {
            result[i] = (fabs(eigenvalues(i)[0]) > fabs(eigenvalues(i)[1])) ?
                eigenvalues(i)[0] : eigenvalues(i)[1];
        }
    }
    else {
        for (size_t i = 0; i < numMats; ++i) {
            result[i] = std::max(fabs(eigenvalues(i)[0]),
                                 fabs(eigenvalues(i)[1]));
        }
    }

    return result;
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse mass matrix matrix for modal analysis.
//  @param[out]  M           Mass matrix in triplet format.
//  @param[in]   forLaplacian   whether the mass matrix is for the laplacian
//                              modal analysis (defaults to false)
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleMassMatrix(TMatrix &M, bool forLaplacian)
{
    // Simple (i, j v) mass matrix generation
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();

    M.m = M.n = (forLaplacian ? 1 : 2) * elemGrid.numNodes();

    PerElementMassMatrixDensity lmass(model(), m_density, m_massMatrixType);
    CornerVec cornerIndices;

    M.clear();
    size_t nnz = 16 * (forLaplacian ? 1 : 2) * (elemGrid.numElements());
    M.nz.reserve(nnz);

    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        lmass.clear();
        q.integrate(lmass, elemGrid.elementBoundingBox(e));
        elemGrid.elementCorners(e, cornerIndices);
        for (size_t i = 0; i < 4; ++i) {
            size_t vi = cornerIndices[i];
            for (size_t j = 0; j < 4; ++j) {
                size_t vj = cornerIndices[j];
                Real val = lmass(i, j);
                if (val > 1e-12) {
                    if (forLaplacian) {
                        M.addNZ(vi, vj, val);
                    }
                    else {
                        M.addNZ(2 * vi    , 2 * vj    , val);
                        M.addNZ(2 * vi + 1, 2 * vj + 1, val);
                    }
                }
            }
        }
    }
}

template<typename Model>
class MeshlessFEM<Model>::BoundaryFunctionLoad
{
public:
    typedef Eigen::Matrix<Real, 4, 1> value_type;

    BoundaryFunctionLoad(const BoundaryFunction &psi, const Model &model)
        : m_psi(psi), m_model(model) {
        clear();
    }

    void clear() {
        m_load = value_type::Zero();
    }

    void accumulate(const Vector &sample,
                    const Vector &ref_sample, Real weight) {
        bool inSupport = m_psi.isInSupport(sample);
        if (inSupport && m_model.isInside(sample)) {
            Real psi = m_psi(sample);

            // Compute unscaled load (integral against each grid node function)
            Real x = ref_sample[0], y = ref_sample[1];
            value_type phi((1 - x) * (1 - y),      x  * (1 - y),
                                x  *      y , (1 - x) *      y );

            m_load += (weight * psi) * phi;
        }
    }

    Real operator()(size_t i) const {
        assert(i < 4);
        return m_load(i);
    }

private:
    value_type m_load;
    const BoundaryFunction &m_psi;
    const Model &m_model;
};

// Rebuild all boundary force blurring functions
// @param[in] r    scale factor determining blur kernel radius. The actual
//                 radius will be r * cellSize
template<typename Model>
void MeshlessFEM<Model>::buildBoundaryFunctions(Real r)
{
    m_boundaryFunctions.clear();
    m_boundaryFunctions.reserve(m_boundaryPoints.size());
    Vector cellSize = m_elementGrid->cellSize();
    Real h = std::max(cellSize[0], cellSize[1]);
    h *= r;

    for (size_t i = 0; i < m_boundaryPoints.size(); ++i) {
        m_boundaryFunctions.push_back(
                BoundaryFunction(m_boundaryPoints[i].p, h));
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Construct the surface force -> surface force load matrix.
//  This matrix maps a (B * dim) vector of flattened (x1, y1, ..) per-boundary
//  point force densities to a (N * dim) vector of flattened (x1, y1, ..)
//  per-node loads.
//  Each pressure variable p_i is blurred into a volume force by boundary
//  function psi_i. Psi_i is (effectively) normalized so that the integral of
//  the point's force over the surface is n_i * a_i * p_i (n_i normal, a_i area)
//  Note: Because of partition of unity, this condition means the matrix columns
//        should sum to 1.
//  @param[out]  F          Load matrix in triplet format.
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleLoadMatrix(TMatrix &F)
{
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    F.clear();
    F.m = elemGrid.numNodes();
    F.n = numBoundaryPoints();

    std::vector<size_t> support_elems;
    CornerVec cornerIndices;
    const Quadrature2D &q = quadrature();

    // Create (i, j, v) triplets for each function's contribution to load in a
    // single dimension.
    IndexVec i, j;
    ValueVec v;

    // Fill out one column of the matrix at a time.
    for (size_t f = 0; f < F.n; ++f) {
        const BoundaryFunction &psi = boundaryFunction(f);
        BoundaryFunctionLoad load(psi, model());

        elemGrid.elementsAroundPoint(psi.center(), psi.supportRadius(),
                                     support_elems);
        Real colSum = 0;
        // Mark the start of the values in this column so we can go back and
        // normalize them.
        size_t colValuesOffset = v.size();
        for (size_t e : support_elems) {
            load.clear();
            q.integrate(load, elemGrid.elementBoundingBox(e));
            elemGrid.elementCorners(e, cornerIndices);
            for (size_t c = 0; c < 4; ++c) {
                Real ld = load(c);
                if (std::abs(ld) > 1e-8) {
                    i.push_back(cornerIndices[c]);
                    j.push_back(f);
                    v.push_back(ld);
                    colSum += ld;
                }
            }
        }

        // Normalize so the column sums to 1
        for (size_t vo = colValuesOffset; vo < v.size(); ++vo) {
            v[vo] /= colSum;
        }
    }

    // Duplicate matrix for each dimension, inserting into F
    F.m *= 2, F.n *= 2;
    size_t singleNNZ = i.size();
    F.reserve(2 * singleNNZ);
    for (size_t k = 0; k < singleNNZ; ++k) {
        F.addNZ(2 * i[k]    , 2 * j[k]    , v[k]);
        F.addNZ(2 * i[k] + 1, 2 * j[k] + 1, v[k]);
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix whose rows span the space of rigid transformation
//  displacements. These are the translations and infinitesimal rotations.
//  In 2D, there are three.
//  The generated matrix also can compute total force and net torque of a
//  (volume) force distribution, so it is useful in formulating the pressure
//  equality constraints for structural optimization.
//  @param[out]  R      Rigid mode matrix in sparse triplet format.
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleRigidModeMatrix(TMatrix &R)
{
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    R.m = 3;
    R.n = 2 * elemGrid.numNodes();
    size_t nNodes = elemGrid.numNodes();
    
    R.clear();
    size_t predictedNNZ = 4 * nNodes;
    R.reserve(predictedNNZ);

    // Translations
    for (size_t k = 0; k < nNodes; ++k) {
        R.addNZ(0, 2 * k    , 1.0);
        R.addNZ(1, 2 * k + 1, 1.0);
    }

    // Infinitesimal rotations
    for (size_t k = 0; k < nNodes; ++k) {
        Vector p = elemGrid.nodePosition(k);
        // offset: [-y, x]
        R.addNZ(2, 2 * k, -p[1]);
        R.addNZ(2, 2 * k + 1, p[0]);
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix mapping boundary pressures to boundary force
//  magnitudes (i.e. weighting the pressures by the area over which they act).
//  @param[out]  A      boundary pressure->force matrix in sparse triplet format
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleAMatrix(TMatrix &A)
{
    A.m = m_boundaryPoints.size();
    A.n = m_boundaryPoints.size();

    A.clear();
    size_t nnz = m_boundaryPoints.size();
    A.reserve(nnz);

    for (size_t k = 0; k < m_boundaryPoints.size(); ++k) {
        A.addNZ(k, k, m_boundaryPoints[k].a);
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix mapping boundary force magnitudes to a flattened
//  vector of forces at those boundary points.
//  @param[out]  N      boundary force magnitude->force matrix in sparse
//                      triplet format.
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleNMatrix(TMatrix &N)
{
    N.m = 2 * m_boundaryPoints.size();
    N.n = m_boundaryPoints.size();

    N.clear();
    size_t nnz = 2 * m_boundaryPoints.size();
    N.reserve(nnz);

    for (size_t k = 0; k < m_boundaryPoints.size(); ++k) {
        // Forces are applied in the negative normal direction
        Vector f = -m_boundaryPoints[k].n;

        // x, y component
        N.addNZ(2 * k, k, f[0]);
        N.addNZ(2 * k + 1, k, f[1]);
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix mapping a flattened per-node displacement vector to a 
//  flattened per-element strain tensor.
//  @param[out]  B      displacement->strain matrix in sparse triplet format
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleBMatrix(TMatrix &B)
{
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    B.m = 3 * elemGrid.numElements();
    B.n = 2 * elemGrid.numNodes();

    if (!m_displacementStrainCached)
        m_computePerElementDisplacementStrainMap();

    size_t nnz = 16 * elemGrid.numElements();
    B.clear();
    B.reserve(nnz);

    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        CornerVec cornerIndices;
        elemGrid.elementCorners(e, cornerIndices);
        for (size_t c = 0; c < 4; ++c) {
            size_t vtx = cornerIndices[c];
            // e_xx, e_yy, e_xy (1), e_xy (2)
            B.addNZ(3 * e + 0, 2 * vtx + 0, m_elementData[e].gradPhi(c, 0));
            B.addNZ(3 * e + 1, 2 * vtx + 1, m_elementData[e].gradPhi(c, 1));
            B.addNZ(3 * e + 2, 2 * vtx + 0, .5 * m_elementData[e].gradPhi(c, 1));
            B.addNZ(3 * e + 2, 2 * vtx + 1, .5 * m_elementData[e].gradPhi(c, 0));
        }
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix mapping a flattened per-element strain tensor to
//  a flattened per-element stress tensor
//  @param[out]  VD     strain->stress sparse matrix in triplet format
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleVDMatrix(TMatrix &VD)
{
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    VD.m = 3 * elemGrid.numElements();
    VD.n = 3 * elemGrid.numElements();

    size_t nnz = 5 * elemGrid.numElements();
    VD.clear();
    VD.reserve(nnz);

    // The per-element matrix is given by:
    // D = d00 d01   0 =  d0 d1   0 
    //     d10 d11   0    d1 d2   0
    //     0   0   d22    0   0   d3
    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        Real vol = m_elementData[e].volume();
        VD.addNZ(3 * e + 0, 3 * e + 0, vol * m_d[0]);
        VD.addNZ(3 * e + 0, 3 * e + 1, vol * m_d[1]);
        VD.addNZ(3 * e + 1, 3 * e + 0, vol * m_d[1]);
        VD.addNZ(3 * e + 1, 3 * e + 1, vol * m_d[2]);
        VD.addNZ(3 * e + 2, 3 * e + 2, vol * m_d[3]);
    }
}

template<typename Model>
bool MeshlessFEM<Model>::modalAnalysis(RC *rc)
{
    bool success;
    Solver<Real> *solver = m_solvers.solver();

    if (m_laplacianModes) {
        // Use laplacian modes
        TMatrix L, M;
        m_assembleLaplacianMatrix(L);
        m_assembleMassMatrix(M, true);

        size_t numModes = std::min((size_t) m_numRequestedModes, L.n);

        std::vector<SField> lapModes;
        std::vector<Real>   lapEigs;
        success = solver->GeneralizedEigenvalueProblem(numModes / 2,
                                              L, M, lapModes, lapEigs);
        assert(numModes / 2 == lapModes.size());

        m_modes.clear(), m_eigenvalues.clear();
        m_modes.reserve(lapModes.size() * 2);
        m_eigenvalues.reserve(lapEigs.size() * 2);
        VField expanded(L.n);
        for (size_t m = 0; m < lapModes.size(); ++m) {
            const SField &mode = lapModes[m];
            // x mode
            expanded.clear();
            for (size_t i = 0; i < L.n; ++i)
                expanded(i)[0] = mode[i];
            m_modes.push_back(expanded);
            m_eigenvalues.push_back(lapEigs[m]);

            // y mode
            expanded.clear();
            for (size_t i = 0; i < L.n; ++i)
                expanded(i)[1] = mode[i];
            m_modes.push_back(expanded);
            m_eigenvalues.push_back(lapEigs[m]);
        }

        numModes = m_modes.size();

        // Normalize so all (nonzero) modes inject unit energy
        for (size_t i = numRigidModes(); i < numModes; ++i) {
            m_modes[i] *= (1.0 / m_computeEnergy(m_modes[i]));
        }
    }
    else {
        // Use stiffness modes
        TMatrix K, M;
        m_assembleStiffnessMatrix(K);
        m_assembleMassMatrix(M);

        size_t numModes = std::min((size_t) m_numRequestedModes, K.n);
        std::vector<SField> eigenVectors;
        success = solver->GeneralizedEigenvalueProblem(numModes,
                                          K, M, eigenVectors, m_eigenvalues);
        assert(numModes == eigenVectors.size());
        m_modes.clear(); m_modes.reserve(eigenVectors.size());
        for (auto it = eigenVectors.begin(); it != eigenVectors.end(); ++it) {
            // Convert to a vector field
            m_modes.push_back(it->template unflatten<2>());
        }

        // Normalize so all (nonzero) modes inject unit energy
        // Mode energy = 1/2 u^T K u = 1/2 lambda u^T M u := 1
        // ==> u^T M u = 2 / lambda
        // Eigensolver gives us u^T M u = 1, so we must just scale u by
        // sqrt(2 / lambda)
        for (size_t i = 0; i < numModes; ++i) {
            Real lambda = eigenvalue(i);
            if (lambda > (Real) 1e-6)
                m_modes[i] *= sqrt(2.0 / lambda);
        }
    }

    m_modalStressTensors.clear();
    m_modalStressNorms.clear();
    m_weakRegions.clear();
    m_weakRegionStressNorms.clear();

    if (success) {
        size_t numModes = m_modes.size();
        // Compute modal stress tensors.
        m_modalStressTensors.reserve(numModes);
        for (size_t i = 0; i < numModes; ++i)
            m_modalStressTensors.push_back(elementStressTensors(mode(i)));

        // Compute (signed) modal stress norms, optionally choosing signs for
        // modes so that the largest stress becomes a compression (for
        // consistency across eigensolves).
        for (size_t i = 0; i < numModes; ++i) {
            m_modalStressNorms.push_back(
                    computeStressTensorNorms(m_modalStressTensors[i], true));
            if (m_consistentSigns) {
                if (m_modalStressNorms.back().signedMaxMag() > 0) {
                    m_modalStressNorms.back() *= -1.0;
                    m_modalStressTensors[i] *= -1.0;
                    m_modes[i] *= -1.0;
                }
            }
        }

        if (rc != NULL) {
            // Record the modes/modal stresses in the results collector.
            for (size_t i = 0; i < numModes; ++i) {
                typedef typename RC::Result Result;
                typedef typename RC::RPtr   RPtr;
                RPtr r(new Result(elementGrid(),
                                  Result::PER_ELEM, m_modalStressNorms[i],
                                  Result::PER_NODE, mode(i)));
                rc->setResult(appendToString("Modes:Mode ", i), r);
            }
        }
    }

    return success;
}

template<typename Model>
bool MeshlessFEM<Model>::simulate(RC *rc) {
    TMatrix K, F, R, N, A;
    m_assembleStiffnessMatrix(K);
    m_assembleLoadMatrix(F);
    m_assembleRigidModeMatrix(R);
    m_assembleNMatrix(N);
    m_assembleAMatrix(A);
    // Note: the following aren't actually needed for simulation
    TMatrix B, VD;
    m_assembleBMatrix(B);
    m_assembleVDMatrix(VD);
    Solver<Real> *solver = m_solvers.solver();

    std::vector<size_t> dirichletIndices;
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    for (size_t i = 0; i < elemGrid.numNodes(); ++i) {
        if (m_boundaryConditions.hasDirichlet(elemGrid.nodePosition(i))) {
            // Add a constraint for each component of the fixed node's disp.
            for (size_t j = 0; j < dim(); ++j)
                dirichletIndices.push_back(dim() * i + j);
        }
    }

    solver->configureAnalysis(K, F, R, N, A, B, VD, m_totalForceBound,
                              m_pointwisePressureBound, dirichletIndices);
    VField forces;
    m_boundaryConditions.getForces(m_boundaryPoints, forces);
    solver->simulate(forces, m_simulatedDisplacement);

    m_simulatedStressTensors = elementStressTensors(m_simulatedDisplacement);
    m_simulatedStressNorms = computeStressTensorNorms(m_simulatedStressTensors);

    typedef typename RC::Result Result;
    typedef typename RC::RPtr RPtr;
    if (rc != NULL) {
        // Record the displacements/stresses in the results collector.

        // MatlabEigenSolver variants provide access to the blurred volume
        // force. If that's what we're using, save this force for debugging.
        MatlabEigenSolver<Real> *s =
                dynamic_cast<MatlabEigenSolver<Real> *>(solver);
        if (s) {
            VField volForce;
            s->getVolumeForceForForces(forces, volForce);
            RPtr f_r(new Result(elemGrid,
                                Result::PER_ELEM, m_simulatedStressNorms,
                                Result::PER_NODE, volForce));
            rc->setResult("Blurred Boundary Forces", f_r);
        }

        RPtr r(new Result(elemGrid,
                          Result::PER_ELEM, m_simulatedStressNorms,
                          Result::PER_NODE, m_simulatedDisplacement));
        rc->setResult("Simulation", r);

        // Element volume scalar field for debug
        // SField volumes(elementGrid().numElements());
        // for (size_t i = 0; i < volumes.size(); ++i) {
        //     volumes[i] = elementGrid().elementOverlap(i);
        // }

        // r = new Result(Result::PER_ELEM, volumes);
        // rc->setResult("Element Volume", r);
    }

    // if (mshPath) {
    //     size_t numNodes = elementGrid().numNodes();
    //     VectorField<Real, 3> disp3Vector(numNodes);
    //     disp3Vector.clear();
    //     for (size_t i = 0; i < numNodes; ++i) {
    //         disp3Vector(i)[0] = m_simulatedDisplacement(i)[0];
    //         disp3Vector(i)[1] = m_simulatedDisplacement(i)[1];
    //     }
    //     MSHWriter<ElementGrid> mshOut(mshPath, elementGrid());
    //     mshOut.addField("sim u", disp3Vector, MSHWriter<ElementGrid>::PER_NODE);
    //     mshOut.addField("sim stress norms", m_simulatedStressNorms,
    //                     MSHWriter<ElementGrid>::PER_ELEMENT);
    // }

    return true;
}
// Return Values
//  -1: modal analysis failure
//   0: success
//   1: success, and modes were updated
template<typename Model>
int MeshlessFEM<Model>::weakRegionExtraction(RC *rc)
{
    bool recomputedModes = false;
    if (m_modes.size() == 0) {
        if (!modalAnalysis(rc))
            return -1;
        recomputedModes = true;
    }

    m_weakRegions.clear();
    m_weakRegionStressNorms.clear();

    const ElementGrid &grid = elementGrid();
    for (size_t m = numRigidModes(); m < m_modes.size(); ++m) {
        // compute the stress cutoff value
        const SField &stressNorms = m_modalStressNorms[m];
        const VField &modalDisp   = m_modes[m];
        assert(stressNorms.size() == grid.numElements());

        std::vector<size_t> sortedElements;
        sortPermutation(AbsWrapper<SField>(stressNorms), sortedElements);

        // Everything above the cutoff percentile is a weak region
        size_t cutoff = m_weaknessCutoff * sortedElements.size();
        std::vector<int> wrIndex(sortedElements.size(), -1);
        for (size_t i = cutoff; i < sortedElements.size(); ++i) {
            // Flag as part of a weak region
            wrIndex[sortedElements[i]] = 0;
        }

        // Extract connected components (BFS-based)
        int tag = 0;
        std::vector<size_t> adj;
        for (size_t i = 0; i < wrIndex.size(); ++i) {
            if (wrIndex[i] != 0) continue;

            ++tag;
            wrIndex[i] = tag;

            std::queue<size_t> bfsQueue;
            // Queue contains elements who have already been tagged, but whose
            // neighbors might not have been.
            // Each element appears at most once in the queue (an old version
            // didn't have this guarantee, and memory blew up!).
            bfsQueue.push(i);
            while (!bfsQueue.empty()) {
                size_t u = bfsQueue.front();
                bfsQueue.pop();
                grid.elementsAdjacentElement(u, adj);
                for (size_t j = 0; j < adj.size(); ++j) {
                    size_t v = adj[j];
                    assert(v < wrIndex.size());
                    if (wrIndex[v] == 0) {
                        wrIndex[v] = tag;
                        bfsQueue.push(v);
                    }
                }
            }
        }

        std::vector<std::vector<size_t> > regions(tag);

        // Extract weak region contents (numbered 1...# regions)
        for (size_t i = 0; i < wrIndex.size(); ++i) {
            assert(wrIndex[i] != 0);
            if (wrIndex[i] > 0) {
                assert(((size_t) wrIndex[i]) <= regions.size());
                regions[wrIndex[i] - 1].push_back(i);
            }
        }

        // Compute energy in each weak region
        std::vector<Real> energies(regions.size(), 0);
        CornerVec cornerIndices;
        for (size_t r = 0; r < regions.size(); ++r) {
            energies[r] = m_computeEnergy(modalDisp, regions[r]);
        }

        // Sort weak regions by energy
        std::vector<size_t> sortedRegions;
        sortPermutation(energies, sortedRegions, true);

        // Take the top m_weakRegionsPerMode
        size_t numWR = std::min((size_t) m_weakRegionsPerMode,
                                         sortedRegions.size());
        for (size_t i = 0; i < numWR; ++i) {
            m_weakRegions.push_back(regions[sortedRegions[i]]);
            m_weakRegionStressNorms.push_back(SField(stressNorms.size()));
            m_weakRegionStressNorms.back().clear();
            size_t wrSize = m_weakRegions.back().size();
            for (size_t j = 0; j < wrSize; ++j) {
                size_t ei = m_weakRegions.back()[j];
                m_weakRegionStressNorms.back()[ei] = stressNorms[ei];
            }
        }
    }

    if (rc != NULL) {
        // Record the weak regions in the results collector.
        for (size_t i = 0; i < m_weakRegionStressNorms.size(); ++i) {
            typedef typename RC::Result Result;
            typedef typename RC::RPtr RPtr;
            RPtr r(new Result(grid, Result::PER_ELEM,
                              m_weakRegionStressNorms[i]));
            rc->setResult(appendToString("Weak Regions:Region ", i), r);
        }
    }

    return recomputedModes ? 1 : 0;
}

template<typename Model>
bool MeshlessFEM<Model>::weaknessAnalysis(Real &weaknessCriterion, RC *rc)
{
    typedef typename RC::Result Result;
    typedef typename RC::RPtr RPtr;

    int ret = weakRegionExtraction(rc);
    if (ret < 0)
        return false;

    Solver<Real> *solver = m_solvers.solver();

    TMatrix K, F, R, N, A, B, VD;
    m_assembleStiffnessMatrix(K);
    m_assembleLoadMatrix(F);
    m_assembleRigidModeMatrix(R);
    m_assembleNMatrix(N);
    m_assembleAMatrix(A);
    m_assembleBMatrix(B);
    m_assembleVDMatrix(VD);
    solver->configureAnalysis(K, F, R, N, A, B, VD, m_totalForceBound,
                                m_pointwisePressureBound);

    const ElementGrid2D<Model> &elemGrid = elementGrid();
    size_t numNodes = elemGrid.numNodes();
    size_t numElems = elemGrid.numElements();

    m_combinedWeakness.resizeDomain(numElems);
    m_combinedWeakness.clear();

    DVector w;
    SField pressures;
    for (size_t i = 0; i < numWeakRegions(); ++i) {
        m_assembleWVector(w, i);
        for (int pass = 0; pass < 2; ++pass) {
            if ((pass > 0) && !m_plusMinusObjective)
                break;

            if (pass == 1)
                w *= -1.0;

            solver->optimizeObjective(w, pressures);
            VField optU(numNodes);
            solver->simulate(pressures, optU);

            SMField stressTensors = elementStressTensors(optU);
            SField  optStress = computeStressTensorNorms(stressTensors);

            if (rc != NULL) {
                RPtr r(new Result(elemGrid, Result::PER_BDRY, pressures));
                string regionName = appendToString("Weak Regions:Region ", i);
                string pmName;
                if (m_plusMinusObjective)
                    pmName = (pass == 0) ? " (+)" : " (-)";
                rc->setResult(regionName + ":Opt Pressure" + pmName, r);

                r = RPtr(new Result(elemGrid, Result::PER_ELEM, optStress,
                                    Result::PER_NODE, optU));
                rc->setResult(regionName + ":Opt Displacement" + pmName, r);
            }

            m_combinedWeakness.maxRelax(optStress);
        }
    }

    if (rc != NULL) {
        RPtr r(new Result(elemGrid, Result::PER_ELEM, m_combinedWeakness));
        rc->setResult("Combined Weakness", r);
    }

    // MatlabSolver<Real> *matsolver = dynamic_cast<MatlabSolver<Real> *>(solver);
    // if (matsolver) {
    //     matsolver->getMatlabInterface()->SetEngineRealMatrix("cw",
    //             m_combinedWeakness.size(), 1, m_combinedWeakness.data());
    // }

    std::vector<size_t> cwSortPerm;
    sortPermutation(m_combinedWeakness, cwSortPerm);
    assert(cwSortPerm.size() == numElems);

    DVector volumes(numElems);
    for (size_t i = 0; i < numElems; ++i)
        volumes[i] = m_elementData[i].volume();

    Real accumVol = 0.0;
    DVector percentile(numElems);
    for (size_t i = 0; i < numElems; ++i) {
        accumVol += volumes[cwSortPerm[i]];
        percentile[cwSortPerm[i]] = accumVol;
    }
    percentile *= (1.0 / accumVol);

    // // Find the highest stress *full* element (stress is averaged over elements,
    // // so partial elements have an unfair advantage in the rankings)
    // Real weaknessCriterion = m_combinedWeakness[cwSortPerm.back()];
    // for (int i = cwSortPerm.size() - 1; i >= 0; --i) {
    //     if (elemGrid.elementIsFull(cwSortPerm[i])) {
    //         weaknessCriterion = m_combinedWeakness[cwSortPerm[i]];
    //         break;
    //     }
    // }
    
    // Lp norm
    Real p = 20;
    weaknessCriterion = 0.0;
    Real totalVol = 0.0;
    for (size_t i = 0; i < m_combinedWeakness.size(); ++i) {
        weaknessCriterion += pow(m_combinedWeakness[i], p) * volumes[i];
        totalVol += volumes[i];
    }
    weaknessCriterion = pow(weaknessCriterion, 1.0 / p) / totalVol;

    std::cout << "Weakness criterion: " << weaknessCriterion << std::endl;

    m_weaknessCriterion = weaknessCriterion;

    // solver->setDenseMatrix("volumes", volumes.rows(),
    //         1, volumes.data(), true);
    // solver->setDenseMatrix("cwp", percentile.rows(),
    //         1, percentile.data(), true);

    // if (cwPath) {
    //     std::ofstream cwFile(cwPath);
    //     if (!cwFile.is_open()) {
    //         std::cout << "Failed to open output file '"
    //                   << cwPath << '\'' << std::endl;
    //     }
    //     else{
    //         cwFile << m_combinedWeakness;
    //     }
    // }
    // if (cwPercentilePath) {
    //     std::ofstream cwpFile(cwPercentilePath);
    //     if (!cwpFile.is_open()) {
    //         std::cout << "Failed to open output file '"
    //                   << cwPercentilePath << '\'' << std::endl;
    //     }
    //     else{
    //         cwpFile << percentile;
    //     }
    // }

    return true;
}

template<typename Model>
void MeshlessFEM<Model>::m_assembleWVector(DVector &w, size_t regionIdx) const {
    size_t numElems = elementGrid().numElements();
    w.resize(3 * numElems, Eigen::NoChange);
    if (regionIdx < m_weakRegions.size()) {
        const SField &weights = m_weakRegionStressNorms[regionIdx];
        assert(weights.size() == numElems);
        for (size_t i = 0; i < numElems; ++i) {
            Real weight = weights[i];
            // In abstrace mode, we use the modal stress sign to choose between
            // maximizing +trace or -trace on a per-element basis. Not in
            // abstrace mode, we always optimize
            if (!m_abstrace) weight = std::abs(weight);
            w[3 * i + 0] = weight;
            w[3 * i + 1] = weight;
            w[3 * i + 2] = 0;
        }
    }
    else {
        for (size_t i = 0; i < numElems; ++i) {
            // Compute total trace everywhere
            w[3 * i + 0] = 1;
            w[3 * i + 1] = 1;
            w[3 * i + 2] = 0;
        }
    }
}

template<typename Model>
void MeshlessFEM<Model>::m_invalidateCache() {
    m_stiffnessCached = false;
    m_massCached = false;
    m_modes.clear();
    m_displacementStrainCached = false;
    m_elementData.clear();

    if (m_useMarchingSquaresBoundary) {
        m_boundaryPoints.clear();

        std::vector<Polygon_t> polygons;
        MarchingSquaresGrid ms(elementGrid().interiorCols(),
                               elementGrid().interiorRows());
        ms.extractBoundaryPolygons(m_model, polygons);
        for (size_t p = 0; p < polygons.size(); ++p) {
            const std::vector<Vector> &points = polygons[p].points;
            m_boundaryPoints.reserve(m_boundaryPoints.size() +
                                     points.size());
            Vector prevSegment = points[0] - points.back();
            for (size_t i = 0; i < points.size(); ++i) {
                Vector nextSegment =
                        points[(i + 1) % points.size()] - points[i];
                Real a = .5 * (prevSegment.norm() + nextSegment.norm());
                // Normals: rotate tangent clockwise 90 degrees
                // (y = -x, x = y)
                Vector n = Vector(prevSegment[1], -prevSegment[0]) +
                           Vector(nextSegment[1], -nextSegment[0]);
                n /= n.norm();
                m_boundaryPoints.push_back(_BoundaryPoint(points[i], n, a));

                prevSegment = nextSegment;
            }
        }
    }
    else {
        m_boundaryPoints = m_model.boundaryPoints(m_boundaryPointSpacing);
    }
    m_boundaryFunctions.clear();

    // Only resize the pressures if necessary. If the number of boundary points
    // doesn't change, pressure values are retained. Otherwise, they are
    // cleared.
    if (m_boundaryConditions.boundarySize() != m_boundaryPoints.size())
        m_boundaryConditions.resizeBoundary(m_boundaryPoints.size());

    m_weakRegions.clear();
    m_weakRegionStressNorms.clear();

    m_combinedWeakness.resizeDomain(0);
}

////////////////////////////////////////////////////////////////////////////////
// Template instantiations
////////////////////////////////////////////////////////////////////////////////
#include "GlobalTypes.hh"
template class MeshlessFEM<CSGTree_t>;
