#include <Eigen/Dense>
#include <iostream>
#include <algorithm>

// Element node ordering:
// 3         2
//  +-------+
//  |       |
//  |       |
//  |       |
//  +-------+
// 0         1

template<typename Model>
class MeshlessFEM<Model>::PerElementStiffnessDensity
{
public:
    typedef Eigen::Matrix<Real, 8, 8> value_type;
    // D: (d00, d01, d10, d11, d22)
    PerElementStiffnessDensity(const DType &d, const Model &model)
        : m_model(model), m_d(d) { clear(); }

    void clear() { result = value_type::Zero(); }

    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        Real x = ref_sample[0], y = ref_sample[1];

        // The following formulas are automaticaly generated by
        // Derivations/2DStiffness.mpl
        // .5 scaling for d22 is to account for engineering stress * strain
        // double counting the off-diagonals.
        Real d00 = m_d[0], d01 = m_d[1], d10 = m_d[1], d11 = m_d[2], d22 = .5 * m_d[3];
        Real invW = 1.0 / m_dimensions[0];
        Real invH = 1.0 / m_dimensions[1];

        result(0, 0) += weight * (invW * invW * y * y * d00 - 2 * invW * invW * d00 * y + invW * invW * d00 + invH * invH * d22 - 2 * invH * invH * d22 * x + invH * invH * x * x * d22);
        result(0, 1) += weight * (invW * d01 * invH - invW * d01 * invH * x - invW * d01 * invH * y + invW * y * d01 * invH * x + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(0, 2) += weight * (2 * invW * invW * d00 * y - invW * invW * y * y * d00 - invW * invW * d00 - invH * invH * x * x * d22 + invH * invH * d22 * x);
        result(0, 3) += weight * (-invW * y * d01 * invH * x + invW * d01 * invH * x + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(0, 4) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(0, 5) += weight * (invW * y * d01 * invH * x - invW * d01 * invH * x + invH * x * d22 * invW * y - invW * d22 * invH * y);
        result(0, 6) += weight * (-invW * invW * y * y * d00 + invW * invW * d00 * y + 2 * invH * invH * d22 * x - invH * invH * x * x * d22 - invH * invH * d22);
        result(0, 7) += weight * (invW * d01 * invH * y - invW * d01 * invH - invW * y * d01 * invH * x + invW * d01 * invH * x - invH * x * d22 * invW * y + invW * d22 * invH * y);
        result(1, 0) += weight * (invH * d10 * invW - invH * x * d10 * invW - invH * d10 * invW * y + invH * x * d10 * invW * y + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(1, 1) += weight * (invH * invH * d11 - 2 * invH * invH * d11 * x + invH * invH * x * x * d11 + invW * invW * y * y * d22 - 2 * invW * invW * d22 * y + invW * invW * d22);
        result(1, 2) += weight * (invH * d10 * invW * y - invH * d10 * invW - invH * x * d10 * invW * y + invH * x * d10 * invW - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(1, 3) += weight * (-invH * invH * x * x * d11 + invH * invH * d11 * x + 2 * invW * invW * d22 * y - invW * invW * y * y * d22 - invW * invW * d22);
        result(1, 4) += weight * (invH * x * d10 * invW * y - invH * d10 * invW * y + invH * x * d22 * invW * y - invW * d22 * invH * x);
        result(1, 5) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(1, 6) += weight * (-invH * x * d10 * invW * y + invH * d10 * invW * y + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(1, 7) += weight * (2 * invH * invH * d11 * x - invH * invH * x * x * d11 - invH * invH * d11 - invW * invW * y * y * d22 + invW * invW * d22 * y);
        result(2, 0) += weight * (2 * invW * invW * d00 * y - invW * invW * y * y * d00 - invW * invW * d00 - invH * invH * x * x * d22 + invH * invH * d22 * x);
        result(2, 1) += weight * (invW * d01 * invH * y - invW * d01 * invH - invW * y * d01 * invH * x + invW * d01 * invH * x - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(2, 2) += weight * (invW * invW * y * y * d00 - 2 * invW * invW * d00 * y + invW * invW * d00 + invH * invH * x * x * d22);
        result(2, 3) += weight * (-invW * d01 * invH * x + invW * y * d01 * invH * x - invW * d22 * invH * x + invH * x * d22 * invW * y);
        result(2, 4) += weight * (invW * invW * d00 * y - invW * invW * y * y * d00 - invH * invH * x * x * d22);
        result(2, 5) += weight * (invW * d01 * invH * x - invW * y * d01 * invH * x - invH * x * d22 * invW * y);
        result(2, 6) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(2, 7) += weight * (invW * d01 * invH - invW * d01 * invH * x - invW * d01 * invH * y + invW * y * d01 * invH * x + invH * x * d22 * invW * y);
        result(3, 0) += weight * (-invH * x * d10 * invW * y + invH * x * d10 * invW + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(3, 1) += weight * (-invH * invH * x * x * d11 + invH * invH * d11 * x + 2 * invW * invW * d22 * y - invW * invW * y * y * d22 - invW * invW * d22);
        result(3, 2) += weight * (-invH * x * d10 * invW + invH * x * d10 * invW * y - invW * d22 * invH * x + invH * x * d22 * invW * y);
        result(3, 3) += weight * (invH * invH * x * x * d11 + invW * invW * y * y * d22 - 2 * invW * invW * d22 * y + invW * invW * d22);
        result(3, 4) += weight * (-invH * x * d10 * invW * y + invW * d22 * invH * x - invH * x * d22 * invW * y);
        result(3, 5) += weight * (-invH * invH * x * x * d11 + invW * invW * d22 * y - invW * invW * y * y * d22);
        result(3, 6) += weight * (invH * x * d10 * invW * y + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(3, 7) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(4, 0) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(4, 1) += weight * (invW * y * d01 * invH * x - invW * d01 * invH * y + invH * x * d22 * invW * y - invW * d22 * invH * x);
        result(4, 2) += weight * (invW * invW * d00 * y - invW * invW * y * y * d00 - invH * invH * x * x * d22);
        result(4, 3) += weight * (-invW * y * d01 * invH * x + invW * d22 * invH * x - invH * x * d22 * invW * y);
        result(4, 4) += weight * (invW * invW * y * y * d00 + invH * invH * x * x * d22);
        result(4, 5) += weight * (invW * y * d01 * invH * x + invH * x * d22 * invW * y);
        result(4, 6) += weight * (-invW * invW * y * y * d00 + invH * invH * d22 * x - invH * invH * x * x * d22);
        result(4, 7) += weight * (invW * d01 * invH * y - invW * y * d01 * invH * x - invH * x * d22 * invW * y);
        result(5, 0) += weight * (invH * x * d10 * invW * y - invH * x * d10 * invW + invH * x * d22 * invW * y - invW * d22 * invH * y);
        result(5, 1) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(5, 2) += weight * (invH * x * d10 * invW - invH * x * d10 * invW * y - invH * x * d22 * invW * y);
        result(5, 3) += weight * (-invH * invH * x * x * d11 + invW * invW * d22 * y - invW * invW * y * y * d22);
        result(5, 4) += weight * (invH * x * d10 * invW * y + invH * x * d22 * invW * y);
        result(5, 5) += weight * (invH * invH * x * x * d11 + invW * invW * y * y * d22);
        result(5, 6) += weight * (-invH * x * d10 * invW * y + invW * d22 * invH * y - invH * x * d22 * invW * y);
        result(5, 7) += weight * (invH * invH * d11 * x - invH * invH * x * x * d11 - invW * invW * y * y * d22);
        result(6, 0) += weight * (-invW * invW * y * y * d00 + invW * invW * d00 * y + 2 * invH * invH * d22 * x - invH * invH * x * x * d22 - invH * invH * d22);
        result(6, 1) += weight * (-invW * y * d01 * invH * x + invW * d01 * invH * y + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(6, 2) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(6, 3) += weight * (invW * y * d01 * invH * x + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(6, 4) += weight * (-invW * invW * y * y * d00 + invH * invH * d22 * x - invH * invH * x * x * d22);
        result(6, 5) += weight * (-invW * y * d01 * invH * x + invW * d22 * invH * y - invH * x * d22 * invW * y);
        result(6, 6) += weight * (invW * invW * y * y * d00 + invH * invH * d22 - 2 * invH * invH * d22 * x + invH * invH * x * x * d22);
        result(6, 7) += weight * (-invW * d01 * invH * y + invW * y * d01 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(7, 0) += weight * (invH * d10 * invW * y - invH * d10 * invW - invH * x * d10 * invW * y + invH * x * d10 * invW - invH * x * d22 * invW * y + invW * d22 * invH * y);
        result(7, 1) += weight * (2 * invH * invH * d11 * x - invH * invH * x * x * d11 - invH * invH * d11 - invW * invW * y * y * d22 + invW * invW * d22 * y);
        result(7, 2) += weight * (invH * d10 * invW - invH * x * d10 * invW - invH * d10 * invW * y + invH * x * d10 * invW * y + invH * x * d22 * invW * y);
        result(7, 3) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(7, 4) += weight * (invH * d10 * invW * y - invH * x * d10 * invW * y - invH * x * d22 * invW * y);
        result(7, 5) += weight * (invH * invH * d11 * x - invH * invH * x * x * d11 - invW * invW * y * y * d22);
        result(7, 6) += weight * (-invH * d10 * invW * y + invH * x * d10 * invW * y - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(7, 7) += weight * (invH * invH * d11 - 2 * invH * invH * d11 * x + invH * invH * x * x * d11 + invW * invW * y * y * d22);
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 8) && (j < 8));
        return result(i, j);
    }

private:
    const Model &m_model;
    const DType &m_d;
    Vector m_dimensions;

    value_type result;
};

// Average grad phi over the element.
template<typename Model>
class MeshlessFEM<Model>::PerElementGradPhi
{
public:
    // D: (d00, d01, d10, d11, d22)
    PerElementGradPhi(const Model &model)
        : m_model(model) { clear(); }

    void clear() {
        result = GradPhis::Zero();
        m_volume = 0.0;
    }

    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        Real x = ref_sample[0], y = ref_sample[1];
        // phi0 = (1 - x) * (1 - y) => grad phi0 = (invW (y - 1), invH (x - 1))
        // phi1 =      x  * (1 - y) => grad phi1 = (invW (1 - y), invH (   -x))
        // phi2 =      x  *      y  => grad phi2 = (invW (    y), invH (    x))
        // phi3 = (1 - x) *      y  => grad phi3 = (invW (   -y), invH (1 - x))
        Real invW = 1.0 / m_dimensions[0];
        Real invH = 1.0 / m_dimensions[1];
        Real xWeight = weight * invW;
        Real yWeight = weight * invH;

        result(0, 0) += xWeight * (y - 1); result(0, 1) += yWeight * (x - 1);
        result(1, 0) += xWeight * (1 - y); result(1, 1) += yWeight * (   -x);
        result(2, 0) += xWeight * (    y); result(2, 1) += yWeight * (    x);
        result(3, 0) += xWeight * (   -y); result(3, 1) += yWeight * (1 - x);

        // volume = \int 1 * dV
        m_volume += weight;
    }

    void finalize() {
        result /= m_volume;
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 8) && (j < 8));
        return result(i, j);
    }

    // Allow type cast to GradPhi
    operator const GradPhis &() const {
        return result;
    }

private:
    const Model &m_model;
    GradPhis result;
    Vector m_dimensions;
    Real m_volume;
};

template<typename Model>
class MeshlessFEM<Model>::PerElementMassMatrixDensity
{
public:
    typedef Eigen::Matrix<Real, 4, 4> value_type;
    PerElementMassMatrixDensity(const Model &model, Real density,
                                   MassMatrixType type = MASS_QUARTER_CELL)
        : m_model(model), m_density(density), m_type(type)
    {
        clear();
    }

    void clear() {
        result = value_type::Zero();
        m_element_mass = 0.0;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        m_element_mass += weight * m_density;

        Real x = ref_sample[0], y = ref_sample[1];
        // Node ordering: 3 2
        //                0 1
        Eigen::Matrix<Real, 4, 1> phi;
        phi[0] = (1 - x) * (1 - y);
        phi[1] =      x  * (1 - y);
        phi[2] =      x  *      y ;
        phi[3] = (1 - x) *      y ;

        for (size_t i = 0; i < 4; ++i) {
            for (size_t j = 0; j < 4; ++j) {
                result(i, j) += weight * m_density * phi[i] * phi[j];
            }
        }
    }

    Real operator()(size_t i, size_t j) const {
        Real val = 0.0;
        if (m_type == MASS_LUMPED) {
            if (i == j) {
                val = .25 * (result(i, 0) + result(i, 1) +
                             result(i, 2) + result(i, 3));
            }
        }
        else if (m_type == MASS_QUARTER_CELL) {
            if (i == j) {
                val = .25 * m_element_mass;
            }
        }
        else if (m_type == MASS_FULL) {
            val = result(i, j);
        }
        else {
            assert(false);
        }
        return val;
    }

private:
    const Model &m_model;
    Real m_density;
    MassMatrixType m_type;

    value_type result;
    Real m_element_mass;
};

template<typename Model>
class MeshlessFEM<Model>::ElementData
{
public:
    ElementData() { }

    void setGradPhis(const GradPhis &gp) {
        m_gradPhis = gp;
    }

    typedef typename MeshlessFEM<Model>::FlattenedTensor FlattenedTensor;

    // Compute non-engineering strain tensor for linear elasticity:
    // e_xx = d u_x / dx = u_0_x d phi_0 / dx + u_1_x d phi_1 / dx + ...
    // e_yy = d u_y / dy = u_0_y d phi_0 / dy + u_1_y d phi_1 / dy + ...
    // e_xy = .5 * (d u_y / dx + d u_x / dy) = u_0_x d phi_0 / dy + ...
    template<typename Tensor>
    void displacementToStrain(const VField &displacements,
                              const CornerVec &corners, Tensor &strain) const
    {
        strain[0] = strain[1] = strain[2] = 0;

        for (size_t c = 0; c < (size_t) corners.size(); ++c) {
            size_t v = corners[c];
            // e_xx contribution
            strain[0] += m_gradPhis(c, 0) * displacements(v)[0];
            // e_yy contribution
            strain[1] += m_gradPhis(c, 1) * displacements(v)[1];
            // e_xy contribution
            strain[2] += .5 * (m_gradPhis(c, 0) * displacements(v)[1]
                            +  m_gradPhis(c, 1) * displacements(v)[0]);
        }
    }

    // Compute non-engineering stress tensor for linear elasticity:
    // sigma = D * B * u = D * displacementToStress
    // D = d00 d01   0 =  d0 d1   0 
    //     d10 d11   0    d1 d2   0
    //     0   0   d22    0   0   d3
    template<typename Tensor>
    void displacementToStress(const VField &displacements,
                              const CornerVec &corners, const DType &d,
                              Tensor &stress) const
    {
        FlattenedTensor strain;
        displacementToStrain(displacements, corners, strain);
        stress[0] = d[0] * strain[0] + d[1] * strain[1];
        stress[1] = d[1] * strain[0] + d[2] * strain[1];
        stress[2] = d[3] * strain[2];
    }
    
private:
    GradPhis m_gradPhis;
};

template<typename Model>
void MeshlessFEM<Model>::m_assembleStiffnessMatrix(size_t &n, IndexVec &mat_i,
        IndexVec &mat_j, std::vector<Real> &mat_v)
{
    // Simple (i, j v) stiffness matrix generation
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();
    n = 2 * elemGrid.numNodes();
    PerElementStiffnessDensity stiff(m_d, model());
    CornerVec cornerIndices;

    mat_i.clear(); mat_j.clear(); mat_v.clear();

    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        stiff.clear();
        BBox_t b = elemGrid.elementBoundingBox(e);
        stiff.setDimensions(b.dimensions());
        q.integrate(stiff, b);
        elemGrid.elementCorners(e, cornerIndices);
        for (size_t i = 0; i < 4; ++i) {
            size_t vi = cornerIndices[i];
            for (size_t j = 0; j < 4; ++j) {
                size_t vj = cornerIndices[j];
                // xx
                mat_i.push_back(2 * vi);
                mat_j.push_back(2 * vj);
                mat_v.push_back(stiff(2 * i, 2 * j));

                // xy
                mat_i.push_back(2 * vi);
                mat_j.push_back(2 * vj + 1);
                mat_v.push_back(stiff(2 * i, 2 * j + 1));

                // yy
                mat_i.push_back(2 * vi + 1);
                mat_j.push_back(2 * vj + 1);
                mat_v.push_back(stiff(2 * i + 1, 2 * j + 1));

                // yx
                mat_i.push_back(2 * vi + 1);
                mat_j.push_back(2 * vj);
                mat_v.push_back(stiff(2 * i + 1, 2 * j));
            }
        }
    }
}


// Compute the quantities needed to evaluate strain from displacement.
template<typename Model>
void MeshlessFEM<Model>::m_computePerElementDisplacementStrainMap()
{
    // Simple (i, j v) stiffness matrix generation
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();
    PerElementGradPhi gradPhi(model());

    size_t numElements = elemGrid.numElements();
    if (m_elementData.size() != numElements) {
        m_elementData.resize(numElements);
    }
    for (size_t e = 0; e < numElements; ++e) {
        gradPhi.clear();
        BBox_t b = elemGrid.elementBoundingBox(e);
        gradPhi.setDimensions(b.dimensions());
        q.integrate(gradPhi, b);
        gradPhi.finalize();
        m_elementData[e].setGradPhis(gradPhi);
    }

    m_displacementStrainCached = true;
}

template<typename Model>
typename MeshlessFEM<Model>::SMField
MeshlessFEM<Model>::elementStressTensors(const VField &displacement)
{
    if (!m_displacementStrainCached) {
        m_computePerElementDisplacementStrainMap();
    }
    size_t numElements = elementGrid().numElements();
    assert(m_elementData.size() == numElements);

    SMField stressTensorField(numElements);

    const ElementGrid2D<Model> &elemGrid = elementGrid();
    for (size_t e = 0; e < numElements; ++e) {
        CornerVec cornerIndices;
        elemGrid.elementCorners(e, cornerIndices);
        typename SMField::SymmetricMatrix tensor = stressTensorField(e);
        m_elementData[e].displacementToStress(displacement, cornerIndices, m_d,
                                              tensor);
    }

    return stressTensorField;
}


template<typename Model>
typename MeshlessFEM<Model>::SField
MeshlessFEM<Model>::computeStressTensorNorms(const SMField &stressField)
{
    size_t numMats = stressField.domainSize();
    VField eigenvalues = m_solver->symm2x2Eigenvalues(stressField);
    assert(eigenvalues.domainSize() == numMats);
    SField result(numMats);

    for (size_t i = 0; i < numMats; ++i)
        result[i] = std::max(fabs(eigenvalues(i)[0]), fabs(eigenvalues(i)[1]));

    return result;
}

template<typename Model>
void MeshlessFEM<Model>::m_assembleMassMatrix(size_t &n, IndexVec &mat_i,
        IndexVec &mat_j, std::vector<Real> &mat_v)
{
    // Simple (i, j v) mass matrix generation
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();
    n = 2 * elemGrid.numNodes();
    PerElementMassMatrixDensity lmass(model(), m_density, m_massMatrixType);
    CornerVec cornerIndices;

    mat_i.clear(); mat_j.clear(); mat_v.clear();

    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        lmass.clear();
        q.integrate(lmass, elemGrid.elementBoundingBox(e));
        elemGrid.elementCorners(e, cornerIndices);
        for (size_t i = 0; i < 4; ++i) {
            size_t vi = cornerIndices[i];
            for (size_t j = 0; j < 4; ++j) {
                size_t vj = cornerIndices[j];
                Real val = lmass(i, j);
                if (val > 1e-12) {
                    mat_i.push_back(2 * vi);
                    mat_j.push_back(2 * vj);
                    mat_v.push_back(val);

                    mat_i.push_back(2 * vi + 1);
                    mat_j.push_back(2 * vj + 1);
                    mat_v.push_back(val);
                }
            }
        }
    }
}
