#include <Eigen/Dense>
#include <iostream>
#include <algorithm>
#include "MeshlessFEM.hh"

// Element node ordering:
// 3         2
//  +-------+
//  |       |
//  |       |
//  |       |
//  +-------+
// 0         1

template<typename Model>
class MeshlessFEM<Model>::PerElementStiffnessDensity
{
public:
    typedef Eigen::Matrix<Real, 8, 8> value_type;
    // D: (d00, d01, d10, d11, d22)
    PerElementStiffnessDensity(const DType &d, const Model &model)
        : m_model(model), m_d(d) { clear(); }

    void clear() { result = value_type::Zero(); }

    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        Real x = ref_sample[0], y = ref_sample[1];

        // The following formulas are automatically generated by
        // Derivations/2DStiffness.mpl
        // .5 scaling for d22 is to account for engineering stress * strain
        // double counting the off-diagonals.
        Real d00 = m_d[0], d01 = m_d[1], d10 = m_d[1], d11 = m_d[2], d22 = .5 * m_d[3];
        Real invW = 1.0 / m_dimensions[0];
        Real invH = 1.0 / m_dimensions[1];

        result(0, 0) += weight * (invW * invW * y * y * d00 - 2 * invW * invW * d00 * y + invW * invW * d00 + invH * invH * d22 - 2 * invH * invH * d22 * x + invH * invH * x * x * d22);
        result(0, 1) += weight * (invW * d01 * invH - invW * d01 * invH * x - invW * d01 * invH * y + invW * y * d01 * invH * x + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(0, 2) += weight * (2 * invW * invW * d00 * y - invW * invW * y * y * d00 - invW * invW * d00 - invH * invH * x * x * d22 + invH * invH * d22 * x);
        result(0, 3) += weight * (-invW * y * d01 * invH * x + invW * d01 * invH * x + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(0, 4) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(0, 5) += weight * (invW * y * d01 * invH * x - invW * d01 * invH * x + invH * x * d22 * invW * y - invW * d22 * invH * y);
        result(0, 6) += weight * (-invW * invW * y * y * d00 + invW * invW * d00 * y + 2 * invH * invH * d22 * x - invH * invH * x * x * d22 - invH * invH * d22);
        result(0, 7) += weight * (invW * d01 * invH * y - invW * d01 * invH - invW * y * d01 * invH * x + invW * d01 * invH * x - invH * x * d22 * invW * y + invW * d22 * invH * y);
        result(1, 0) += weight * (invH * d10 * invW - invH * x * d10 * invW - invH * d10 * invW * y + invH * x * d10 * invW * y + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(1, 1) += weight * (invH * invH * d11 - 2 * invH * invH * d11 * x + invH * invH * x * x * d11 + invW * invW * y * y * d22 - 2 * invW * invW * d22 * y + invW * invW * d22);
        result(1, 2) += weight * (invH * d10 * invW * y - invH * d10 * invW - invH * x * d10 * invW * y + invH * x * d10 * invW - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(1, 3) += weight * (-invH * invH * x * x * d11 + invH * invH * d11 * x + 2 * invW * invW * d22 * y - invW * invW * y * y * d22 - invW * invW * d22);
        result(1, 4) += weight * (invH * x * d10 * invW * y - invH * d10 * invW * y + invH * x * d22 * invW * y - invW * d22 * invH * x);
        result(1, 5) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(1, 6) += weight * (-invH * x * d10 * invW * y + invH * d10 * invW * y + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(1, 7) += weight * (2 * invH * invH * d11 * x - invH * invH * x * x * d11 - invH * invH * d11 - invW * invW * y * y * d22 + invW * invW * d22 * y);
        result(2, 0) += weight * (2 * invW * invW * d00 * y - invW * invW * y * y * d00 - invW * invW * d00 - invH * invH * x * x * d22 + invH * invH * d22 * x);
        result(2, 1) += weight * (invW * d01 * invH * y - invW * d01 * invH - invW * y * d01 * invH * x + invW * d01 * invH * x - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(2, 2) += weight * (invW * invW * y * y * d00 - 2 * invW * invW * d00 * y + invW * invW * d00 + invH * invH * x * x * d22);
        result(2, 3) += weight * (-invW * d01 * invH * x + invW * y * d01 * invH * x - invW * d22 * invH * x + invH * x * d22 * invW * y);
        result(2, 4) += weight * (invW * invW * d00 * y - invW * invW * y * y * d00 - invH * invH * x * x * d22);
        result(2, 5) += weight * (invW * d01 * invH * x - invW * y * d01 * invH * x - invH * x * d22 * invW * y);
        result(2, 6) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(2, 7) += weight * (invW * d01 * invH - invW * d01 * invH * x - invW * d01 * invH * y + invW * y * d01 * invH * x + invH * x * d22 * invW * y);
        result(3, 0) += weight * (-invH * x * d10 * invW * y + invH * x * d10 * invW + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(3, 1) += weight * (-invH * invH * x * x * d11 + invH * invH * d11 * x + 2 * invW * invW * d22 * y - invW * invW * y * y * d22 - invW * invW * d22);
        result(3, 2) += weight * (-invH * x * d10 * invW + invH * x * d10 * invW * y - invW * d22 * invH * x + invH * x * d22 * invW * y);
        result(3, 3) += weight * (invH * invH * x * x * d11 + invW * invW * y * y * d22 - 2 * invW * invW * d22 * y + invW * invW * d22);
        result(3, 4) += weight * (-invH * x * d10 * invW * y + invW * d22 * invH * x - invH * x * d22 * invW * y);
        result(3, 5) += weight * (-invH * invH * x * x * d11 + invW * invW * d22 * y - invW * invW * y * y * d22);
        result(3, 6) += weight * (invH * x * d10 * invW * y + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(3, 7) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(4, 0) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(4, 1) += weight * (invW * y * d01 * invH * x - invW * d01 * invH * y + invH * x * d22 * invW * y - invW * d22 * invH * x);
        result(4, 2) += weight * (invW * invW * d00 * y - invW * invW * y * y * d00 - invH * invH * x * x * d22);
        result(4, 3) += weight * (-invW * y * d01 * invH * x + invW * d22 * invH * x - invH * x * d22 * invW * y);
        result(4, 4) += weight * (invW * invW * y * y * d00 + invH * invH * x * x * d22);
        result(4, 5) += weight * (invW * y * d01 * invH * x + invH * x * d22 * invW * y);
        result(4, 6) += weight * (-invW * invW * y * y * d00 + invH * invH * d22 * x - invH * invH * x * x * d22);
        result(4, 7) += weight * (invW * d01 * invH * y - invW * y * d01 * invH * x - invH * x * d22 * invW * y);
        result(5, 0) += weight * (invH * x * d10 * invW * y - invH * x * d10 * invW + invH * x * d22 * invW * y - invW * d22 * invH * y);
        result(5, 1) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(5, 2) += weight * (invH * x * d10 * invW - invH * x * d10 * invW * y - invH * x * d22 * invW * y);
        result(5, 3) += weight * (-invH * invH * x * x * d11 + invW * invW * d22 * y - invW * invW * y * y * d22);
        result(5, 4) += weight * (invH * x * d10 * invW * y + invH * x * d22 * invW * y);
        result(5, 5) += weight * (invH * invH * x * x * d11 + invW * invW * y * y * d22);
        result(5, 6) += weight * (-invH * x * d10 * invW * y + invW * d22 * invH * y - invH * x * d22 * invW * y);
        result(5, 7) += weight * (invH * invH * d11 * x - invH * invH * x * x * d11 - invW * invW * y * y * d22);
        result(6, 0) += weight * (-invW * invW * y * y * d00 + invW * invW * d00 * y + 2 * invH * invH * d22 * x - invH * invH * x * x * d22 - invH * invH * d22);
        result(6, 1) += weight * (-invW * y * d01 * invH * x + invW * d01 * invH * y + invW * d22 * invH * y - invW * d22 * invH - invH * x * d22 * invW * y + invW * d22 * invH * x);
        result(6, 2) += weight * (-invW * invW * d00 * y + invW * invW * y * y * d00 - invH * invH * d22 * x + invH * invH * x * x * d22);
        result(6, 3) += weight * (invW * y * d01 * invH * x + invW * d22 * invH - invW * d22 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(6, 4) += weight * (-invW * invW * y * y * d00 + invH * invH * d22 * x - invH * invH * x * x * d22);
        result(6, 5) += weight * (-invW * y * d01 * invH * x + invW * d22 * invH * y - invH * x * d22 * invW * y);
        result(6, 6) += weight * (invW * invW * y * y * d00 + invH * invH * d22 - 2 * invH * invH * d22 * x + invH * invH * x * x * d22);
        result(6, 7) += weight * (-invW * d01 * invH * y + invW * y * d01 * invH * x - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(7, 0) += weight * (invH * d10 * invW * y - invH * d10 * invW - invH * x * d10 * invW * y + invH * x * d10 * invW - invH * x * d22 * invW * y + invW * d22 * invH * y);
        result(7, 1) += weight * (2 * invH * invH * d11 * x - invH * invH * x * x * d11 - invH * invH * d11 - invW * invW * y * y * d22 + invW * invW * d22 * y);
        result(7, 2) += weight * (invH * d10 * invW - invH * x * d10 * invW - invH * d10 * invW * y + invH * x * d10 * invW * y + invH * x * d22 * invW * y);
        result(7, 3) += weight * (-invH * invH * d11 * x + invH * invH * x * x * d11 - invW * invW * d22 * y + invW * invW * y * y * d22);
        result(7, 4) += weight * (invH * d10 * invW * y - invH * x * d10 * invW * y - invH * x * d22 * invW * y);
        result(7, 5) += weight * (invH * invH * d11 * x - invH * invH * x * x * d11 - invW * invW * y * y * d22);
        result(7, 6) += weight * (-invH * d10 * invW * y + invH * x * d10 * invW * y - invW * d22 * invH * y + invH * x * d22 * invW * y);
        result(7, 7) += weight * (invH * invH * d11 - 2 * invH * invH * d11 * x + invH * invH * x * x * d11 + invW * invW * y * y * d22);
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 8) && (j < 8));
        return result(i, j);
    }

private:
    const Model &m_model;
    const DType &m_d;
    Vector m_dimensions;

    value_type result;
};

template<typename Model>
class MeshlessFEM<Model>::PerElementLaplacianDensity
{
public:
    typedef Eigen::Matrix<Real, 4, 4> value_type;
    PerElementLaplacianDensity(const Model &model)
        : m_model(model) { clear(); }

    void clear() { result = value_type::Zero(); }

    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        Real x = ref_sample[0], y = ref_sample[1];

        // The following formulas are automatically generated by
        // Derivations/2DStiffness.mpl
        // .5 scaling for d22 is to account for engineering stress * strain
        // double counting the off-diagonals.
        Real invW = 1.0 / m_dimensions[0];
        Real invH = 1.0 / m_dimensions[1];

        result(0, 0) += weight * (invW * invW - 2 * invW * invW * y + invW * invW * y * y + invH * invH - 2 * invH * invH * x + invH * invH * x * x);
        result(0, 1) += weight * (2 * invW * invW * y - invW * invW * y * y - invW * invW - invH * invH * x * x + invH * invH * x);
        result(0, 2) += weight * (invW * invW * y * y - invW * invW * y + invH * invH * x * x - invH * invH * x);
        result(0, 3) += weight * (-invW * invW * y * y + invW * invW * y + 2 * invH * invH * x - invH * invH * x * x - invH * invH);
        result(1, 0) += weight * (2 * invW * invW * y - invW * invW * y * y - invW * invW - invH * invH * x * x + invH * invH * x);
        result(1, 1) += weight * (invW * invW - 2 * invW * invW * y + invW * invW * y * y + invH * invH * x * x);
        result(1, 2) += weight * (invW * invW * y - invW * invW * y * y - invH * invH * x * x);
        result(1, 3) += weight * (invW * invW * y * y - invW * invW * y + invH * invH * x * x - invH * invH * x);
        result(2, 0) += weight * (invW * invW * y * y - invW * invW * y + invH * invH * x * x - invH * invH * x);
        result(2, 1) += weight * (invW * invW * y - invW * invW * y * y - invH * invH * x * x);
        result(2, 2) += weight * (invW * invW * y * y + invH * invH * x * x);
        result(2, 3) += weight * (-invW * invW * y * y + invH * invH * x - invH * invH * x * x);
        result(3, 0) += weight * (-invW * invW * y * y + invW * invW * y + 2 * invH * invH * x - invH * invH * x * x - invH * invH);
        result(3, 1) += weight * (invW * invW * y * y - invW * invW * y + invH * invH * x * x - invH * invH * x);
        result(3, 2) += weight * (-invW * invW * y * y + invH * invH * x - invH * invH * x * x);
        result(3, 3) += weight * (invW * invW * y * y + invH * invH - 2 * invH * invH * x + invH * invH * x * x);
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 8) && (j < 8));
        return result(i, j);
    }

private:
    const Model &m_model;
    Vector m_dimensions;

    value_type result;
};

// Average grad phi over the element.
template<typename Model>
class MeshlessFEM<Model>::PerElementGradPhi
{
public:
    // D: (d00, d01, d10, d11, d22)
    PerElementGradPhi(const Model &model)
        : m_model(model) { clear(); }

    void clear() {
        result = GradPhis::Zero();
        m_volume = 0.0;
    }

    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        Real x = ref_sample[0], y = ref_sample[1];
        // phi0 = (1 - x) * (1 - y) => grad phi0 = (invW (y - 1), invH (x - 1))
        // phi1 =      x  * (1 - y) => grad phi1 = (invW (1 - y), invH (   -x))
        // phi2 =      x  *      y  => grad phi2 = (invW (    y), invH (    x))
        // phi3 = (1 - x) *      y  => grad phi3 = (invW (   -y), invH (1 - x))
        Real invW = 1.0 / m_dimensions[0];
        Real invH = 1.0 / m_dimensions[1];
        Real xWeight = weight * invW;
        Real yWeight = weight * invH;

        result(0, 0) += xWeight * (y - 1); result(0, 1) += yWeight * (x - 1);
        result(1, 0) += xWeight * (1 - y); result(1, 1) += yWeight * (   -x);
        result(2, 0) += xWeight * (    y); result(2, 1) += yWeight * (    x);
        result(3, 0) += xWeight * (   -y); result(3, 1) += yWeight * (1 - x);

        // volume = \int 1 * dV
        m_volume += weight;
    }

    void finalize() {
        result /= m_volume;
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 8) && (j < 8));
        return result(i, j);
    }

    Real volume() const {
        return m_volume;
    }

    // Allow type cast to GradPhi
    operator const GradPhis &() const {
        return result;
    }

private:
    const Model &m_model;
    GradPhis result;
    Vector m_dimensions;
    Real m_volume;
};

template<typename Model>
class MeshlessFEM<Model>::PerElementMassMatrixDensity
{
public:
    typedef Eigen::Matrix<Real, 4, 4> value_type;
    PerElementMassMatrixDensity(const Model &model, Real density,
                                   MassMatrixType type = MASS_QUARTER_CELL)
        : m_model(model), m_density(density), m_type(type)
    {
        clear();
    }

    void clear() {
        result = value_type::Zero();
        m_element_mass = 0.0;
    }

    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        m_element_mass += weight * m_density;

        Real x = ref_sample[0], y = ref_sample[1];
        // Node ordering: 3 2
        //                0 1
        Eigen::Matrix<Real, 4, 1> phi;
        phi[0] = (1 - x) * (1 - y);
        phi[1] =      x  * (1 - y);
        phi[2] =      x  *      y ;
        phi[3] = (1 - x) *      y ;

        for (size_t i = 0; i < 4; ++i) {
            for (size_t j = 0; j < 4; ++j) {
                result(i, j) += weight * m_density * phi[i] * phi[j];
            }
        }
    }

    Real operator()(size_t i, size_t j) const {
        Real val = 0.0;
        if (m_type == MASS_LUMPED) {
            if (i == j) {
                // Lumped mass puts sum of entire row on the diagonal
                val = result(i, 0) + result(i, 1) + result(i, 2) + result(i, 3);
            }
        }
        else if (m_type == MASS_QUARTER_CELL) {
            if (i == j) {
                val = .25 * m_element_mass;
            }
        }
        else if (m_type == MASS_FULL) {
            val = result(i, j);
        }
        else {
            assert(false);
        }
        return val;
    }

private:
    const Model &m_model;
    Real m_density;
    MassMatrixType m_type;

    value_type result;
    Real m_element_mass;
};

template<typename Model>
void MeshlessFEM<Model>::m_assembleStiffnessMatrix(size_t &n, IndexVec &mat_i,
        IndexVec &mat_j, ValueVec &mat_v)
{
    // Simple (i, j v) stiffness matrix generation
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();
    n = 2 * elemGrid.numNodes();
    PerElementStiffnessDensity stiff(m_d, model());
    CornerVec cornerIndices;

    mat_i.clear(); mat_j.clear(); mat_v.clear();
    size_t nnz = 64 * elemGrid.numElements();
    mat_i.reserve(nnz); mat_j.reserve(nnz); mat_v.reserve(nnz);

    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        stiff.clear();
        BBox_t b = elemGrid.elementBoundingBox(e);
        stiff.setDimensions(b.dimensions());
        q.integrate(stiff, b);
        elemGrid.elementCorners(e, cornerIndices);
        for (size_t i = 0; i < 4; ++i) {
            size_t vi = cornerIndices[i];
            for (size_t j = 0; j < 4; ++j) {
                size_t vj = cornerIndices[j];
                // xx
                mat_i.push_back(2 * vi);
                mat_j.push_back(2 * vj);
                mat_v.push_back(stiff(2 * i, 2 * j));

                // xy
                mat_i.push_back(2 * vi);
                mat_j.push_back(2 * vj + 1);
                mat_v.push_back(stiff(2 * i, 2 * j + 1));

                // yy
                mat_i.push_back(2 * vi + 1);
                mat_j.push_back(2 * vj + 1);
                mat_v.push_back(stiff(2 * i + 1, 2 * j + 1));

                // yx
                mat_i.push_back(2 * vi + 1);
                mat_j.push_back(2 * vj);
                mat_v.push_back(stiff(2 * i + 1, 2 * j));
            }
        }
    }
}

template<typename Model>
void MeshlessFEM<Model>::m_assembleLaplacianMatrix(size_t &n, IndexVec &mat_i,
        IndexVec &mat_j, ValueVec &mat_v)
{
    // Simple (i, j v) laplacian matrix generation
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();
    n = elemGrid.numNodes();
    PerElementLaplacianDensity lap(model());
    CornerVec cornerIndices;

    mat_i.clear(); mat_j.clear(); mat_v.clear();
    size_t nnz = 16 * elemGrid.numElements();
    mat_i.reserve(nnz); mat_j.reserve(nnz); mat_v.reserve(nnz);

    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        lap.clear();
        BBox_t b = elemGrid.elementBoundingBox(e);
        lap.setDimensions(b.dimensions());
        q.integrate(lap, b);
        elemGrid.elementCorners(e, cornerIndices);
        for (size_t i = 0; i < 4; ++i) {
            size_t vi = cornerIndices[i];
            for (size_t j = 0; j < 4; ++j) {
                size_t vj = cornerIndices[j];
                mat_i.push_back(vi);
                mat_j.push_back(vj);
                mat_v.push_back(lap(i, j));
            }
        }
    }
}


// Compute the quantities needed to evaluate strain/stress/energy from displacement.
template<typename Model>
void MeshlessFEM<Model>::m_computePerElementDisplacementStrainMap()
{
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();
    PerElementGradPhi gradPhi(model());

    size_t numElements = elemGrid.numElements();
    if (m_elementData.size() != numElements) {
        m_elementData.resize(numElements);
    }
    for (size_t e = 0; e < numElements; ++e) {
        gradPhi.clear();
        BBox_t b = elemGrid.elementBoundingBox(e);
        gradPhi.setDimensions(b.dimensions());
        q.integrate(gradPhi, b);
        gradPhi.finalize();
        m_elementData[e].setGradPhis(gradPhi);
        m_elementData[e].setVolume(gradPhi.volume());
    }

    m_displacementStrainCached = true;
}

template<typename Model>
typename MeshlessFEM<Model>::SMField
MeshlessFEM<Model>::elementStressTensors(const VField &displacement)
{
    if (!m_displacementStrainCached)
        m_computePerElementDisplacementStrainMap();
    size_t numElements = elementGrid().numElements();
    assert(m_elementData.size() == numElements);

    SMField stressTensorField(numElements);

    const ElementGrid2D<Model> &elemGrid = elementGrid();
    for (size_t e = 0; e < numElements; ++e) {
        CornerVec cornerIndices;
        elemGrid.elementCorners(e, cornerIndices);
        typename SMField::SymmetricMatrix tensor = stressTensorField(e);
        m_elementData[e].displacementToStress(displacement, cornerIndices, m_d,
                                              tensor);
    }

    return stressTensorField;
}

template<typename Model>
typename MeshlessFEM<Model>::SField
MeshlessFEM<Model>::computeStressTensorNorms(const SMField &stressField)
{
    size_t numMats = stressField.domainSize();
    VField eigenvalues = m_solver->symm2x2Eigenvalues(stressField);
    assert(eigenvalues.domainSize() == numMats);
    SField result(numMats);

    for (size_t i = 0; i < numMats; ++i)
        result[i] = std::max(fabs(eigenvalues(i)[0]), fabs(eigenvalues(i)[1]));

    return result;
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse mass matrix matrix for modal analysis.
//  @param[out]  m, n           Number of matrix rows, columns
//  @param[out]  mat_i, mat_j,  row indices, column indices, and values
//               mat_v Entry 
//  @param[in]   forLaplacian   whether the mass matrix is for the laplacian
//                              modal analysis (defaults to false)
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleMassMatrix(size_t &n, IndexVec &mat_i,
        IndexVec &mat_j, ValueVec &mat_v, bool forLaplacian)
{
    // Simple (i, j v) mass matrix generation
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    const Quadrature2D &q = quadrature();

    if (forLaplacian)
        n = elemGrid.numNodes();
    else
        n = 2 * elemGrid.numNodes();

    PerElementMassMatrixDensity lmass(model(), m_density, m_massMatrixType);
    CornerVec cornerIndices;

    mat_i.clear(); mat_j.clear(); mat_v.clear();

    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        lmass.clear();
        q.integrate(lmass, elemGrid.elementBoundingBox(e));
        elemGrid.elementCorners(e, cornerIndices);
        for (size_t i = 0; i < 4; ++i) {
            size_t vi = cornerIndices[i];
            for (size_t j = 0; j < 4; ++j) {
                size_t vj = cornerIndices[j];
                Real val = lmass(i, j);
                if (val > 1e-12) {
                    if (forLaplacian) {
                        mat_i.push_back(vi);
                        mat_j.push_back(vj);
                        mat_v.push_back(val);
                    }
                    else {
                        mat_i.push_back(2 * vi);
                        mat_j.push_back(2 * vj);
                        mat_v.push_back(val);

                        mat_i.push_back(2 * vi + 1);
                        mat_j.push_back(2 * vj + 1);
                        mat_v.push_back(val);
                    }
                }
            }
        }
    }
}

template<typename Model>
class MeshlessFEM<Model>::BoundaryFunctionLoad
{
public:
    typedef Eigen::Matrix<Real, 4, 1> value_type;

    BoundaryFunctionLoad(const BoundaryFunction &psi)
        : m_psi(psi) {
        clear();
    }

    void clear() {
        m_load = value_type::Zero();
    }

    void accumulate(const Vector &sample,
                    const Vector &ref_sample, Real weight) {
        bool inSupport = m_psi.isInSupport(sample);
        if (inSupport) {
            Real psi = m_psi(sample);

            // Compute unscaled load (integral against each grid node function.)
            value_type phi;
            Real x = ref_sample[0], y = ref_sample[1];
            phi[0] = (1 - x) * (1 - y);
            phi[1] =      x  * (1 - y);
            phi[2] =      x  *      y ;
            phi[3] = (1 - x) *      y ;

            m_load += (weight * psi) * phi;
        }
    }

    Real operator()(size_t i) const {
        assert(i < 4);
        return m_load(i);
    }

private:
    value_type m_load;
    const BoundaryFunction &m_psi;
};

template<typename Model>
void MeshlessFEM<Model>::buildBoundaryFunctions()
{
    m_boundaryFunctions.clear();
    m_boundaryFunctions.reserve(m_boundaryPoints.size());
    Vector cellSize = m_elementGrid->cellSize();
    Real h = std::max(cellSize[0], cellSize[1]);

    for (size_t i = 0; i < m_boundaryPoints.size(); ++i) {
        m_boundaryFunctions.push_back(
                BoundaryFunction(m_boundaryPoints[i].p, h));
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Construct the surface force -> surface force load matrix.
//  This matrix maps a (B * dim) vector of flattened (x1, y1, ..) per-boundary
//  point force densities to a (N * dim) vector of flattened (x1, y1, ..)
//  per-node loads.
//  Each pressure variable p_i is blurred into a volume force by boundary
//  function psi_i. Psi_i is (effectively) normalized so that the integral of
//  the point's force over the surface is n_i * a_i * p_i (n_i normal, a_i area)
//  Note: Because of partition of unity, this condition means the matrix columns
//        should sum to 1.
//  @param[out]  m, n       Number of matrix rows, columns
//  @param[out]  i, j, v    Entry row indices, column indices, and values
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleLoadMatrix(size_t &m, size_t &n, IndexVec &i,
                                              IndexVec &j, ValueVec &v)
{
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    m = elemGrid.numNodes();
    n = numBoundaryPoints();

    i.clear(), j.clear(), v.clear();

    std::vector<size_t> support_elems;
    CornerVec cornerIndices;
    const Quadrature2D &q = quadrature();

    // Fill out one column of the matrix at a time.
    for (size_t f = 0; f < n; ++f) {
        const BoundaryFunction &psi = boundaryFunction(f);
        BoundaryFunctionLoad load(psi);

        elemGrid.elementsAroundPoint(psi.center(), psi.supportRadius(),
                                     support_elems);
        Real colSum = 0;
        // Mark the start of the values in this column so we can go back and
        // normalize them.
        size_t colValuesOffset = v.size();
        for (size_t e = 0; e < support_elems.size(); ++e) {
            load.clear();
            q.integrate(load, elemGrid.elementBoundingBox(support_elems[e]));
            elemGrid.elementCorners(support_elems[e], cornerIndices);
            for (size_t c = 0; c < 4; ++c) {
                Real ld = load(c);
                if (std::abs(ld) > 1e-8) {
                    i.push_back(cornerIndices[c]);
                    j.push_back(f);
                    v.push_back(ld);
                    colSum += ld;
                }
            }
        }

        // Normalize so the column sums to 1
        for (size_t vo = colValuesOffset; vo < v.size(); ++vo)
            v[vo] /= colSum;
    }

    // Duplicate matrix for each dimension
    m *= 2, n *= 2;
    size_t singleNZ = i.size();
    i.reserve(singleNZ * 2), j.reserve(singleNZ * 2), v.reserve(singleNZ * 2);
    for (size_t k = 0; k < singleNZ; ++k) {
        size_t row = i[k], col = j[k];
        i[k] = 2 * row;
        j[k] = 2 * col;
        i.push_back(2 * row + 1);
        j.push_back(2 * col + 1);
        v.push_back(v[k]);
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix whose rows span the space of rigid transformation
//  displacements. These are the translations and infinitesimal rotations.
//  In 2D, there are three.
//  The generated matrix also can compute total force and net torque of a
//  (volume) force distribution, so it is useful in formulating the pressure
//  equality constraints for structural optimization.
//  @param[out]  m, n       Number of matrix rows, columns
//  @param[out]  i, j, v    Entry row indices, column indices, and values
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleRigidModeMatrix(size_t &m, size_t &n,
                            IndexVec &i, IndexVec &j, ValueVec &v)
{
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    m = 3;
    n = 2 * elemGrid.numNodes();
    size_t nNodes = elemGrid.numNodes();
    
    i.clear(), j.clear(), v.clear();
    size_t predictedNNZ = 4 * nNodes;
    i.reserve(predictedNNZ), j.reserve(predictedNNZ), v.reserve(predictedNNZ);

    // Translations
    for (size_t k = 0; k < nNodes; ++k) {
        i.push_back(0);
        j.push_back(2 * k);
        v.push_back(1.0);

        i.push_back(1);
        j.push_back(2 * k + 1);
        v.push_back(1.0);
    }

    // Infinitesimal rotations
    for (size_t k = 0; k < nNodes; ++k) {
        Vector p = elemGrid.nodePosition(k);
        // x offset: -y
        i.push_back(2);
        j.push_back(2 * k);
        v.push_back(-p[1]);

        // y offset: x
        i.push_back(2);
        j.push_back(2 * k + 1);
        v.push_back(p[0]);
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix mapping boundary pressures to boundary force
//  magnitudes (i.e. weighting the pressures by the area over which they act).
//  @param[out]  m, n       Number of matrix rows, columns
//  @param[out]  i, j, v    Entry row indices, column indices, and values
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleAMatrix(size_t &m, size_t &n,
                            IndexVec &i, IndexVec &j, ValueVec &v)
{
    m = m_boundaryPoints.size();
    n = m_boundaryPoints.size();

    i.clear(), j.clear(), v.clear();
    size_t nnz = m_boundaryPoints.size();
    i.reserve(nnz), j.reserve(nnz), v.reserve(nnz);

    for (size_t k = 0; k < m_boundaryPoints.size(); ++k) {
        i.push_back(k);
        j.push_back(k);
        v.push_back(m_boundaryPoints[k].a);
    }
}


////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix mapping boundary force magnitudes to a flattened
//  vector of forces at those boundary points.
//  @param[out]  m, n       Number of matrix rows, columns
//  @param[out]  i, j, v    Entry row indices, column indices, and values
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleNMatrix(size_t &m, size_t &n,
                            IndexVec &i, IndexVec &j, ValueVec &v)
{
    m = 2 * m_boundaryPoints.size();
    n = m_boundaryPoints.size();

    i.clear(), j.clear(), v.clear();
    size_t nnz = 2 * m_boundaryPoints.size();
    i.reserve(nnz), j.reserve(nnz), v.reserve(nnz);

    for (size_t k = 0; k < m_boundaryPoints.size(); ++k) {
        // Forces are applied in the negative normal direction
        Vector f = -m_boundaryPoints[k].n;

        // x component
        i.push_back(2 * k);
        j.push_back(k);
        v.push_back(f[0]);

        // y component
        i.push_back(2 * k + 1);
        j.push_back(k);
        v.push_back(f[1]);
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix mapping a flattened per-node displacement vector to a 
//  flattened per-element strain tensor.
//  @param[out]  m, n       Number of matrix rows, columns
//  @param[out]  i, j, v    Entry row indices, column indices, and values
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleBMatrix(size_t &m, size_t &n,
                            IndexVec &i, IndexVec &j, ValueVec &v)
{
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    m = 3 * elemGrid.numElements();
    n = 2 * elemGrid.numNodes();

    if (!m_displacementStrainCached)
        m_computePerElementDisplacementStrainMap();

    size_t nnz = 16 * elemGrid.numElements();
    i.clear(), j.clear(), v.clear();
    i.reserve(nnz), j.reserve(nnz), v.reserve(nnz);

    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        CornerVec cornerIndices;
        elemGrid.elementCorners(e, cornerIndices);
        for (size_t c = 0; c < 4; ++c) {
            size_t vtx = cornerIndices[c];
            // e_xx
            i.push_back(3 * e + 0);
            j.push_back(2 * vtx + 0);
            v.push_back(m_elementData[e].gradPhi(c, 0));

            // e_yy
            i.push_back(3 * e + 1);
            j.push_back(2 * vtx + 1);
            v.push_back(m_elementData[e].gradPhi(c, 1));

            // e_xy (1)
            i.push_back(3 * e + 2);
            j.push_back(2 * vtx + 0);
            v.push_back(.5 * m_elementData[e].gradPhi(c, 1));

            // e_xy (2)
            i.push_back(3 * e + 2);
            j.push_back(2 * vtx + 1);
            v.push_back(.5 * m_elementData[e].gradPhi(c, 0));
        }
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix mapping a flattened per-element strain tensor to
//  a flattened per-element stress tensor
//  @param[out]  m, n       Number of matrix rows, columns
//  @param[out]  i, j, v    Entry row indices, column indices, and values
*///////////////////////////////////////////////////////////////////////////////
template<typename Model>
void MeshlessFEM<Model>::m_assembleVDMatrix(size_t &m, size_t &n,
                            IndexVec &i, IndexVec &j, ValueVec &v)
{
    const ElementGrid2D<Model> &elemGrid = elementGrid();
    m = 3 * elemGrid.numElements();
    n = 3 * elemGrid.numElements();

    size_t nnz = 5 * elemGrid.numElements();
    i.clear(), j.clear(), v.clear();
    i.reserve(nnz), j.reserve(nnz), v.reserve(nnz);

    // The per-element matrix is given by:
    // D = d00 d01   0 =  d0 d1   0 
    //     d10 d11   0    d1 d2   0
    //     0   0   d22    0   0   d3
    for (size_t e = 0; e < elemGrid.numElements(); ++e) {
        Real vol = m_elementData[e].volume();
        i.push_back(3 * e + 0);
        j.push_back(3 * e + 0);
        v.push_back(vol * m_d[0]);

        i.push_back(3 * e + 0);
        j.push_back(3 * e + 1);
        v.push_back(vol * m_d[1]);

        i.push_back(3 * e + 1);
        j.push_back(3 * e + 0);
        v.push_back(vol * m_d[1]);

        i.push_back(3 * e + 1);
        j.push_back(3 * e + 1);
        v.push_back(vol * m_d[2]);

        i.push_back(3 * e + 2);
        j.push_back(3 * e + 2);
        v.push_back(vol * m_d[3]);
    }
}

template<typename Model>
bool MeshlessFEM<Model>::modalAnalysis()
{
    bool success;

    if (m_laplacianModes) {
        // Use laplacian modes
        std::vector<size_t> L_i, L_j;
        std::vector<Real> L_v;
        size_t L_n;
        m_assembleLaplacianMatrix(L_n, L_i, L_j, L_v);

        std::vector<size_t> M_i, M_j;
        std::vector<Real> M_v;
        size_t M_n;
        m_assembleMassMatrix(M_n, M_i, M_j, M_v, true);

        size_t numModes = std::min((size_t) m_numRequestedModes, L_n);

        std::vector<SField> lapModes;
        std::vector<Real>   lapEigs;
        success = m_solver->GeneralizedEigenvalueProblem(numModes / 2,
                                              L_n, L_i, L_j, L_v,
                                              M_n, M_i, M_j, M_v,
                                              lapModes, lapEigs);
        assert(numModes / 2 == lapModes.size());

        m_modes.clear(), m_eigenvalues.clear();
        m_modes.reserve(lapModes.size() * 2);
        m_eigenvalues.reserve(lapEigs.size() * 2);
        VField expanded(L_n);
        for (size_t m = 0; m < lapModes.size(); ++m) {
            const SField &mode = lapModes[m];
            // x mode
            expanded.clear();
            for (size_t i = 0; i < L_n; ++i)
                expanded(i)[0] = mode[i];
            m_modes.push_back(expanded);
            m_eigenvalues.push_back(lapEigs[m]);

            // y mode
            expanded.clear();
            for (size_t i = 0; i < L_n; ++i)
                expanded(i)[1] = mode[i];
            m_modes.push_back(expanded);
            m_eigenvalues.push_back(lapEigs[m]);
        }

        numModes = m_modes.size();

        // Normalize so all (nonzero) modes inject unit energy
        for (size_t i = numRigidModes(); i < numModes; ++i) {
            m_modes[i] *= (1.0 / m_computeEnergy(m_modes[i]));
        }
    }
    else {
        // Use stiffness modes
        std::vector<size_t> K_i, K_j;
        std::vector<Real> K_v;
        size_t K_n;
        m_assembleStiffnessMatrix(K_n, K_i, K_j, K_v);

        std::vector<size_t> M_i, M_j;
        std::vector<Real> M_v;
        size_t M_n;
        m_assembleMassMatrix(M_n, M_i, M_j, M_v);

        size_t numModes = std::min((size_t) m_numRequestedModes, K_n);
        std::vector<SField> eigenVectors;
        success = m_solver->GeneralizedEigenvalueProblem(numModes,
                                              K_n, K_i, K_j, K_v,
                                              M_n, M_i, M_j, M_v, eigenVectors,
                                              m_eigenvalues);
        assert(numModes == eigenVectors.size());
        m_modes.clear(); m_modes.reserve(eigenVectors.size());
        for (auto it = eigenVectors.begin(); it != eigenVectors.end(); ++it) {
            // Convert to a vector field
            m_modes.push_back(it->template unflatten<2>());
        }

        // Normalize so all (nonzero) modes inject unit energy
        // Mode energy = 1/2 u^T K u = 1/2 lambda u^T M u := 1
        // ==> u^T M u = 2 / lambda
        // Eigensolver gives us u^T M u = 1, so we must just scale u by
        // sqrt(2 / lambda)
        for (size_t i = 0; i < numModes; ++i) {
            Real lambda = eigenvalue(i);
            if (lambda > (Real) 1e-6)
                m_modes[i] *= sqrt(2.0 / lambda);
        }
    }

    m_modalStressTensors.clear();
    m_modalStressNorms.clear();
    m_weakRegions.clear();
    m_weakRegionStressNorms.clear();

    if (success) {
        size_t numModes = m_modes.size();
        // Compute modal stress tensors.
        m_modalStressTensors.reserve(numModes);
        for (size_t i = 0; i < numModes; ++i)
            m_modalStressTensors.push_back(elementStressTensors(mode(i)));

        // Compute modal stress norms
        for (size_t i = 0; i < numModes; ++i)
            m_modalStressNorms.push_back(
                    computeStressTensorNorms(m_modalStressTensors[i]));
    }

    return success;
}

// Return Values
//  -1: modal analysis failure
//   0: success
//   1: success, and modes were updated
template<typename Model>
int MeshlessFEM<Model>::weakRegionExtraction()
{
    bool recomputedModes = false;
    if (m_modes.size() == 0) {
        if (!modalAnalysis())
            return -1;
        recomputedModes = true;
    }

    m_weakRegions.clear();
    m_weakRegionStressNorms.clear();
    std::vector<Real> weakRegionVolumes;

    const ElementGrid &grid = elementGrid();
    for (size_t m = numRigidModes(); m < m_modes.size(); ++m) {
        // compute the stress cutoff value
        const SField &stressNorms = m_modalStressNorms[m];
        const VField &modalDisp   = m_modes[m];
        assert(stressNorms.size() == grid.numElements());

        std::vector<size_t> sortedElements;
        sortPermutation(stressNorms, sortedElements);

        // Everything above the cutoff percentile is a weak region
        size_t cutoff = m_weaknessCutoff * sortedElements.size();
        std::vector<int> wrIndex(sortedElements.size(), -1);
        for (size_t i = cutoff; i < sortedElements.size(); ++i) {
            // Flag as part of a weak region
            wrIndex[sortedElements[i]] = 0;
        }

        // Extract connected components (BFS-based)
        int tag = 0;
        std::vector<size_t> adj;
        for (size_t i = 0; i < wrIndex.size(); ++i) {
            if (wrIndex[i] != 0) continue;

            ++tag;
            wrIndex[i] = tag;

            std::queue<size_t> bfsQueue;
            // Queue contains elements who have already been tagged, but whose
            // neighbors might not have been.
            // Each element appears at most once in the queue (an old version
            // didn't have this guarantee, and memory blew up!).
            bfsQueue.push(i);
            while (!bfsQueue.empty()) {
                size_t u = bfsQueue.front();
                bfsQueue.pop();
                grid.elementsAdjacentElement(u, adj);
                for (size_t j = 0; j < adj.size(); ++j) {
                    size_t v = adj[j];
                    assert(v < wrIndex.size());
                    if (wrIndex[v] == 0) {
                        wrIndex[v] = tag;
                        bfsQueue.push(v);
                    }
                }
            }
        }

        std::vector<std::vector<size_t> > regions(tag);

        // Extract weak region contents (numbered 1...# regions)
        for (size_t i = 0; i < wrIndex.size(); ++i) {
            assert(wrIndex[i] != 0);
            if (wrIndex[i] > 0) {
                assert(((size_t) wrIndex[i]) <= regions.size());
                regions[wrIndex[i] - 1].push_back(i);
            }
        }

        // Compute energy in each weak region
        std::vector<Real> energies(regions.size(), 0);
        CornerVec cornerIndices;
        for (size_t r = 0; r < regions.size(); ++r) {
            energies[r] = m_computeEnergy(modalDisp, regions[r]);
        }

        // Sort weak regions by energy
        std::vector<size_t> sortedRegions;
        sortPermutation(energies, sortedRegions, true);

        // Take the top m_weakRegionsPerMode
        size_t numWR = std::min((size_t) m_weakRegionsPerMode,
                                         sortedRegions.size());
        for (size_t i = 0; i < numWR; ++i) {
            m_weakRegions.push_back(regions[sortedRegions[i]]);
            m_weakRegionStressNorms.push_back(SField(stressNorms.size()));
            m_weakRegionStressNorms.back().clear();
            size_t wrSize = m_weakRegions.back().size();
            for (size_t j = 0; j < wrSize; ++j) {
                size_t ei = m_weakRegions.back()[j];
                m_weakRegionStressNorms.back()[ei] = stressNorms[ei];
            }
        }
    }

    // weakRegionVolumes.assign(m_weakRegions.size(), 0.0);
    // for (size_t r = 0; r < m_weakRegions.size(); ++r) {
    //     const Region &region = m_weakRegions[r];
    //     for (size_t i = 0; i < region.size(); ++i) {
    //         weakRegionVolumes[i] += m_elementData[region[i]].volume();
    //     }
    // }

    return recomputedModes ? 1 : 0;
}

template<typename Model>
bool MeshlessFEM<Model>::weaknessAnalysis(Real &weaknessCriterion,
        const char *cwPath, const char *cwPercentilePath) {
    if (combinedWeaknessIsCached()) {
        weaknessCriterion = m_weaknessCriterion;
        return true;
    }

    int ret = weakRegionExtraction();
    if (ret < 0)
        return false;

    MatlabSolver<Real> *solver = dynamic_cast<MatlabSolver<Real> *>(m_solver);
    assert(solver != NULL);

    size_t Fm, Fn, Kn, Rm, Rn, Nm, Nn, Am, An, Bm, Bn, VDm, VDn;
    IndexVec Fi, Fj, Ki, Kj, Ri, Rj, Ni, Nj, Ai, Aj, Bi, Bj, VDi, VDj;
    ValueVec Fv, Kv, Rv, Nv, Av, Bv, VDv;
    m_assembleLoadMatrix(Fm, Fn, Fi, Fj, Fv);
    m_assembleStiffnessMatrix(Kn, Ki, Kj, Kv);
    m_assembleRigidModeMatrix(Rm, Rn, Ri, Rj, Rv);
    m_assembleNMatrix(Nm, Nn, Ni, Nj, Nv);
    m_assembleAMatrix(Am, An, Ai, Aj, Av);
    m_assembleBMatrix(Bm, Bn, Bi, Bj, Bv);
    m_assembleVDMatrix(VDm, VDn, VDi, VDj, VDv);
    solver->setSparseMatrix("F", Fm, Fn, Fi, Fj, Fv);
    solver->setSparseMatrix("K", Kn, Kn, Ki, Kj, Kv);
    solver->setSparseMatrix("R", Rm, Rn, Ri, Rj, Rv);
    solver->setSparseMatrix("N", Nm, Nn, Ni, Nj, Nv);
    solver->setSparseMatrix("A", Am, An, Ai, Aj, Av);
    solver->setSparseMatrix("B", Bm, Bn, Bi, Bj, Bv);
    solver->setSparseMatrix("VD", VDm, VDn, VDi, VDj, VDv);

    solver->eval("C_s = [K, R'; R, zeros(3)];");
    solver->eval("S = [speye(size(K, 1)); zeros(3, size(K, 1))];");

    char cmd[128];
    snprintf(cmd, 128, "F_tot = %lf; p_max = %lf;",
            (double) m_totalForceBound, (double) m_pointwisePressureBound);
    solver->eval(cmd);

    solver->eval("psize=size(A, 2); linprog_A = [-speye(psize); speye(psize)];");
    solver->eval("linprog_b = [zeros(psize, 1); p_max * ones(psize, 1)];");
    solver->eval("linprog_Aeq = [R * F * N * A; diag(A)'];");
    solver->eval("linprog_beq = [zeros(3, 1); F_tot];");

    const ElementGrid2D<Model> &elemGrid = elementGrid();
    size_t numNodes = elemGrid.numNodes();
    size_t numElems = elemGrid.numElements();

    m_combinedWeakness.resizeDomain(numElems);
    m_combinedWeakness.clear();

    DVector w;
    for (size_t i = 0; i < numWeakRegions(); ++i) {
        m_assembleWVector(w, i);
        solver->setDenseMatrix("w", w.rows(), 1, w.data(), true);

        solver->eval("q = (C_s') \\ (S * B' * VD' * w);");
        solver->eval("f = (S * F * N * A)' * q;");

        // Get optimal pressures
        solver->eval("p = linprog(-f, linprog_A, linprog_b, linprog_Aeq, linprog_beq);");
        m_pressures.resizeDomain(m_boundaryPoints.size());
        solver->getDenseMatrix("p", m_boundaryPoints.size(), 1, m_pressures.data(), true);

        // Get optimal displacements
        solver->eval("u = S' * (C_s \\ (S * F * N * A * p));");

        VField optU(numNodes);
        solver->getDenseMatrix("u", Kn, 1, optU.data().data(), true);
        typedef Eigen::Map<Eigen::Matrix<Real, Eigen::Dynamic,
                                         2, Eigen::RowMajor> > MappedMat;

        SMField stressTensors = elementStressTensors(optU);
        SField  optStress = computeStressTensorNorms(stressTensors);

        m_combinedWeakness.maxRelax(optStress);
    }

    solver->setDenseMatrix("combinedWeakness", m_combinedWeakness.size(),
            1, m_combinedWeakness.data(), true);

    std::vector<size_t> cwSortPerm;
    sortPermutation(m_combinedWeakness, cwSortPerm);
    assert(cwSortPerm.size() == numElems);

    DVector volumes(numElems);
    for (size_t i = 0; i < numElems; ++i)
        volumes[i] = m_elementData[i].volume();

    Real accumVol = 0.0;
    DVector percentile(numElems);
    for (size_t i = 0; i < numElems; ++i) {
        accumVol += volumes[cwSortPerm[i]];
        percentile[cwSortPerm[i]] = accumVol;
    }
    percentile *= (1.0 / accumVol);

    // // Find the highest stress *full* element (stress is averaged over elements,
    // // so partial elements have an unfair advantage in the rankings)
    // Real weaknessCriterion = m_combinedWeakness[cwSortPerm.back()];
    // for (int i = cwSortPerm.size() - 1; i >= 0; --i) {
    //     if (elemGrid.elementIsFull(cwSortPerm[i])) {
    //         weaknessCriterion = m_combinedWeakness[cwSortPerm[i]];
    //         break;
    //     }
    // }

    // Lp norm
    Real p = 20;
    weaknessCriterion = 0.0;
    Real totalVol = 0.0;
    for (size_t i = 0; i < m_combinedWeakness.size(); ++i) {
        weaknessCriterion += pow(m_combinedWeakness[i], p) * volumes[i];
        totalVol += volumes[i];
    }
    weaknessCriterion = pow(weaknessCriterion, 1.0 / p) / totalVol;

    std::cout << "Weakness criterion: " << weaknessCriterion << std::endl;

    m_weaknessCriterion = weaknessCriterion;

    solver->setDenseMatrix("volumes", volumes.rows(),
            1, volumes.data(), true);
    solver->setDenseMatrix("cwPercentiles", percentile.rows(),
            1, percentile.data(), true);

    if (cwPath) {
        std::ofstream cwFile(cwPath);
        if (!cwFile.is_open()) {
            std::cout << "Failed to open output file '"
                      << cwPath << '\'' << std::endl;
        }
        else{
            cwFile << m_combinedWeakness;
        }
    }
    if (cwPercentilePath) {
        std::ofstream cwpFile(cwPercentilePath);
        if (!cwpFile.is_open()) {
            std::cout << "Failed to open output file '"
                      << cwPercentilePath << '\'' << std::endl;
        }
        else{
            cwpFile << percentile;
        }
    }
    

    return true;
}

template<typename Model>
void MeshlessFEM<Model>::m_assembleWVector(DVector &w, size_t regionIdx) const {
    size_t numElems = elementGrid().numElements();
    w.resize(3 * numElems, Eigen::NoChange);
    if (regionIdx < m_weakRegions.size()) {
        const SField &weights = m_weakRegionStressNorms[regionIdx];
        assert(weights.size() == numElems);
        for (size_t i = 0; i < numElems; ++i) {
            Real weight = weights[i];
            w[3 * i + 0] = weight;
            w[3 * i + 1] = weight;
            w[3 * i + 2] = 0;
        }
    }
    else {
        for (size_t i = 0; i < numElems; ++i) {
            // Compute total trace everywhere
            w[3 * i + 0] = 1;
            w[3 * i + 1] = 1;
            w[3 * i + 2] = 0;
        }
    }
}

template<typename Model>
void MeshlessFEM<Model>::m_invalidateCache() {
    m_stiffnessCached = false;
    m_massCached = false;
    m_modes.clear();
    m_displacementStrainCached = false;
    m_elementData.clear();

    if (m_useMarchingSquaresBoundary) {
        m_boundaryPoints.clear();

        std::vector<Polygon_t> polygons;
        MarchingSquaresGrid ms(elementGrid().interiorRows(),
                               elementGrid().interiorCols());
        ms.extractBoundaryPolygons(m_model, polygons);
        for (size_t p = 0; p < polygons.size(); ++p) {
            const std::vector<Vector> &points = polygons[p].points;
            m_boundaryPoints.reserve(m_boundaryPoints.size() +
                                     points.size());
            Vector prevSegment = points[0] - points.back();
            for (size_t i = 0; i < points.size(); ++i) {
                Vector nextSegment =
                        points[(i + 1) % points.size()] - points[i];
                Real a = .5 * (prevSegment.norm() + nextSegment.norm());
                // Normals: rotate tangent clockwise 90 degrees
                // (y = -x, x = y)
                Vector n = Vector(prevSegment[1], -prevSegment[0]) +
                           Vector(nextSegment[1], -nextSegment[0]);
                n /= n.norm();
                m_boundaryPoints.push_back(_BoundaryPoint(points[i], n, a));

                prevSegment = nextSegment;
            }
        }
    }
    else {
        m_boundaryPoints = m_model.boundaryPoints(m_boundaryPointSpacing);
    }
    m_boundaryFunctions.clear();
    m_pressures.resizeDomain(m_boundaryPoints.size());
    m_nodeFixed.assign(elementGrid().numNodes(), false);

    m_weakRegions.clear();
    m_weakRegionStressNorms.clear();

    m_combinedWeakness.resizeDomain(0);
}

////////////////////////////////////////////////////////////////////////////////
// Template instantiations
////////////////////////////////////////////////////////////////////////////////
#include "GlobalTypes.hh"
template class MeshlessFEM<CSGTree_t>;
