////////////////////////////////////////////////////////////////////////////////
// MeshlessFEM3D.cc
////////////////////////////////////////////////////////////////////////////////
/*! @file
//		Implements a 3D mesh-free finite element discretization of linear
//		elasticity." Mesh-free" means the surface/volume representation only
//      needs to support point inclusion tests.
*/ 
//  Author:  Julian Panetta (jpanetta), julian.panetta@gmail.com
//  Company:  New York University
//  Created:  04/30/2014 00:07:12
////////////////////////////////////////////////////////////////////////////////
#define DIM 3
#include "MeshlessFEM3D.hh"
#include <cassert>
#include <iostream>
#include "utils.hh"

// Integrand for the per-element stiffness matrix integral for an orthotropic
// material. As an optimization for symmetry, only the upper triangle terms are
// computed, and accesses to the lower triangle are redirected to the upper
// triangle.
template<typename _Model>
class MeshlessFEM3D<_Model>::PerElementOrthotropicStiffnessDensity
{
public:
    typedef Eigen::Matrix<Real, 24, 24> value_type;

    // D: (d00, d01, d10, d11, d22)
    PerElementOrthotropicStiffnessDensity(const DType &d, const Model &model)
        : m_model(model), m_d(d) { clear(); setDimensions(Vector::Zero()); }

    void clear() { result = value_type::Zero(); }

    // Set element size
    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
        m_fullCellIntegralCached = false;
    }

    // Called once per quadrature sample to perform the integration.
    // @param[in]  sample     quadrature sample point in element
    // @param[in]  ref_sample sample coordinates in reference cube ([0, 1]^3)
    // @param[in]  weight     "dV" for the sample--includes jacobian determinant
    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        Real x = ref_sample[0], y = ref_sample[1], z = ref_sample[2];

        // The following formulas are automatically generated by
        // Derivations/3DStiffness.nb

        // Unpack elasticity tensor
        // .5 scaling for off-diagonals  is to account for engineering stress :
        // engineering strain double-counting the off-diagonals.
        Real d00 = m_d[0], d01 = 0.5 * m_d[1], d02 = 0.5 * m_d[ 2], // d03 = 0.5 * m_d[ 3], d04 = .5 * m_d[ 4], d05 = .5 * m_d[ 5],
                           d11 =       m_d[6], d12 = 0.5 * m_d[ 7], // d13 = 0.5 * m_d[ 8], d14 = .5 * m_d[ 9], d15 = .5 * m_d[10],
                                               d22 =       m_d[11], // d23 = 0.5 * m_d[12], d24 = .5 * m_d[13], d25 = .5 * m_d[14],
                                                                    d33 =       m_d[15], // d34 = .5 * m_d[16], d35 = .5 * m_d[17],
                                                                                         d44 =      m_d[18], // d45 = .5 * m_d[19],
                                                                                                             d55 =      m_d[20];

        // Entries in B
        Real dxp0 = ((y - 1) * (1 - z))/m_dimensions[0];
        Real dxp1 = ((1 - y) * (1 - z))/m_dimensions[0];
        Real dxp2 =       (y * (1 - z))/m_dimensions[0];
        Real dxp3 =       (y * (z - 1))/m_dimensions[0];
        Real dxp4 =       ((y - 1) * z)/m_dimensions[0];
        Real dxp5 =       ((1 - y) * z)/m_dimensions[0];
        Real dxp6 =             (y * z)/m_dimensions[0];
        Real dxp7 =            -(y * z)/m_dimensions[0];
        Real dyp0 = ((x - 1) * (1 - z))/m_dimensions[1];
        Real dyp1 =       (x * (z - 1))/m_dimensions[1];
        Real dyp2 =       (x * (1 - z))/m_dimensions[1];
        Real dyp3 = ((1 - x) * (1 - z))/m_dimensions[1];
        Real dyp4 =       ((x - 1) * z)/m_dimensions[1];
        Real dyp5 =            -(x * z)/m_dimensions[1];
        Real dyp6 =             (x * z)/m_dimensions[1];
        Real dyp7 =       ((1 - x) * z)/m_dimensions[1];
        Real dzp0 = ((x - 1) * (1 - y))/m_dimensions[2];
        Real dzp1 =       (x * (y - 1))/m_dimensions[2];
        Real dzp2 =            -(x * y)/m_dimensions[2];
        Real dzp3 =       ((x - 1) * y)/m_dimensions[2];
        Real dzp4 = ((1 - x) * (1 - y))/m_dimensions[2];
        Real dzp5 =       (x * (1 - y))/m_dimensions[2];
        Real dzp6 =             (x * y)/m_dimensions[2];
        Real dzp7 =       ((1 - x) * y)/m_dimensions[2];

        result(0, 0) += weight * (d00*(dxp0*dxp0) + d55*(dyp0*dyp0) + d44*(dzp0*dzp0));
        result(0, 1) += weight * ((d01 + d55)*dxp0*dyp0);
        result(0, 2) += weight * ((d02 + d44)*dxp0*dzp0);
        result(0, 3) += weight * (d00*dxp0*dxp1 + d55*dyp0*dyp1 + d44*dzp0*dzp1);
        result(0, 4) += weight * (d55*dxp1*dyp0 + d01*dxp0*dyp1);
        result(0, 5) += weight * (d44*dxp1*dzp0 + d02*dxp0*dzp1);
        result(0, 6) += weight * (d00*dxp0*dxp2 + d55*dyp0*dyp2 + d44*dzp0*dzp2);
        result(0, 7) += weight * (d55*dxp2*dyp0 + d01*dxp0*dyp2);
        result(0, 8) += weight * (d44*dxp2*dzp0 + d02*dxp0*dzp2);
        result(0, 9) += weight * (d00*dxp0*dxp3 + d55*dyp0*dyp3 + d44*dzp0*dzp3);
        result(0, 10) += weight * (d55*dxp3*dyp0 + d01*dxp0*dyp3);
        result(0, 11) += weight * (d44*dxp3*dzp0 + d02*dxp0*dzp3);
        result(0, 12) += weight * (d00*dxp0*dxp4 + d55*dyp0*dyp4 + d44*dzp0*dzp4);
        result(0, 13) += weight * (d55*dxp4*dyp0 + d01*dxp0*dyp4);
        result(0, 14) += weight * (d44*dxp4*dzp0 + d02*dxp0*dzp4);
        result(0, 15) += weight * (d00*dxp0*dxp5 + d55*dyp0*dyp5 + d44*dzp0*dzp5);
        result(0, 16) += weight * (d55*dxp5*dyp0 + d01*dxp0*dyp5);
        result(0, 17) += weight * (d44*dxp5*dzp0 + d02*dxp0*dzp5);
        result(0, 18) += weight * (d00*dxp0*dxp6 + d55*dyp0*dyp6 + d44*dzp0*dzp6);
        result(0, 19) += weight * (d55*dxp6*dyp0 + d01*dxp0*dyp6);
        result(0, 20) += weight * (d44*dxp6*dzp0 + d02*dxp0*dzp6);
        result(0, 21) += weight * (d00*dxp0*dxp7 + d55*dyp0*dyp7 + d44*dzp0*dzp7);
        result(0, 22) += weight * (d55*dxp7*dyp0 + d01*dxp0*dyp7);
        result(0, 23) += weight * (d44*dxp7*dzp0 + d02*dxp0*dzp7);
        result(1, 1) += weight * (d55*(dxp0*dxp0) + d11*(dyp0*dyp0) + d33*(dzp0*dzp0));
        result(1, 2) += weight * ((d12 + d33)*dyp0*dzp0);
        result(1, 3) += weight * (d01*dxp1*dyp0 + d55*dxp0*dyp1);
        result(1, 4) += weight * (d55*dxp0*dxp1 + d11*dyp0*dyp1 + d33*dzp0*dzp1);
        result(1, 5) += weight * (d33*dyp1*dzp0 + d12*dyp0*dzp1);
        result(1, 6) += weight * (d01*dxp2*dyp0 + d55*dxp0*dyp2);
        result(1, 7) += weight * (d55*dxp0*dxp2 + d11*dyp0*dyp2 + d33*dzp0*dzp2);
        result(1, 8) += weight * (d33*dyp2*dzp0 + d12*dyp0*dzp2);
        result(1, 9) += weight * (d01*dxp3*dyp0 + d55*dxp0*dyp3);
        result(1, 10) += weight * (d55*dxp0*dxp3 + d11*dyp0*dyp3 + d33*dzp0*dzp3);
        result(1, 11) += weight * (d33*dyp3*dzp0 + d12*dyp0*dzp3);
        result(1, 12) += weight * (d01*dxp4*dyp0 + d55*dxp0*dyp4);
        result(1, 13) += weight * (d55*dxp0*dxp4 + d11*dyp0*dyp4 + d33*dzp0*dzp4);
        result(1, 14) += weight * (d33*dyp4*dzp0 + d12*dyp0*dzp4);
        result(1, 15) += weight * (d01*dxp5*dyp0 + d55*dxp0*dyp5);
        result(1, 16) += weight * (d55*dxp0*dxp5 + d11*dyp0*dyp5 + d33*dzp0*dzp5);
        result(1, 17) += weight * (d33*dyp5*dzp0 + d12*dyp0*dzp5);
        result(1, 18) += weight * (d01*dxp6*dyp0 + d55*dxp0*dyp6);
        result(1, 19) += weight * (d55*dxp0*dxp6 + d11*dyp0*dyp6 + d33*dzp0*dzp6);
        result(1, 20) += weight * (d33*dyp6*dzp0 + d12*dyp0*dzp6);
        result(1, 21) += weight * (d01*dxp7*dyp0 + d55*dxp0*dyp7);
        result(1, 22) += weight * (d55*dxp0*dxp7 + d11*dyp0*dyp7 + d33*dzp0*dzp7);
        result(1, 23) += weight * (d33*dyp7*dzp0 + d12*dyp0*dzp7);
        result(2, 2) += weight * (d44*(dxp0*dxp0) + d33*(dyp0*dyp0) + d22*(dzp0*dzp0));
        result(2, 3) += weight * (d02*dxp1*dzp0 + d44*dxp0*dzp1);
        result(2, 4) += weight * (d12*dyp1*dzp0 + d33*dyp0*dzp1);
        result(2, 5) += weight * (d44*dxp0*dxp1 + d33*dyp0*dyp1 + d22*dzp0*dzp1);
        result(2, 6) += weight * (d02*dxp2*dzp0 + d44*dxp0*dzp2);
        result(2, 7) += weight * (d12*dyp2*dzp0 + d33*dyp0*dzp2);
        result(2, 8) += weight * (d44*dxp0*dxp2 + d33*dyp0*dyp2 + d22*dzp0*dzp2);
        result(2, 9) += weight * (d02*dxp3*dzp0 + d44*dxp0*dzp3);
        result(2, 10) += weight * (d12*dyp3*dzp0 + d33*dyp0*dzp3);
        result(2, 11) += weight * (d44*dxp0*dxp3 + d33*dyp0*dyp3 + d22*dzp0*dzp3);
        result(2, 12) += weight * (d02*dxp4*dzp0 + d44*dxp0*dzp4);
        result(2, 13) += weight * (d12*dyp4*dzp0 + d33*dyp0*dzp4);
        result(2, 14) += weight * (d44*dxp0*dxp4 + d33*dyp0*dyp4 + d22*dzp0*dzp4);
        result(2, 15) += weight * (d02*dxp5*dzp0 + d44*dxp0*dzp5);
        result(2, 16) += weight * (d12*dyp5*dzp0 + d33*dyp0*dzp5);
        result(2, 17) += weight * (d44*dxp0*dxp5 + d33*dyp0*dyp5 + d22*dzp0*dzp5);
        result(2, 18) += weight * (d02*dxp6*dzp0 + d44*dxp0*dzp6);
        result(2, 19) += weight * (d12*dyp6*dzp0 + d33*dyp0*dzp6);
        result(2, 20) += weight * (d44*dxp0*dxp6 + d33*dyp0*dyp6 + d22*dzp0*dzp6);
        result(2, 21) += weight * (d02*dxp7*dzp0 + d44*dxp0*dzp7);
        result(2, 22) += weight * (d12*dyp7*dzp0 + d33*dyp0*dzp7);
        result(2, 23) += weight * (d44*dxp0*dxp7 + d33*dyp0*dyp7 + d22*dzp0*dzp7);
        result(3, 3) += weight * (d00*(dxp1*dxp1) + d55*(dyp1*dyp1) + d44*(dzp1*dzp1));
        result(3, 4) += weight * ((d01 + d55)*dxp1*dyp1);
        result(3, 5) += weight * ((d02 + d44)*dxp1*dzp1);
        result(3, 6) += weight * (d00*dxp1*dxp2 + d55*dyp1*dyp2 + d44*dzp1*dzp2);
        result(3, 7) += weight * (d55*dxp2*dyp1 + d01*dxp1*dyp2);
        result(3, 8) += weight * (d44*dxp2*dzp1 + d02*dxp1*dzp2);
        result(3, 9) += weight * (d00*dxp1*dxp3 + d55*dyp1*dyp3 + d44*dzp1*dzp3);
        result(3, 10) += weight * (d55*dxp3*dyp1 + d01*dxp1*dyp3);
        result(3, 11) += weight * (d44*dxp3*dzp1 + d02*dxp1*dzp3);
        result(3, 12) += weight * (d00*dxp1*dxp4 + d55*dyp1*dyp4 + d44*dzp1*dzp4);
        result(3, 13) += weight * (d55*dxp4*dyp1 + d01*dxp1*dyp4);
        result(3, 14) += weight * (d44*dxp4*dzp1 + d02*dxp1*dzp4);
        result(3, 15) += weight * (d00*dxp1*dxp5 + d55*dyp1*dyp5 + d44*dzp1*dzp5);
        result(3, 16) += weight * (d55*dxp5*dyp1 + d01*dxp1*dyp5);
        result(3, 17) += weight * (d44*dxp5*dzp1 + d02*dxp1*dzp5);
        result(3, 18) += weight * (d00*dxp1*dxp6 + d55*dyp1*dyp6 + d44*dzp1*dzp6);
        result(3, 19) += weight * (d55*dxp6*dyp1 + d01*dxp1*dyp6);
        result(3, 20) += weight * (d44*dxp6*dzp1 + d02*dxp1*dzp6);
        result(3, 21) += weight * (d00*dxp1*dxp7 + d55*dyp1*dyp7 + d44*dzp1*dzp7);
        result(3, 22) += weight * (d55*dxp7*dyp1 + d01*dxp1*dyp7);
        result(3, 23) += weight * (d44*dxp7*dzp1 + d02*dxp1*dzp7);
        result(4, 4) += weight * (d55*(dxp1*dxp1) + d11*(dyp1*dyp1) + d33*(dzp1*dzp1));
        result(4, 5) += weight * ((d12 + d33)*dyp1*dzp1);
        result(4, 6) += weight * (d01*dxp2*dyp1 + d55*dxp1*dyp2);
        result(4, 7) += weight * (d55*dxp1*dxp2 + d11*dyp1*dyp2 + d33*dzp1*dzp2);
        result(4, 8) += weight * (d33*dyp2*dzp1 + d12*dyp1*dzp2);
        result(4, 9) += weight * (d01*dxp3*dyp1 + d55*dxp1*dyp3);
        result(4, 10) += weight * (d55*dxp1*dxp3 + d11*dyp1*dyp3 + d33*dzp1*dzp3);
        result(4, 11) += weight * (d33*dyp3*dzp1 + d12*dyp1*dzp3);
        result(4, 12) += weight * (d01*dxp4*dyp1 + d55*dxp1*dyp4);
        result(4, 13) += weight * (d55*dxp1*dxp4 + d11*dyp1*dyp4 + d33*dzp1*dzp4);
        result(4, 14) += weight * (d33*dyp4*dzp1 + d12*dyp1*dzp4);
        result(4, 15) += weight * (d01*dxp5*dyp1 + d55*dxp1*dyp5);
        result(4, 16) += weight * (d55*dxp1*dxp5 + d11*dyp1*dyp5 + d33*dzp1*dzp5);
        result(4, 17) += weight * (d33*dyp5*dzp1 + d12*dyp1*dzp5);
        result(4, 18) += weight * (d01*dxp6*dyp1 + d55*dxp1*dyp6);
        result(4, 19) += weight * (d55*dxp1*dxp6 + d11*dyp1*dyp6 + d33*dzp1*dzp6);
        result(4, 20) += weight * (d33*dyp6*dzp1 + d12*dyp1*dzp6);
        result(4, 21) += weight * (d01*dxp7*dyp1 + d55*dxp1*dyp7);
        result(4, 22) += weight * (d55*dxp1*dxp7 + d11*dyp1*dyp7 + d33*dzp1*dzp7);
        result(4, 23) += weight * (d33*dyp7*dzp1 + d12*dyp1*dzp7);
        result(5, 5) += weight * (d44*(dxp1*dxp1) + d33*(dyp1*dyp1) + d22*(dzp1*dzp1));
        result(5, 6) += weight * (d02*dxp2*dzp1 + d44*dxp1*dzp2);
        result(5, 7) += weight * (d12*dyp2*dzp1 + d33*dyp1*dzp2);
        result(5, 8) += weight * (d44*dxp1*dxp2 + d33*dyp1*dyp2 + d22*dzp1*dzp2);
        result(5, 9) += weight * (d02*dxp3*dzp1 + d44*dxp1*dzp3);
        result(5, 10) += weight * (d12*dyp3*dzp1 + d33*dyp1*dzp3);
        result(5, 11) += weight * (d44*dxp1*dxp3 + d33*dyp1*dyp3 + d22*dzp1*dzp3);
        result(5, 12) += weight * (d02*dxp4*dzp1 + d44*dxp1*dzp4);
        result(5, 13) += weight * (d12*dyp4*dzp1 + d33*dyp1*dzp4);
        result(5, 14) += weight * (d44*dxp1*dxp4 + d33*dyp1*dyp4 + d22*dzp1*dzp4);
        result(5, 15) += weight * (d02*dxp5*dzp1 + d44*dxp1*dzp5);
        result(5, 16) += weight * (d12*dyp5*dzp1 + d33*dyp1*dzp5);
        result(5, 17) += weight * (d44*dxp1*dxp5 + d33*dyp1*dyp5 + d22*dzp1*dzp5);
        result(5, 18) += weight * (d02*dxp6*dzp1 + d44*dxp1*dzp6);
        result(5, 19) += weight * (d12*dyp6*dzp1 + d33*dyp1*dzp6);
        result(5, 20) += weight * (d44*dxp1*dxp6 + d33*dyp1*dyp6 + d22*dzp1*dzp6);
        result(5, 21) += weight * (d02*dxp7*dzp1 + d44*dxp1*dzp7);
        result(5, 22) += weight * (d12*dyp7*dzp1 + d33*dyp1*dzp7);
        result(5, 23) += weight * (d44*dxp1*dxp7 + d33*dyp1*dyp7 + d22*dzp1*dzp7);
        result(6, 6) += weight * (d00*(dxp2*dxp2) + d55*(dyp2*dyp2) + d44*(dzp2*dzp2));
        result(6, 7) += weight * ((d01 + d55)*dxp2*dyp2);
        result(6, 8) += weight * ((d02 + d44)*dxp2*dzp2);
        result(6, 9) += weight * (d00*dxp2*dxp3 + d55*dyp2*dyp3 + d44*dzp2*dzp3);
        result(6, 10) += weight * (d55*dxp3*dyp2 + d01*dxp2*dyp3);
        result(6, 11) += weight * (d44*dxp3*dzp2 + d02*dxp2*dzp3);
        result(6, 12) += weight * (d00*dxp2*dxp4 + d55*dyp2*dyp4 + d44*dzp2*dzp4);
        result(6, 13) += weight * (d55*dxp4*dyp2 + d01*dxp2*dyp4);
        result(6, 14) += weight * (d44*dxp4*dzp2 + d02*dxp2*dzp4);
        result(6, 15) += weight * (d00*dxp2*dxp5 + d55*dyp2*dyp5 + d44*dzp2*dzp5);
        result(6, 16) += weight * (d55*dxp5*dyp2 + d01*dxp2*dyp5);
        result(6, 17) += weight * (d44*dxp5*dzp2 + d02*dxp2*dzp5);
        result(6, 18) += weight * (d00*dxp2*dxp6 + d55*dyp2*dyp6 + d44*dzp2*dzp6);
        result(6, 19) += weight * (d55*dxp6*dyp2 + d01*dxp2*dyp6);
        result(6, 20) += weight * (d44*dxp6*dzp2 + d02*dxp2*dzp6);
        result(6, 21) += weight * (d00*dxp2*dxp7 + d55*dyp2*dyp7 + d44*dzp2*dzp7);
        result(6, 22) += weight * (d55*dxp7*dyp2 + d01*dxp2*dyp7);
        result(6, 23) += weight * (d44*dxp7*dzp2 + d02*dxp2*dzp7);
        result(7, 7) += weight * (d55*(dxp2*dxp2) + d11*(dyp2*dyp2) + d33*(dzp2*dzp2));
        result(7, 8) += weight * ((d12 + d33)*dyp2*dzp2);
        result(7, 9) += weight * (d01*dxp3*dyp2 + d55*dxp2*dyp3);
        result(7, 10) += weight * (d55*dxp2*dxp3 + d11*dyp2*dyp3 + d33*dzp2*dzp3);
        result(7, 11) += weight * (d33*dyp3*dzp2 + d12*dyp2*dzp3);
        result(7, 12) += weight * (d01*dxp4*dyp2 + d55*dxp2*dyp4);
        result(7, 13) += weight * (d55*dxp2*dxp4 + d11*dyp2*dyp4 + d33*dzp2*dzp4);
        result(7, 14) += weight * (d33*dyp4*dzp2 + d12*dyp2*dzp4);
        result(7, 15) += weight * (d01*dxp5*dyp2 + d55*dxp2*dyp5);
        result(7, 16) += weight * (d55*dxp2*dxp5 + d11*dyp2*dyp5 + d33*dzp2*dzp5);
        result(7, 17) += weight * (d33*dyp5*dzp2 + d12*dyp2*dzp5);
        result(7, 18) += weight * (d01*dxp6*dyp2 + d55*dxp2*dyp6);
        result(7, 19) += weight * (d55*dxp2*dxp6 + d11*dyp2*dyp6 + d33*dzp2*dzp6);
        result(7, 20) += weight * (d33*dyp6*dzp2 + d12*dyp2*dzp6);
        result(7, 21) += weight * (d01*dxp7*dyp2 + d55*dxp2*dyp7);
        result(7, 22) += weight * (d55*dxp2*dxp7 + d11*dyp2*dyp7 + d33*dzp2*dzp7);
        result(7, 23) += weight * (d33*dyp7*dzp2 + d12*dyp2*dzp7);
        result(8, 8) += weight * (d44*(dxp2*dxp2) + d33*(dyp2*dyp2) + d22*(dzp2*dzp2));
        result(8, 9) += weight * (d02*dxp3*dzp2 + d44*dxp2*dzp3);
        result(8, 10) += weight * (d12*dyp3*dzp2 + d33*dyp2*dzp3);
        result(8, 11) += weight * (d44*dxp2*dxp3 + d33*dyp2*dyp3 + d22*dzp2*dzp3);
        result(8, 12) += weight * (d02*dxp4*dzp2 + d44*dxp2*dzp4);
        result(8, 13) += weight * (d12*dyp4*dzp2 + d33*dyp2*dzp4);
        result(8, 14) += weight * (d44*dxp2*dxp4 + d33*dyp2*dyp4 + d22*dzp2*dzp4);
        result(8, 15) += weight * (d02*dxp5*dzp2 + d44*dxp2*dzp5);
        result(8, 16) += weight * (d12*dyp5*dzp2 + d33*dyp2*dzp5);
        result(8, 17) += weight * (d44*dxp2*dxp5 + d33*dyp2*dyp5 + d22*dzp2*dzp5);
        result(8, 18) += weight * (d02*dxp6*dzp2 + d44*dxp2*dzp6);
        result(8, 19) += weight * (d12*dyp6*dzp2 + d33*dyp2*dzp6);
        result(8, 20) += weight * (d44*dxp2*dxp6 + d33*dyp2*dyp6 + d22*dzp2*dzp6);
        result(8, 21) += weight * (d02*dxp7*dzp2 + d44*dxp2*dzp7);
        result(8, 22) += weight * (d12*dyp7*dzp2 + d33*dyp2*dzp7);
        result(8, 23) += weight * (d44*dxp2*dxp7 + d33*dyp2*dyp7 + d22*dzp2*dzp7);
        result(9, 9) += weight * (d00*(dxp3*dxp3) + d55*(dyp3*dyp3) + d44*(dzp3*dzp3));
        result(9, 10) += weight * ((d01 + d55)*dxp3*dyp3);
        result(9, 11) += weight * ((d02 + d44)*dxp3*dzp3);
        result(9, 12) += weight * (d00*dxp3*dxp4 + d55*dyp3*dyp4 + d44*dzp3*dzp4);
        result(9, 13) += weight * (d55*dxp4*dyp3 + d01*dxp3*dyp4);
        result(9, 14) += weight * (d44*dxp4*dzp3 + d02*dxp3*dzp4);
        result(9, 15) += weight * (d00*dxp3*dxp5 + d55*dyp3*dyp5 + d44*dzp3*dzp5);
        result(9, 16) += weight * (d55*dxp5*dyp3 + d01*dxp3*dyp5);
        result(9, 17) += weight * (d44*dxp5*dzp3 + d02*dxp3*dzp5);
        result(9, 18) += weight * (d00*dxp3*dxp6 + d55*dyp3*dyp6 + d44*dzp3*dzp6);
        result(9, 19) += weight * (d55*dxp6*dyp3 + d01*dxp3*dyp6);
        result(9, 20) += weight * (d44*dxp6*dzp3 + d02*dxp3*dzp6);
        result(9, 21) += weight * (d00*dxp3*dxp7 + d55*dyp3*dyp7 + d44*dzp3*dzp7);
        result(9, 22) += weight * (d55*dxp7*dyp3 + d01*dxp3*dyp7);
        result(9, 23) += weight * (d44*dxp7*dzp3 + d02*dxp3*dzp7);
        result(10, 10) += weight * (d55*(dxp3*dxp3) + d11*(dyp3*dyp3) + d33*(dzp3*dzp3));
        result(10, 11) += weight * ((d12 + d33)*dyp3*dzp3);
        result(10, 12) += weight * (d01*dxp4*dyp3 + d55*dxp3*dyp4);
        result(10, 13) += weight * (d55*dxp3*dxp4 + d11*dyp3*dyp4 + d33*dzp3*dzp4);
        result(10, 14) += weight * (d33*dyp4*dzp3 + d12*dyp3*dzp4);
        result(10, 15) += weight * (d01*dxp5*dyp3 + d55*dxp3*dyp5);
        result(10, 16) += weight * (d55*dxp3*dxp5 + d11*dyp3*dyp5 + d33*dzp3*dzp5);
        result(10, 17) += weight * (d33*dyp5*dzp3 + d12*dyp3*dzp5);
        result(10, 18) += weight * (d01*dxp6*dyp3 + d55*dxp3*dyp6);
        result(10, 19) += weight * (d55*dxp3*dxp6 + d11*dyp3*dyp6 + d33*dzp3*dzp6);
        result(10, 20) += weight * (d33*dyp6*dzp3 + d12*dyp3*dzp6);
        result(10, 21) += weight * (d01*dxp7*dyp3 + d55*dxp3*dyp7);
        result(10, 22) += weight * (d55*dxp3*dxp7 + d11*dyp3*dyp7 + d33*dzp3*dzp7);
        result(10, 23) += weight * (d33*dyp7*dzp3 + d12*dyp3*dzp7);
        result(11, 11) += weight * (d44*(dxp3*dxp3) + d33*(dyp3*dyp3) + d22*(dzp3*dzp3));
        result(11, 12) += weight * (d02*dxp4*dzp3 + d44*dxp3*dzp4);
        result(11, 13) += weight * (d12*dyp4*dzp3 + d33*dyp3*dzp4);
        result(11, 14) += weight * (d44*dxp3*dxp4 + d33*dyp3*dyp4 + d22*dzp3*dzp4);
        result(11, 15) += weight * (d02*dxp5*dzp3 + d44*dxp3*dzp5);
        result(11, 16) += weight * (d12*dyp5*dzp3 + d33*dyp3*dzp5);
        result(11, 17) += weight * (d44*dxp3*dxp5 + d33*dyp3*dyp5 + d22*dzp3*dzp5);
        result(11, 18) += weight * (d02*dxp6*dzp3 + d44*dxp3*dzp6);
        result(11, 19) += weight * (d12*dyp6*dzp3 + d33*dyp3*dzp6);
        result(11, 20) += weight * (d44*dxp3*dxp6 + d33*dyp3*dyp6 + d22*dzp3*dzp6);
        result(11, 21) += weight * (d02*dxp7*dzp3 + d44*dxp3*dzp7);
        result(11, 22) += weight * (d12*dyp7*dzp3 + d33*dyp3*dzp7);
        result(11, 23) += weight * (d44*dxp3*dxp7 + d33*dyp3*dyp7 + d22*dzp3*dzp7);
        result(12, 12) += weight * (d00*(dxp4*dxp4) + d55*(dyp4*dyp4) + d44*(dzp4*dzp4));
        result(12, 13) += weight * ((d01 + d55)*dxp4*dyp4);
        result(12, 14) += weight * ((d02 + d44)*dxp4*dzp4);
        result(12, 15) += weight * (d00*dxp4*dxp5 + d55*dyp4*dyp5 + d44*dzp4*dzp5);
        result(12, 16) += weight * (d55*dxp5*dyp4 + d01*dxp4*dyp5);
        result(12, 17) += weight * (d44*dxp5*dzp4 + d02*dxp4*dzp5);
        result(12, 18) += weight * (d00*dxp4*dxp6 + d55*dyp4*dyp6 + d44*dzp4*dzp6);
        result(12, 19) += weight * (d55*dxp6*dyp4 + d01*dxp4*dyp6);
        result(12, 20) += weight * (d44*dxp6*dzp4 + d02*dxp4*dzp6);
        result(12, 21) += weight * (d00*dxp4*dxp7 + d55*dyp4*dyp7 + d44*dzp4*dzp7);
        result(12, 22) += weight * (d55*dxp7*dyp4 + d01*dxp4*dyp7);
        result(12, 23) += weight * (d44*dxp7*dzp4 + d02*dxp4*dzp7);
        result(13, 13) += weight * (d55*(dxp4*dxp4) + d11*(dyp4*dyp4) + d33*(dzp4*dzp4));
        result(13, 14) += weight * ((d12 + d33)*dyp4*dzp4);
        result(13, 15) += weight * (d01*dxp5*dyp4 + d55*dxp4*dyp5);
        result(13, 16) += weight * (d55*dxp4*dxp5 + d11*dyp4*dyp5 + d33*dzp4*dzp5);
        result(13, 17) += weight * (d33*dyp5*dzp4 + d12*dyp4*dzp5);
        result(13, 18) += weight * (d01*dxp6*dyp4 + d55*dxp4*dyp6);
        result(13, 19) += weight * (d55*dxp4*dxp6 + d11*dyp4*dyp6 + d33*dzp4*dzp6);
        result(13, 20) += weight * (d33*dyp6*dzp4 + d12*dyp4*dzp6);
        result(13, 21) += weight * (d01*dxp7*dyp4 + d55*dxp4*dyp7);
        result(13, 22) += weight * (d55*dxp4*dxp7 + d11*dyp4*dyp7 + d33*dzp4*dzp7);
        result(13, 23) += weight * (d33*dyp7*dzp4 + d12*dyp4*dzp7);
        result(14, 14) += weight * (d44*(dxp4*dxp4) + d33*(dyp4*dyp4) + d22*(dzp4*dzp4));
        result(14, 15) += weight * (d02*dxp5*dzp4 + d44*dxp4*dzp5);
        result(14, 16) += weight * (d12*dyp5*dzp4 + d33*dyp4*dzp5);
        result(14, 17) += weight * (d44*dxp4*dxp5 + d33*dyp4*dyp5 + d22*dzp4*dzp5);
        result(14, 18) += weight * (d02*dxp6*dzp4 + d44*dxp4*dzp6);
        result(14, 19) += weight * (d12*dyp6*dzp4 + d33*dyp4*dzp6);
        result(14, 20) += weight * (d44*dxp4*dxp6 + d33*dyp4*dyp6 + d22*dzp4*dzp6);
        result(14, 21) += weight * (d02*dxp7*dzp4 + d44*dxp4*dzp7);
        result(14, 22) += weight * (d12*dyp7*dzp4 + d33*dyp4*dzp7);
        result(14, 23) += weight * (d44*dxp4*dxp7 + d33*dyp4*dyp7 + d22*dzp4*dzp7);
        result(15, 15) += weight * (d00*(dxp5*dxp5) + d55*(dyp5*dyp5) + d44*(dzp5*dzp5));
        result(15, 16) += weight * ((d01 + d55)*dxp5*dyp5);
        result(15, 17) += weight * ((d02 + d44)*dxp5*dzp5);
        result(15, 18) += weight * (d00*dxp5*dxp6 + d55*dyp5*dyp6 + d44*dzp5*dzp6);
        result(15, 19) += weight * (d55*dxp6*dyp5 + d01*dxp5*dyp6);
        result(15, 20) += weight * (d44*dxp6*dzp5 + d02*dxp5*dzp6);
        result(15, 21) += weight * (d00*dxp5*dxp7 + d55*dyp5*dyp7 + d44*dzp5*dzp7);
        result(15, 22) += weight * (d55*dxp7*dyp5 + d01*dxp5*dyp7);
        result(15, 23) += weight * (d44*dxp7*dzp5 + d02*dxp5*dzp7);
        result(16, 16) += weight * (d55*(dxp5*dxp5) + d11*(dyp5*dyp5) + d33*(dzp5*dzp5));
        result(16, 17) += weight * ((d12 + d33)*dyp5*dzp5);
        result(16, 18) += weight * (d01*dxp6*dyp5 + d55*dxp5*dyp6);
        result(16, 19) += weight * (d55*dxp5*dxp6 + d11*dyp5*dyp6 + d33*dzp5*dzp6);
        result(16, 20) += weight * (d33*dyp6*dzp5 + d12*dyp5*dzp6);
        result(16, 21) += weight * (d01*dxp7*dyp5 + d55*dxp5*dyp7);
        result(16, 22) += weight * (d55*dxp5*dxp7 + d11*dyp5*dyp7 + d33*dzp5*dzp7);
        result(16, 23) += weight * (d33*dyp7*dzp5 + d12*dyp5*dzp7);
        result(17, 17) += weight * (d44*(dxp5*dxp5) + d33*(dyp5*dyp5) + d22*(dzp5*dzp5));
        result(17, 18) += weight * (d02*dxp6*dzp5 + d44*dxp5*dzp6);
        result(17, 19) += weight * (d12*dyp6*dzp5 + d33*dyp5*dzp6);
        result(17, 20) += weight * (d44*dxp5*dxp6 + d33*dyp5*dyp6 + d22*dzp5*dzp6);
        result(17, 21) += weight * (d02*dxp7*dzp5 + d44*dxp5*dzp7);
        result(17, 22) += weight * (d12*dyp7*dzp5 + d33*dyp5*dzp7);
        result(17, 23) += weight * (d44*dxp5*dxp7 + d33*dyp5*dyp7 + d22*dzp5*dzp7);
        result(18, 18) += weight * (d00*(dxp6*dxp6) + d55*(dyp6*dyp6) + d44*(dzp6*dzp6));
        result(18, 19) += weight * ((d01 + d55)*dxp6*dyp6);
        result(18, 20) += weight * ((d02 + d44)*dxp6*dzp6);
        result(18, 21) += weight * (d00*dxp6*dxp7 + d55*dyp6*dyp7 + d44*dzp6*dzp7);
        result(18, 22) += weight * (d55*dxp7*dyp6 + d01*dxp6*dyp7);
        result(18, 23) += weight * (d44*dxp7*dzp6 + d02*dxp6*dzp7);
        result(19, 19) += weight * (d55*(dxp6*dxp6) + d11*(dyp6*dyp6) + d33*(dzp6*dzp6));
        result(19, 20) += weight * ((d12 + d33)*dyp6*dzp6);
        result(19, 21) += weight * (d01*dxp7*dyp6 + d55*dxp6*dyp7);
        result(19, 22) += weight * (d55*dxp6*dxp7 + d11*dyp6*dyp7 + d33*dzp6*dzp7);
        result(19, 23) += weight * (d33*dyp7*dzp6 + d12*dyp6*dzp7);
        result(20, 20) += weight * (d44*(dxp6*dxp6) + d33*(dyp6*dyp6) + d22*(dzp6*dzp6));
        result(20, 21) += weight * (d02*dxp7*dzp6 + d44*dxp6*dzp7);
        result(20, 22) += weight * (d12*dyp7*dzp6 + d33*dyp6*dzp7);
        result(20, 23) += weight * (d44*dxp6*dxp7 + d33*dyp6*dyp7 + d22*dzp6*dzp7);
        result(21, 21) += weight * (d00*(dxp7*dxp7) + d55*(dyp7*dyp7) + d44*(dzp7*dzp7));
        result(21, 22) += weight * ((d01 + d55)*dxp7*dyp7);
        result(21, 23) += weight * ((d02 + d44)*dxp7*dzp7);
        result(22, 22) += weight * (d55*(dxp7*dxp7) + d11*(dyp7*dyp7) + d33*(dzp7*dzp7));
        result(22, 23) += weight * ((d12 + d33)*dyp7*dzp7);
        result(23, 23) += weight * (d44*(dxp7*dxp7) + d33*(dyp7*dyp7) + d22*(dzp7*dzp7));
    }

    // Analytic result for a full cell
    Real fullCellIntegral(size_t i, size_t j) {
        if (!m_fullCellIntegralCached) {
            // Unpack elasticity tensor
            // .5 scaling for off-diagonals  is to account for engineering stress :
            // engineering strain double-counting the off-diagonals.
            Real d00 = m_d[0], d01 = 0.5 * m_d[1], d02 = 0.5 * m_d[ 2], // d03 = 0.5 * m_d[ 3], d04 = .5 * m_d[ 4], d05 = .5 * m_d[ 5],
                               d11 =       m_d[6], d12 = 0.5 * m_d[ 7], // d13 = 0.5 * m_d[ 8], d14 = .5 * m_d[ 9], d15 = .5 * m_d[10],
                                                   d22 =       m_d[11], // d23 = 0.5 * m_d[12], d24 = .5 * m_d[13], d25 = .5 * m_d[14],
                                                                        d33 =       m_d[15], // d34 = .5 * m_d[16], d35 = .5 * m_d[17],
                                                                                             d44 =      m_d[18], // d45 = .5 * m_d[19],
                                                                                                                 d55 =      m_d[20];

            Real w = m_dimensions[0];
            Real h = m_dimensions[1];
            Real d = m_dimensions[2];
            Real invVol = 1.0 / (w * h * d);

            Real dSqhSq = d * d * h * h;
            Real dSqwSq = d * d * w * w;
            Real hSqwSq = h * h * w * w;
            Real dSqhw  = d * d * h * w;
            Real wSqdh  = w * w * d * h;
            Real hSqdw  = h * h * d * w;

            fullCellResult(0, 0) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            fullCellResult(0, 1) = invVol * ((d01 + d55)*dSqhw)/12.;
            fullCellResult(0, 2) = invVol * ((d02 + d44)*hSqdw)/12.;
            fullCellResult(0, 3) = invVol * (-2*d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/18.;
            fullCellResult(0, 4) = invVol * ((d01 - d55)*dSqhw)/12.;
            fullCellResult(0, 5) = invVol * ((d02 - d44)*hSqdw)/12.;
            fullCellResult(0, 6) = invVol * (-2*d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/36.;
            fullCellResult(0, 7) = invVol * -((d01 + d55)*dSqhw)/12.;
            fullCellResult(0, 8) = invVol * ((d02 - d44)*hSqdw)/24.;
            fullCellResult(0, 9) = invVol * (d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/18.;
            fullCellResult(0, 10) = invVol * ((-d01 + d55)*dSqhw)/12.;
            fullCellResult(0, 11) = invVol * ((d02 + d44)*hSqdw)/24.;
            fullCellResult(0, 12) = invVol * (d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/18.;
            fullCellResult(0, 13) = invVol * ((d01 + d55)*dSqhw)/24.;
            fullCellResult(0, 14) = invVol * ((-d02 + d44)*hSqdw)/12.;
            fullCellResult(0, 15) = invVol * (-2*d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/36.;
            fullCellResult(0, 16) = invVol * ((d01 - d55)*dSqhw)/24.;
            fullCellResult(0, 17) = invVol * -((d02 + d44)*hSqdw)/12.;
            fullCellResult(0, 18) = invVol * (-(d00*dSqhSq) - d55*dSqwSq - d44*hSqwSq)/36.;
            fullCellResult(0, 19) = invVol * -((d01 + d55)*dSqhw)/24.;
            fullCellResult(0, 20) = invVol * -((d02 + d44)*hSqdw)/24.;
            fullCellResult(0, 21) = invVol * (d00*dSqhSq - 2*(d55*dSqwSq + d44*hSqwSq))/36.;
            fullCellResult(0, 22) = invVol * ((-d01 + d55)*dSqhw)/24.;
            fullCellResult(0, 23) = invVol * ((-d02 + d44)*hSqdw)/24.;
            fullCellResult(1, 1) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            fullCellResult(1, 2) = invVol * ((d12 + d33)*wSqdh)/12.;
            fullCellResult(1, 3) = invVol * ((-d01 + d55)*dSqhw)/12.;
            fullCellResult(1, 4) = invVol * (-2*d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/18.;
            fullCellResult(1, 5) = invVol * ((d12 + d33)*wSqdh)/24.;
            fullCellResult(1, 6) = invVol * -((d01 + d55)*dSqhw)/12.;
            fullCellResult(1, 7) = invVol * (-2*d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/36.;
            fullCellResult(1, 8) = invVol * ((d12 - d33)*wSqdh)/24.;
            fullCellResult(1, 9) = invVol * ((d01 - d55)*dSqhw)/12.;
            fullCellResult(1, 10) = invVol * (d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/18.;
            fullCellResult(1, 11) = invVol * ((d12 - d33)*wSqdh)/12.;
            fullCellResult(1, 12) = invVol * ((d01 + d55)*dSqhw)/24.;
            fullCellResult(1, 13) = invVol * (d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/18.;
            fullCellResult(1, 14) = invVol * ((-d12 + d33)*wSqdh)/12.;
            fullCellResult(1, 15) = invVol * ((-d01 + d55)*dSqhw)/24.;
            fullCellResult(1, 16) = invVol * (-2*d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/36.;
            fullCellResult(1, 17) = invVol * ((-d12 + d33)*wSqdh)/24.;
            fullCellResult(1, 18) = invVol * -((d01 + d55)*dSqhw)/24.;
            fullCellResult(1, 19) = invVol * (-(d55*dSqhSq) - d11*dSqwSq - d33*hSqwSq)/36.;
            fullCellResult(1, 20) = invVol * -((d12 + d33)*wSqdh)/24.;
            fullCellResult(1, 21) = invVol * ((d01 - d55)*dSqhw)/24.;
            fullCellResult(1, 22) = invVol * (d55*dSqhSq - 2*(d11*dSqwSq + d33*hSqwSq))/36.;
            fullCellResult(1, 23) = invVol * -((d12 + d33)*wSqdh)/12.;
            fullCellResult(2, 2) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            fullCellResult(2, 3) = invVol * ((-d02 + d44)*hSqdw)/12.;
            fullCellResult(2, 4) = invVol * ((d12 + d33)*wSqdh)/24.;
            fullCellResult(2, 5) = invVol * (-2*d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/18.;
            fullCellResult(2, 6) = invVol * ((-d02 + d44)*hSqdw)/24.;
            fullCellResult(2, 7) = invVol * ((-d12 + d33)*wSqdh)/24.;
            fullCellResult(2, 8) = invVol * (-2*d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/36.;
            fullCellResult(2, 9) = invVol * ((d02 + d44)*hSqdw)/24.;
            fullCellResult(2, 10) = invVol * ((-d12 + d33)*wSqdh)/12.;
            fullCellResult(2, 11) = invVol * (d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/18.;
            fullCellResult(2, 12) = invVol * ((d02 - d44)*hSqdw)/12.;
            fullCellResult(2, 13) = invVol * ((d12 - d33)*wSqdh)/12.;
            fullCellResult(2, 14) = invVol * (d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/18.;
            fullCellResult(2, 15) = invVol * -((d02 + d44)*hSqdw)/12.;
            fullCellResult(2, 16) = invVol * ((d12 - d33)*wSqdh)/24.;
            fullCellResult(2, 17) = invVol * (-2*d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/36.;
            fullCellResult(2, 18) = invVol * -((d02 + d44)*hSqdw)/24.;
            fullCellResult(2, 19) = invVol * -((d12 + d33)*wSqdh)/24.;
            fullCellResult(2, 20) = invVol * (-(d44*dSqhSq) - d33*dSqwSq - d22*hSqwSq)/36.;
            fullCellResult(2, 21) = invVol * ((d02 - d44)*hSqdw)/24.;
            fullCellResult(2, 22) = invVol * -((d12 + d33)*wSqdh)/12.;
            fullCellResult(2, 23) = invVol * (d44*dSqhSq - 2*(d33*dSqwSq + d22*hSqwSq))/36.;
            fullCellResult(3, 3) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            fullCellResult(3, 4) = invVol * -((d01 + d55)*dSqhw)/12.;
            fullCellResult(3, 5) = invVol * -((d02 + d44)*hSqdw)/12.;
            fullCellResult(3, 6) = invVol * (d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/18.;
            fullCellResult(3, 7) = invVol * ((d01 - d55)*dSqhw)/12.;
            fullCellResult(3, 8) = invVol * -((d02 + d44)*hSqdw)/24.;
            fullCellResult(3, 9) = invVol * (-2*d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/36.;
            fullCellResult(3, 10) = invVol * ((d01 + d55)*dSqhw)/12.;
            fullCellResult(3, 11) = invVol * ((-d02 + d44)*hSqdw)/24.;
            fullCellResult(3, 12) = invVol * (-2*d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/36.;
            fullCellResult(3, 13) = invVol * ((-d01 + d55)*dSqhw)/24.;
            fullCellResult(3, 14) = invVol * ((d02 + d44)*hSqdw)/12.;
            fullCellResult(3, 15) = invVol * (d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/18.;
            fullCellResult(3, 16) = invVol * -((d01 + d55)*dSqhw)/24.;
            fullCellResult(3, 17) = invVol * ((d02 - d44)*hSqdw)/12.;
            fullCellResult(3, 18) = invVol * (d00*dSqhSq - 2*(d55*dSqwSq + d44*hSqwSq))/36.;
            fullCellResult(3, 19) = invVol * ((d01 - d55)*dSqhw)/24.;
            fullCellResult(3, 20) = invVol * ((d02 - d44)*hSqdw)/24.;
            fullCellResult(3, 21) = invVol * (-(d00*dSqhSq) - d55*dSqwSq - d44*hSqwSq)/36.;
            fullCellResult(3, 22) = invVol * ((d01 + d55)*dSqhw)/24.;
            fullCellResult(3, 23) = invVol * ((d02 + d44)*hSqdw)/24.;
            fullCellResult(4, 4) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            fullCellResult(4, 5) = invVol * ((d12 + d33)*wSqdh)/12.;
            fullCellResult(4, 6) = invVol * ((-d01 + d55)*dSqhw)/12.;
            fullCellResult(4, 7) = invVol * (d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/18.;
            fullCellResult(4, 8) = invVol * ((d12 - d33)*wSqdh)/12.;
            fullCellResult(4, 9) = invVol * ((d01 + d55)*dSqhw)/12.;
            fullCellResult(4, 10) = invVol * (-2*d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/36.;
            fullCellResult(4, 11) = invVol * ((d12 - d33)*wSqdh)/24.;
            fullCellResult(4, 12) = invVol * ((d01 - d55)*dSqhw)/24.;
            fullCellResult(4, 13) = invVol * (-2*d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/36.;
            fullCellResult(4, 14) = invVol * ((-d12 + d33)*wSqdh)/24.;
            fullCellResult(4, 15) = invVol * -((d01 + d55)*dSqhw)/24.;
            fullCellResult(4, 16) = invVol * (d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/18.;
            fullCellResult(4, 17) = invVol * ((-d12 + d33)*wSqdh)/12.;
            fullCellResult(4, 18) = invVol * ((-d01 + d55)*dSqhw)/24.;
            fullCellResult(4, 19) = invVol * (d55*dSqhSq - 2*(d11*dSqwSq + d33*hSqwSq))/36.;
            fullCellResult(4, 20) = invVol * -((d12 + d33)*wSqdh)/12.;
            fullCellResult(4, 21) = invVol * ((d01 + d55)*dSqhw)/24.;
            fullCellResult(4, 22) = invVol * (-(d55*dSqhSq) - d11*dSqwSq - d33*hSqwSq)/36.;
            fullCellResult(4, 23) = invVol * -((d12 + d33)*wSqdh)/24.;
            fullCellResult(5, 5) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            fullCellResult(5, 6) = invVol * -((d02 + d44)*hSqdw)/24.;
            fullCellResult(5, 7) = invVol * ((-d12 + d33)*wSqdh)/12.;
            fullCellResult(5, 8) = invVol * (d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/18.;
            fullCellResult(5, 9) = invVol * ((d02 - d44)*hSqdw)/24.;
            fullCellResult(5, 10) = invVol * ((-d12 + d33)*wSqdh)/24.;
            fullCellResult(5, 11) = invVol * (-2*d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/36.;
            fullCellResult(5, 12) = invVol * ((d02 + d44)*hSqdw)/12.;
            fullCellResult(5, 13) = invVol * ((d12 - d33)*wSqdh)/24.;
            fullCellResult(5, 14) = invVol * (-2*d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/36.;
            fullCellResult(5, 15) = invVol * ((-d02 + d44)*hSqdw)/12.;
            fullCellResult(5, 16) = invVol * ((d12 - d33)*wSqdh)/12.;
            fullCellResult(5, 17) = invVol * (d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/18.;
            fullCellResult(5, 18) = invVol * ((-d02 + d44)*hSqdw)/24.;
            fullCellResult(5, 19) = invVol * -((d12 + d33)*wSqdh)/12.;
            fullCellResult(5, 20) = invVol * (d44*dSqhSq - 2*(d33*dSqwSq + d22*hSqwSq))/36.;
            fullCellResult(5, 21) = invVol * ((d02 + d44)*hSqdw)/24.;
            fullCellResult(5, 22) = invVol * -((d12 + d33)*wSqdh)/24.;
            fullCellResult(5, 23) = invVol * (-(d44*dSqhSq) - d33*dSqwSq - d22*hSqwSq)/36.;
            fullCellResult(6, 6) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            fullCellResult(6, 7) = invVol * ((d01 + d55)*dSqhw)/12.;
            fullCellResult(6, 8) = invVol * -((d02 + d44)*hSqdw)/12.;
            fullCellResult(6, 9) = invVol * (-2*d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/18.;
            fullCellResult(6, 10) = invVol * ((d01 - d55)*dSqhw)/12.;
            fullCellResult(6, 11) = invVol * ((-d02 + d44)*hSqdw)/12.;
            fullCellResult(6, 12) = invVol * (-(d00*dSqhSq) - d55*dSqwSq - d44*hSqwSq)/36.;
            fullCellResult(6, 13) = invVol * -((d01 + d55)*dSqhw)/24.;
            fullCellResult(6, 14) = invVol * ((d02 + d44)*hSqdw)/24.;
            fullCellResult(6, 15) = invVol * (d00*dSqhSq - 2*(d55*dSqwSq + d44*hSqwSq))/36.;
            fullCellResult(6, 16) = invVol * ((-d01 + d55)*dSqhw)/24.;
            fullCellResult(6, 17) = invVol * ((d02 - d44)*hSqdw)/24.;
            fullCellResult(6, 18) = invVol * (d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/18.;
            fullCellResult(6, 19) = invVol * ((d01 + d55)*dSqhw)/24.;
            fullCellResult(6, 20) = invVol * ((d02 - d44)*hSqdw)/12.;
            fullCellResult(6, 21) = invVol * (-2*d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/36.;
            fullCellResult(6, 22) = invVol * ((d01 - d55)*dSqhw)/24.;
            fullCellResult(6, 23) = invVol * ((d02 + d44)*hSqdw)/12.;
            fullCellResult(7, 7) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            fullCellResult(7, 8) = invVol * -((d12 + d33)*wSqdh)/12.;
            fullCellResult(7, 9) = invVol * ((-d01 + d55)*dSqhw)/12.;
            fullCellResult(7, 10) = invVol * (-2*d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/18.;
            fullCellResult(7, 11) = invVol * -((d12 + d33)*wSqdh)/24.;
            fullCellResult(7, 12) = invVol * -((d01 + d55)*dSqhw)/24.;
            fullCellResult(7, 13) = invVol * (-(d55*dSqhSq) - d11*dSqwSq - d33*hSqwSq)/36.;
            fullCellResult(7, 14) = invVol * ((d12 + d33)*wSqdh)/24.;
            fullCellResult(7, 15) = invVol * ((d01 - d55)*dSqhw)/24.;
            fullCellResult(7, 16) = invVol * (d55*dSqhSq - 2*(d11*dSqwSq + d33*hSqwSq))/36.;
            fullCellResult(7, 17) = invVol * ((d12 + d33)*wSqdh)/12.;
            fullCellResult(7, 18) = invVol * ((d01 + d55)*dSqhw)/24.;
            fullCellResult(7, 19) = invVol * (d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/18.;
            fullCellResult(7, 20) = invVol * ((d12 - d33)*wSqdh)/12.;
            fullCellResult(7, 21) = invVol * ((-d01 + d55)*dSqhw)/24.;
            fullCellResult(7, 22) = invVol * (-2*d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/36.;
            fullCellResult(7, 23) = invVol * ((d12 - d33)*wSqdh)/24.;
            fullCellResult(8, 8) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            fullCellResult(8, 9) = invVol * ((d02 - d44)*hSqdw)/12.;
            fullCellResult(8, 10) = invVol * -((d12 + d33)*wSqdh)/24.;
            fullCellResult(8, 11) = invVol * (-2*d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/18.;
            fullCellResult(8, 12) = invVol * ((d02 + d44)*hSqdw)/24.;
            fullCellResult(8, 13) = invVol * ((d12 + d33)*wSqdh)/24.;
            fullCellResult(8, 14) = invVol * (-(d44*dSqhSq) - d33*dSqwSq - d22*hSqwSq)/36.;
            fullCellResult(8, 15) = invVol * ((-d02 + d44)*hSqdw)/24.;
            fullCellResult(8, 16) = invVol * ((d12 + d33)*wSqdh)/12.;
            fullCellResult(8, 17) = invVol * (d44*dSqhSq - 2*(d33*dSqwSq + d22*hSqwSq))/36.;
            fullCellResult(8, 18) = invVol * ((-d02 + d44)*hSqdw)/12.;
            fullCellResult(8, 19) = invVol * ((-d12 + d33)*wSqdh)/12.;
            fullCellResult(8, 20) = invVol * (d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/18.;
            fullCellResult(8, 21) = invVol * ((d02 + d44)*hSqdw)/12.;
            fullCellResult(8, 22) = invVol * ((-d12 + d33)*wSqdh)/24.;
            fullCellResult(8, 23) = invVol * (-2*d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/36.;
            fullCellResult(9, 9) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            fullCellResult(9, 10) = invVol * -((d01 + d55)*dSqhw)/12.;
            fullCellResult(9, 11) = invVol * ((d02 + d44)*hSqdw)/12.;
            fullCellResult(9, 12) = invVol * (d00*dSqhSq - 2*(d55*dSqwSq + d44*hSqwSq))/36.;
            fullCellResult(9, 13) = invVol * ((d01 - d55)*dSqhw)/24.;
            fullCellResult(9, 14) = invVol * ((-d02 + d44)*hSqdw)/24.;
            fullCellResult(9, 15) = invVol * (-(d00*dSqhSq) - d55*dSqwSq - d44*hSqwSq)/36.;
            fullCellResult(9, 16) = invVol * ((d01 + d55)*dSqhw)/24.;
            fullCellResult(9, 17) = invVol * -((d02 + d44)*hSqdw)/24.;
            fullCellResult(9, 18) = invVol * (-2*d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/36.;
            fullCellResult(9, 19) = invVol * ((-d01 + d55)*dSqhw)/24.;
            fullCellResult(9, 20) = invVol * -((d02 + d44)*hSqdw)/12.;
            fullCellResult(9, 21) = invVol * (d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/18.;
            fullCellResult(9, 22) = invVol * -((d01 + d55)*dSqhw)/24.;
            fullCellResult(9, 23) = invVol * ((-d02 + d44)*hSqdw)/12.;
            fullCellResult(10, 10) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            fullCellResult(10, 11) = invVol * -((d12 + d33)*wSqdh)/12.;
            fullCellResult(10, 12) = invVol * ((-d01 + d55)*dSqhw)/24.;
            fullCellResult(10, 13) = invVol * (d55*dSqhSq - 2*(d11*dSqwSq + d33*hSqwSq))/36.;
            fullCellResult(10, 14) = invVol * ((d12 + d33)*wSqdh)/12.;
            fullCellResult(10, 15) = invVol * ((d01 + d55)*dSqhw)/24.;
            fullCellResult(10, 16) = invVol * (-(d55*dSqhSq) - d11*dSqwSq - d33*hSqwSq)/36.;
            fullCellResult(10, 17) = invVol * ((d12 + d33)*wSqdh)/24.;
            fullCellResult(10, 18) = invVol * ((d01 - d55)*dSqhw)/24.;
            fullCellResult(10, 19) = invVol * (-2*d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/36.;
            fullCellResult(10, 20) = invVol * ((d12 - d33)*wSqdh)/24.;
            fullCellResult(10, 21) = invVol * -((d01 + d55)*dSqhw)/24.;
            fullCellResult(10, 22) = invVol * (d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/18.;
            fullCellResult(10, 23) = invVol * ((d12 - d33)*wSqdh)/12.;
            fullCellResult(11, 11) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            fullCellResult(11, 12) = invVol * ((d02 - d44)*hSqdw)/24.;
            fullCellResult(11, 13) = invVol * ((d12 + d33)*wSqdh)/12.;
            fullCellResult(11, 14) = invVol * (d44*dSqhSq - 2*(d33*dSqwSq + d22*hSqwSq))/36.;
            fullCellResult(11, 15) = invVol * -((d02 + d44)*hSqdw)/24.;
            fullCellResult(11, 16) = invVol * ((d12 + d33)*wSqdh)/24.;
            fullCellResult(11, 17) = invVol * (-(d44*dSqhSq) - d33*dSqwSq - d22*hSqwSq)/36.;
            fullCellResult(11, 18) = invVol * -((d02 + d44)*hSqdw)/12.;
            fullCellResult(11, 19) = invVol * ((-d12 + d33)*wSqdh)/24.;
            fullCellResult(11, 20) = invVol * (-2*d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/36.;
            fullCellResult(11, 21) = invVol * ((d02 - d44)*hSqdw)/12.;
            fullCellResult(11, 22) = invVol * ((-d12 + d33)*wSqdh)/12.;
            fullCellResult(11, 23) = invVol * (d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/18.;
            fullCellResult(12, 12) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            fullCellResult(12, 13) = invVol * ((d01 + d55)*dSqhw)/12.;
            fullCellResult(12, 14) = invVol * -((d02 + d44)*hSqdw)/12.;
            fullCellResult(12, 15) = invVol * (-2*d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/18.;
            fullCellResult(12, 16) = invVol * ((d01 - d55)*dSqhw)/12.;
            fullCellResult(12, 17) = invVol * ((-d02 + d44)*hSqdw)/12.;
            fullCellResult(12, 18) = invVol * (-2*d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/36.;
            fullCellResult(12, 19) = invVol * -((d01 + d55)*dSqhw)/12.;
            fullCellResult(12, 20) = invVol * ((-d02 + d44)*hSqdw)/24.;
            fullCellResult(12, 21) = invVol * (d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/18.;
            fullCellResult(12, 22) = invVol * ((-d01 + d55)*dSqhw)/12.;
            fullCellResult(12, 23) = invVol * -((d02 + d44)*hSqdw)/24.;
            fullCellResult(13, 13) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            fullCellResult(13, 14) = invVol * -((d12 + d33)*wSqdh)/12.;
            fullCellResult(13, 15) = invVol * ((-d01 + d55)*dSqhw)/12.;
            fullCellResult(13, 16) = invVol * (-2*d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/18.;
            fullCellResult(13, 17) = invVol * -((d12 + d33)*wSqdh)/24.;
            fullCellResult(13, 18) = invVol * -((d01 + d55)*dSqhw)/12.;
            fullCellResult(13, 19) = invVol * (-2*d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/36.;
            fullCellResult(13, 20) = invVol * ((-d12 + d33)*wSqdh)/24.;
            fullCellResult(13, 21) = invVol * ((d01 - d55)*dSqhw)/12.;
            fullCellResult(13, 22) = invVol * (d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/18.;
            fullCellResult(13, 23) = invVol * ((-d12 + d33)*wSqdh)/12.;
            fullCellResult(14, 14) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            fullCellResult(14, 15) = invVol * ((d02 - d44)*hSqdw)/12.;
            fullCellResult(14, 16) = invVol * -((d12 + d33)*wSqdh)/24.;
            fullCellResult(14, 17) = invVol * (-2*d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/18.;
            fullCellResult(14, 18) = invVol * ((d02 - d44)*hSqdw)/24.;
            fullCellResult(14, 19) = invVol * ((d12 - d33)*wSqdh)/24.;
            fullCellResult(14, 20) = invVol * (-2*d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/36.;
            fullCellResult(14, 21) = invVol * -((d02 + d44)*hSqdw)/24.;
            fullCellResult(14, 22) = invVol * ((d12 - d33)*wSqdh)/12.;
            fullCellResult(14, 23) = invVol * (d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/18.;
            fullCellResult(15, 15) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            fullCellResult(15, 16) = invVol * -((d01 + d55)*dSqhw)/12.;
            fullCellResult(15, 17) = invVol * ((d02 + d44)*hSqdw)/12.;
            fullCellResult(15, 18) = invVol * (d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/18.;
            fullCellResult(15, 19) = invVol * ((d01 - d55)*dSqhw)/12.;
            fullCellResult(15, 20) = invVol * ((d02 + d44)*hSqdw)/24.;
            fullCellResult(15, 21) = invVol * (-2*d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/36.;
            fullCellResult(15, 22) = invVol * ((d01 + d55)*dSqhw)/12.;
            fullCellResult(15, 23) = invVol * ((d02 - d44)*hSqdw)/24.;
            fullCellResult(16, 16) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            fullCellResult(16, 17) = invVol * -((d12 + d33)*wSqdh)/12.;
            fullCellResult(16, 18) = invVol * ((-d01 + d55)*dSqhw)/12.;
            fullCellResult(16, 19) = invVol * (d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/18.;
            fullCellResult(16, 20) = invVol * ((-d12 + d33)*wSqdh)/12.;
            fullCellResult(16, 21) = invVol * ((d01 + d55)*dSqhw)/12.;
            fullCellResult(16, 22) = invVol * (-2*d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/36.;
            fullCellResult(16, 23) = invVol * ((-d12 + d33)*wSqdh)/24.;
            fullCellResult(17, 17) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            fullCellResult(17, 18) = invVol * ((d02 + d44)*hSqdw)/24.;
            fullCellResult(17, 19) = invVol * ((d12 - d33)*wSqdh)/12.;
            fullCellResult(17, 20) = invVol * (d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/18.;
            fullCellResult(17, 21) = invVol * ((-d02 + d44)*hSqdw)/24.;
            fullCellResult(17, 22) = invVol * ((d12 - d33)*wSqdh)/24.;
            fullCellResult(17, 23) = invVol * (-2*d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/36.;
            fullCellResult(18, 18) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            fullCellResult(18, 19) = invVol * ((d01 + d55)*dSqhw)/12.;
            fullCellResult(18, 20) = invVol * ((d02 + d44)*hSqdw)/12.;
            fullCellResult(18, 21) = invVol * (-2*d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/18.;
            fullCellResult(18, 22) = invVol * ((d01 - d55)*dSqhw)/12.;
            fullCellResult(18, 23) = invVol * ((d02 - d44)*hSqdw)/12.;
            fullCellResult(19, 19) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            fullCellResult(19, 20) = invVol * ((d12 + d33)*wSqdh)/12.;
            fullCellResult(19, 21) = invVol * ((-d01 + d55)*dSqhw)/12.;
            fullCellResult(19, 22) = invVol * (-2*d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/18.;
            fullCellResult(19, 23) = invVol * ((d12 + d33)*wSqdh)/24.;
            fullCellResult(20, 20) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            fullCellResult(20, 21) = invVol * ((-d02 + d44)*hSqdw)/12.;
            fullCellResult(20, 22) = invVol * ((d12 + d33)*wSqdh)/24.;
            fullCellResult(20, 23) = invVol * (-2*d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/18.;
            fullCellResult(21, 21) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            fullCellResult(21, 22) = invVol * -((d01 + d55)*dSqhw)/12.;
            fullCellResult(21, 23) = invVol * -((d02 + d44)*hSqdw)/12.;
            fullCellResult(22, 22) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            fullCellResult(22, 23) = invVol * ((d12 + d33)*wSqdh)/12.;
            fullCellResult(23, 23) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;

            m_fullCellIntegralCached = true;
        }

        return (i <= j) ? fullCellResult(i, j) : fullCellResult(j, i);
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 24) && (j < 24));
        return (i <= j) ? result(i, j) : result(j, i);
    }

private:
    const Model &m_model;
    const DType &m_d;
    Vector m_dimensions;
    bool m_fullCellIntegralCached;

    value_type result, fullCellResult;
};

// Integrand computing the averaged (not integrated), grad phi over the element
// Used to build per-element displacement->strain map.
// Average is computed over the non-void portion of the element, not the full
// element.
template<typename _Model>
class MeshlessFEM3D<_Model>::PerElementGradPhi {
public:
    PerElementGradPhi(const Model &model)
        : m_model(model) { clear(); setDimensions(Vector::Zero()); }

    void clear() { result = GradPhis::Zero(); }

    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
        m_fullCellIntegralCached = false;
    }

    // Numerical integration of grad phis over the cell
    // (Must call finalze() passing in the integration volume to make 
    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        // Multiply integrand by indicator function
        if (!m_model.isInside(sample))
            return;

        Real x = ref_sample[0], y = ref_sample[1], z = ref_sample[2];
        Real invW = 1.0 / m_dimensions[0];
        Real invH = 1.0 / m_dimensions[1];
        Real invD = 1.0 / m_dimensions[2];
        Real xWeight = weight / m_dimensions[0];
        Real yWeight = weight / m_dimensions[1];
        Real zWeight = weight / m_dimensions[2];

        result(0, 0) += xWeight * (y - 1) * (1 - z); result(0, 1) += yWeight * (x - 1) * (1 - z); result(0, 2) += zWeight * (x - 1) * (1 - y);
        result(1, 0) += xWeight * (1 - y) * (1 - z); result(1, 1) += yWeight * x * (z - 1);       result(1, 2) += zWeight * x * (y - 1);
        result(2, 0) += xWeight * y * (1 - z);       result(2, 1) += yWeight * x * (1 - z);       result(2, 2) += zWeight * (-x * y);
        result(3, 0) += xWeight * y * (z - 1);       result(3, 1) += yWeight * (1 - x) * (1 - z); result(3, 2) += zWeight * (x - 1) * y;
        result(4, 0) += xWeight * (y - 1) * z;       result(4, 1) += yWeight * (x - 1) * z;       result(4, 2) += zWeight * (1 - x) * (1 - y);
        result(5, 0) += xWeight * (1 - y) * z;       result(5, 1) += yWeight * (-x * z);          result(5, 2) += zWeight * x * (1 - y);
        result(6, 0) += xWeight * y * z;             result(6, 1) += yWeight * x * z;             result(6, 2) += zWeight * x * y;
        result(7, 0) += xWeight * y * z;             result(7, 1) += yWeight * (1 - x) * z;       result(7, 2) += zWeight * (1 - x) * y;
    }

    // Analytic average of grad phis over the full cell
    const GradPhis &fullCellAverage() {
        if (!m_fullCellIntegralCached) {
            Real qInvW = 0.25 / m_dimensions[0];
            Real qInvH = 0.25 / m_dimensions[1];
            Real qInvD = 0.25 / m_dimensions[2];

            fullCellResult(0, 0) = -qInvW; fullCellResult(0, 1) = -qInvH; fullCellResult(0, 2) = -qInvD;
            fullCellResult(1, 0) =  qInvW; fullCellResult(1, 1) = -qInvH; fullCellResult(1, 2) = -qInvD;
            fullCellResult(2, 0) =  qInvW; fullCellResult(2, 1) =  qInvH; fullCellResult(2, 2) = -qInvD;
            fullCellResult(3, 0) = -qInvW; fullCellResult(3, 1) =  qInvH; fullCellResult(3, 2) = -qInvD;
            fullCellResult(4, 0) = -qInvW; fullCellResult(4, 1) = -qInvH; fullCellResult(4, 2) =  qInvD;
            fullCellResult(5, 0) =  qInvW; fullCellResult(5, 1) = -qInvH; fullCellResult(5, 2) =  qInvD;
            fullCellResult(6, 0) =  qInvW; fullCellResult(6, 1) =  qInvH; fullCellResult(6, 2) =  qInvD;
            fullCellResult(7, 0) = -qInvW; fullCellResult(7, 1) =  qInvH; fullCellResult(7, 2) =  qInvD;

            m_fullCellIntegralCached = true;
        }

        return fullCellResult;
    }

    // Convert the integraded quantitites into averaged quantities by dividing
    // by the integration domain volume. This is elementOverlap * full cell
    // volume.
    // Note: this doesn't need to be done for the full cell expression since it
    // is already an average
    void finalize(Real elementOverlap = 1.0) {
        // We accumulated the integral, not the average--divide by the
        // integration domain.
        result /= elementOverlap * m_dimensions[0] * m_dimensions[1];
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 8) && (j < 8));
        return result(i, j);
    }

    // Allow type cast to GradPhi
    operator const GradPhis &() const { return result; }

private:
    const Model &m_model;
    GradPhis result, fullCellResult;
    bool m_fullCellIntegralCached;
    Vector m_dimensions;
    Real m_volume;
};

////////////////////////////////////////////////////////////////////////////////
/*! Compute and assemble each 24x24 per-element stiffness matrix into the full
//  3N x 3N stiffness matrix.
//  @param[out] K   Stiffness matrix in sparse triplet format.
*///////////////////////////////////////////////////////////////////////////////
template<typename _Model>
void MeshlessFEM3D<_Model>::m_assembleStiffnessMatrix(TMatrix &K) {
    K.m = K.n = 3 * m_elementGrid.numNodes();
    PerElementOrthotropicStiffnessDensity stiff(m_d, m_model);
    CornerVec cornerIndices;

    K.clear();
    K.reserve(24 * 24 * m_elementGrid.numElements());

    for (size_t e = 0; e < m_elementGrid.numElements(); ++e) {
         BBox b = m_elementGrid.elementBoundingBox(e);
         m_elementGrid.elementCorners(e, cornerIndices);
         stiff.setDimensions(b.dimensions());

         if (m_exactFullElements && m_elementGrid.elementIsFull(e)) {
             for (size_t i = 0; i < 8; ++i) {
                 size_t vi = cornerIndices[i];
                 for (size_t j = 0; j < 8; ++j) {
                     size_t vj = cornerIndices[j];
                     // xx, xy, xz, yx, yy, yz, zx, zy, zz
                     K.addNZ(3 * vi    , 3 * vj    , stiff.fullCellIntegral(3 * i    , 3 * j    ));
                     K.addNZ(3 * vi    , 3 * vj + 1, stiff.fullCellIntegral(3 * i    , 3 * j + 1));
                     K.addNZ(3 * vi    , 3 * vj + 2, stiff.fullCellIntegral(3 * i    , 3 * j + 2));
                     K.addNZ(3 * vi + 1, 3 * vj    , stiff.fullCellIntegral(3 * i + 1, 3 * j    ));
                     K.addNZ(3 * vi + 1, 3 * vj + 1, stiff.fullCellIntegral(3 * i + 1, 3 * j + 1));
                     K.addNZ(3 * vi + 1, 3 * vj + 2, stiff.fullCellIntegral(3 * i + 1, 3 * j + 2));
                     K.addNZ(3 * vi + 2, 3 * vj    , stiff.fullCellIntegral(3 * i + 2, 3 * j    ));
                     K.addNZ(3 * vi + 2, 3 * vj + 1, stiff.fullCellIntegral(3 * i + 2, 3 * j + 1));
                     K.addNZ(3 * vi + 2, 3 * vj + 2, stiff.fullCellIntegral(3 * i + 2, 3 * j + 2));
                 }
             }
         }
         else {
             stiff.clear();
             m_quadrature.integrate(stiff, b);
             for (size_t i = 0; i < 8; ++i) {
                 size_t vi = cornerIndices[i];
                 for (size_t j = 0; j < 8; ++j) {
                     size_t vj = cornerIndices[j];
                     // xx, xy, xz, yx, yy, yz, zx, zy, zz
                     K.addNZ(3 * vi    , 3 * vj    , stiff(3 * i    , 3 * j    ));
                     K.addNZ(3 * vi    , 3 * vj + 1, stiff(3 * i    , 3 * j + 1));
                     K.addNZ(3 * vi    , 3 * vj + 2, stiff(3 * i    , 3 * j + 2));
                     K.addNZ(3 * vi + 1, 3 * vj    , stiff(3 * i + 1, 3 * j    ));
                     K.addNZ(3 * vi + 1, 3 * vj + 1, stiff(3 * i + 1, 3 * j + 1));
                     K.addNZ(3 * vi + 1, 3 * vj + 2, stiff(3 * i + 1, 3 * j + 2));
                     K.addNZ(3 * vi + 2, 3 * vj    , stiff(3 * i + 2, 3 * j    ));
                     K.addNZ(3 * vi + 2, 3 * vj + 1, stiff(3 * i + 2, 3 * j + 1));
                     K.addNZ(3 * vi + 2, 3 * vj + 2, stiff(3 * i + 2, 3 * j + 2));
                 }
             }
         }
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix whose rows span the space of translations.
//  This matrix can also compute the total force of a load.
//  @param[out] T   Translation mode matrix in sparse triplet format.
*///////////////////////////////////////////////////////////////////////////////
template<typename _Model>
void MeshlessFEM3D<_Model>::m_assembleTranslationMatrix(TMatrix &T) {
    size_t nNodes = m_elementGrid.numNodes();

    T.m = 3;
    T.n = 3 * nNodes;

    T.clear();
    T.reserve(3 * nNodes);
    
    for (size_t k = 0; k < nNodes; ++k) {
        T.addNZ(0, 3 * k    , 1.0);
        T.addNZ(1, 3 * k + 1, 1.0);
        T.addNZ(2, 3 * k + 2, 1.0);
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix whose rows span the space of rigid motion.
//  This matrix can also compute the total force/net torque of a load.
//  @param[out] R   Rigid mode matrix in sparse triplet format.
*///////////////////////////////////////////////////////////////////////////////
template<typename _Model>
void MeshlessFEM3D<_Model>::m_assembleRigidModeMatrix(TMatrix &R) {
    size_t nNodes = m_elementGrid.numNodes();
    R.reserve((3 + 6) * nNodes);
    m_assembleTranslationMatrix(R);

    // We're appending 3 after the translation modes
    assert(R.m == 3);
    R.m += 3;
    
    for (size_t k = 0; k < nNodes; ++k) {
        Vector x = m_elementGrid.nodePosition(k);
        // x axis infinitesimal rotation (0, -z, y)
        R.addNZ(3, 3 * k + 1, -x[2]);
        R.addNZ(3, 3 * k + 2,  x[1]);
        // y axis infinitesimal rotation (z, 0, -x)
        R.addNZ(4, 3 * k    ,  x[2]);
        R.addNZ(4, 3 * k + 2, -x[0]);
        // z axis infinitesimal rotation (-y, x, 0)
        R.addNZ(5, 3 * k    , -x[1]);
        R.addNZ(5, 3 * k + 1,  x[0]);
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Fill in m_elementData with the quantities needed to evaluate (averaged)
//  per-element strain, stress, and energy from displacement.
*///////////////////////////////////////////////////////////////////////////////
template<typename _Model>
void MeshlessFEM3D<_Model>::m_computePerElementDisplacementStrainMap() {
    PerElementGradPhi gradPhi(m_model);

    size_t numElements = m_elementGrid.numElements();
    if (m_elementData.size() != numElements)
        m_elementData.resize(numElements);

    for (size_t e = 0; e < numElements; ++e) {
        BBox_t b = m_elementGrid.elementBoundingBox(e);
        gradPhi.setDimensions(b.dimensions());
        m_elementData[e].setVolume(b.volume());
        if (m_exactFullElements && (m_elementGrid.elementIsFull(e))) {
            m_elementData[e].setGradPhis(gradPhi.fullCellAverage());
        }
        else {
            gradPhi.clear();
            m_quadrature.integrate(gradPhi, b);
            gradPhi.finalize(m_elementGrid.elementOverlap(e));
            m_elementData[e].setGradPhis(gradPhi);
        }
    }

    m_displacementStrainCached = true;
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix mapping a flattened per-node displacement vector to a 
//  flattened per-element (non-engineering) strain tensor. The strain tensor for
//  element e is computed by rows 6 * e + [0..5].
//  @param[out]  B      displacement->strain matrix in sparse triplet format
*///////////////////////////////////////////////////////////////////////////////
template<typename _Model>
void MeshlessFEM3D<_Model>::m_assembleBMatrix(TMatrix &B) {
    if (!m_displacementStrainCached)
        m_computePerElementDisplacementStrainMap();

    B.m = 6 * m_elementGrid.numElements();
    B.n = 3 * m_elementGrid.numNodes();

    B.clear();
    // 3 normal strain rows have  8 nonzeros
    // 3  shear strain rows have 16 nonzeros
    B.reserve(72 * m_elementGrid.numElements());

    CornerVec cornerIndices;
    for (size_t e = 0; e < m_elementGrid.numElements(); ++e) {
        const ElementData &data = m_elementData[e];
        m_elementGrid.elementCorners(e, cornerIndices);
        for (size_t c = 0; c < 8; ++c) {
            size_t vtx = cornerIndices[c];
            // Rows of B are given by Voigt flattening:
            // First normal stresses: e_xx, e_yy, e_zz...
            B.addNZ(6 * e    , 3 * vtx    , data.gradPhi(c, 0));
            B.addNZ(6 * e + 1, 3 * vtx + 1, data.gradPhi(c, 1));
            B.addNZ(6 * e + 2, 3 * vtx + 2, data.gradPhi(c, 2));
            // then shear stresses: e_yz, e_xz, e_xy
            B.addNZ(6 * e + 3, 3 * vtx + 1, 0.5 * data.gradPhi(c, 2));
            B.addNZ(6 * e + 3, 3 * vtx + 2, 0.5 * data.gradPhi(c, 1));
            B.addNZ(6 * e + 4, 3 * vtx    , 0.5 * data.gradPhi(c, 2));
            B.addNZ(6 * e + 4, 3 * vtx + 2, 0.5 * data.gradPhi(c, 0));
            B.addNZ(6 * e + 5, 3 * vtx    , 0.5 * data.gradPhi(c, 1));
            B.addNZ(6 * e + 5, 3 * vtx + 1, 0.5 * data.gradPhi(c, 0));
        }
    }
}

template<typename _Model>
void MeshlessFEM3D<_Model>::m_assembleVDMatrix(TMatrix &VD) {
    assert(false); // Unimplemented
    VD.m = 6 * m_elementGrid.numElements();
    VD.n = 6 * m_elementGrid.numElements();

    VD.clear();
    // VD.reserve();

    Real d00 = m_d[0], d01 = m_d[1], d02 = m_d[ 2], d03 = m_d[ 3], d04 = m_d[ 4], d05 = m_d[ 5],
                       d11 = m_d[6], d12 = m_d[ 7], d13 = m_d[ 8], d14 = m_d[ 9], d15 = m_d[10],
                                     d22 = m_d[11], d23 = m_d[12], d24 = m_d[13], d25 = m_d[14],
                                                    d33 = m_d[15], d34 = m_d[16], d35 = m_d[17],
                                                                   d44 = m_d[18], d45 = m_d[19],
                                                                                  d55 = m_d[20];
    // for (size_t e = 0; e < m_elementGrid.numElements(); ++e) {
    //     Real vol = m_elementData[e].volume();
    //     VD.addNZ(6 * e + 0, 6 * e + 0
    // }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix for the equations enforcing periodic displacement
//  boundary conditions on the computational grid.
//  @param[out] P   periodic constraint matrix in sparse triplet format 
*///////////////////////////////////////////////////////////////////////////////
template<typename _Model>
void MeshlessFEM3D<_Model>::m_assemblePeriodicConstraints(TMatrix &P) const {
    std::vector<std::pair<size_t, size_t> > pairs, indep;
    m_elementGrid.periodicBoundaryPairs(pairs);
    // Pairs found from the grid have redundancies (cyclic identifications). We
    // must break these to get linearly independent constraints.
    spanningForest(pairs, indep);

    P.clear();
    P.m = indep.size() * 3;
    P.n = m_elementGrid.numNodes() * 3;
    P.reserve(indep.size() * 6);

    for (size_t i = 0; i < indep.size(); ++i) {
        P.addNZ(3 * i    , 3 * indep[i].first     ,  1.0);
        P.addNZ(3 * i    , 3 * indep[i].second    , -1.0);
        P.addNZ(3 * i + 1, 3 * indep[i].first  + 1,  1.0);
        P.addNZ(3 * i + 1, 3 * indep[i].second + 1, -1.0);
        P.addNZ(3 * i + 2, 3 * indep[i].first  + 2,  1.0);
        P.addNZ(3 * i + 2, 3 * indep[i].second + 2, -1.0);
    }
}

template<typename Vector_>
struct VectorSlicer {
    typedef typename Vector_::value_type     Scalar;

    VectorSlicer(Vector_ &v) : vec(v) { }
    size_t rows() const { return indices.size(); }
    void  clear()       { indices.clear(); }
    void appendIndex(size_t i) {
        assert(i < vec.size());
        indices.push_back(i);
    }

    Scalar &operator[](size_t i) {
        assert(i < indices.size());
        size_t ii = indices[i];
        assert(ii < vec.size());
        return vec[ii];
    }

    Scalar operator[](size_t i) const {
        assert(i < indices.size());
        size_t ii = indices[i];
        assert(ii < vec.size());
        return vec[ii];
    }
    
    std::vector<size_t> indices;
    Vector_ &vec;
};

template<typename _Model>
void MeshlessFEM3D<_Model>::
periodicHomogenize(Timer *timer, MSHWriter *mshWriter) {
    std::cout << "Running homogenization on "
              << m_elementGrid.slices() << " x "
              << m_elementGrid.rows() << " x "
              << m_elementGrid.cols() << " grid with "
              << m_elementGrid.numElements()  << " elements and "
              << m_elementGrid.numNodes()  << " nodes (qp = "
              << m_quadrature.numPoints() << ")" << std::endl;
    TMatrix K, T, P;

    if (timer) timer->start("Assemble Stiffness");
    m_assembleStiffnessMatrix(K);
    if (timer) timer->stop("Assemble Stiffness");
    if (timer) timer->start("Assemble T, P");
    m_assembleTranslationMatrix(T);
    m_assemblePeriodicConstraints(P);
    if (timer) timer->stop("Assemble T, P");

    if (timer) timer->start("Assemble C");
    // Build constrained system with lagrange multipliers
    // [ K T' P' ] [u        ]   [ f ]
    // [ T       ] [lambda_t ] = [ 0 ]
    // [ P       ] [lambda_p ]   [ 0 ]
    //  --- C ---   -- u_l --    -rhs-
    TMatrix &C = K; // update in place
    // Append boolean arguments:        pad   transpose
    C.append(T, TMatrix::APPEND_BELOW, false, false);
    C.append(P, TMatrix::APPEND_BELOW, false, false);
    C.append(T, TMatrix::APPEND_RIGHT,  true,  true);
    C.append(P, TMatrix::APPEND_RIGHT,  true,  true);
    if (timer) timer->stop("Assemble C");
    
    if (timer) timer->start("To SuiteSparse");
    SuiteSparseMatrix ssC(C);
    if (timer) timer->stop("To SuiteSparse");
    if (timer) timer->start("Factorize");
    UmfpackFactorizer Cfactors(ssC);
    if (timer) timer->stop("Factorize");

    // Solve cell problems for fluctuation displacments "w_ij"
    std::vector<std::vector<double> > w_ij(6);
    m_computePerElementDisplacementStrainMap();
    assert(m_elementData.size() == m_elementGrid.numElements());

    if (timer) timer->startSection("Cell Problems");
    FlattenedRank2Tensor e_ij, s_ij;
    for (size_t i = 0; i < 6; ++i) {
        // Use constant engineering test strain so that B' * V * D computes
        // nodal load.
        e_ij = FlattenedRank2Tensor::Zero();
        e_ij[i] = (i < 3) ? 1 : 2;
        strainToStress(e_ij, m_d, s_ij);
        std::vector<double> rhs(C.n, 0.0);

        // Apply B'V to each the constant stress tensor, accumulating into rhs
        VectorSlicer<std::vector<double> > loadSlicer(rhs);
        for (size_t e = 0; e < m_elementGrid.numElements(); ++e) {
            CornerVec cornerIndices;
            m_elementGrid.elementCorners(e, cornerIndices);

            // Index into load vector based on the corner indices
            loadSlicer.clear();
            for (size_t c = 0; c < cornerIndices.RowsAtCompileTime; ++c) {
                loadSlicer.appendIndex(3 * cornerIndices[c]    );
                loadSlicer.appendIndex(3 * cornerIndices[c] + 1);
                loadSlicer.appendIndex(3 * cornerIndices[c] + 2);
            }

            m_elementData[e].applyBt_V(s_ij, loadSlicer); 
        }
        for (size_t i = 0; i < rhs.size(); ++i) {
            rhs[i] = -rhs[i];
            if (i >= 3 * m_elementGrid.numNodes())
                assert(rhs[i] == 0.0);
        }

        if (timer) timer->start("Solve");
        Cfactors.solve(rhs, w_ij[i]);
        if (timer) timer->stop("Solve");

        // Trim off the lagrange multipliers.
        w_ij[i].resize(3 * m_elementGrid.numNodes());
    }
    if (timer) timer->stopSection("Cell Problems");

    if (mshWriter) {
        for (size_t i = 0; i < 6; ++i) {
            std::string name("w_ij ");
            name += std::to_string(i);
            VField displ(w_ij[i]);
            mshWriter->addField(name, displ, MSHWriter::PER_NODE);
        }
    }
}

////////////////////////////////////////////////////////////////////////////////
// Template instantiations
////////////////////////////////////////////////////////////////////////////////
#include "GlobalTypes.hh"
template class MeshlessFEM3D<LevelSet_t>;
