////////////////////////////////////////////////////////////////////////////////
// MeshlessFEM3D.cc
////////////////////////////////////////////////////////////////////////////////
/*! @file
//		Implmeents a 3D mesh-free finite elmeent discretization of linear
//		elasticity." Mesh-free" means the surface/volume representation only
//      needs to support point inclusion tests.
*/ 
//  Author:  Julian Panetta (jpanetta), julian.panetta@gmail.com
//  Company:  New York University
//  Created:  04/30/2014 00:07:12
////////////////////////////////////////////////////////////////////////////////
#include "MeshlessFEM3D.hh"

// Integrand for the per-element stiffness matrix integral for an orthotropic
// material. As an optimization for symmetry, only the upper triangle terms are
// computed, and accesses to the lower triangle are redirected to the upper
// triangle.
template<typename _Model>
class MeshlessFEM2D<_Model>::PerElementOrthotropicStiffnessDensity
{
public:
    typedef Eigen::Matrix<Real, 24, 24> value_type;

    // D: (d00, d01, d10, d11, d22)
    PerElementOrthotropicStiffnessDensity(const DType &d, const Model &model)
        : m_model(model), m_d(d) { clear(); setDimensions(Vector::Zero()); }

    void clear() { result = value_type::Zero(); }

    // Set element size
    void setDimensions(const Vector &dims) {
        m_dimensions = dims;
        m_fullCellIntegralCached = false;
    }

    // Called once per quadrature sample to perform the integration.
    // @param[in]  sample     quadrature sample point in element
    // @param[in]  ref_sample sample coordinates in reference cube ([0, 1]^3)
    // @param[in]  weight     "dV" for the sample--includes jacobian determinant
    void accumulate(const Vector &sample, const Vector &ref_sample, Real weight)
    {
        if (!m_model.isInside(sample))
            return;
        Real x = ref_sample[0], y = ref_sample[1], Real z = ref_sample[1];

        // The following formulas are automatically generated by
        // Derivations/3DStiffness.nb

        // Unpack elasticity tensor
        // .5 scaling for off-diagonals  is to account for engineering stress :
        // engineering strain double-counting the off-diagonals.
        Real d00 = m_d[0], d01 = 0.5 * m_d[1], d02 = 0.5 * m_d[ 2], // d03 = 0.5 * m_d[ 3], d04 = .5 * m_d[ 4], d05 = .5 * m_d[ 5],
                           d11 =       m_d[6], d12 = 0.5 * m_d[ 7], // d13 = 0.5 * m_d[ 8], d14 = .5 * m_d[ 9], d15 = .5 * m_d[ 10],
                                               d22 =       m_d[11], // d23 = 0.5 * m_d[12], d24 = .5 * m_d[13], d25 = .5 * m_d[14],
                                                                    d33 =       m_d[15], // d34 = .5 * m_d[16], d35 = .5 * m_d[17],
                                                                                         d44 =      m_d[18], // d45 = .5 * m_d[19],
                                                                                                             d55 =      m_d[20];

        // Entries in B
        Real dxp0 = ((y - 1) * (1 - z))/m_dimensions[0];
        Real dxp1 = ((1 - y) * (1 - z))/m_dimensions[0];
        Real dxp2 =       (y * (1 - z))/m_dimensions[0];
        Real dxp3 =      ((y * (z - 1))/m_dimensions[0];
        Real dxp4 =       ((y - 1) * z)/m_dimensions[0];
        Real dxp5 =       ((1 - y) * z)/m_dimensions[0];
        Real dxp6 =             (y * z)/m_dimensions[0];
        Real dxp7 =            -(y * z)/m_dimensions[0];
        Real dyp0 = ((x - 1) * (1 - z))/m_dimensions[1];
        Real dyp1 =       (x * (z - 1))/m_dimensions[1];
        Real dyp2 =       (x * (1 - z))/m_dimensions[1];
        Real dyp3 = ((1 - x) * (1 - z))/m_dimensions[1];
        Real dyp4 =      (((x - 1) * z)/m_dimensions[1];
        Real dyp5 =            -(x * z)/m_dimensions[1];
        Real dyp6 =             (x * z)/m_dimensions[1];
        Real dyp7 =       ((1 - x) * z)/m_dimensions[1];
        Real dzp0 = ((x - 1) * (1 - y))/m_dimensions[2];
        Real dzp1 =       (x * (y - 1))/m_dimensions[2];
        Real dzp2 =             (x * y)/m_dimensions[2];
        Real dzp3 =       ((x - 1) * y)/m_dimensions[2];
        Real dzp4 = ((1 - x) * (1 - y))/m_dimensions[2];
        Real dzp5 =       (x * (1 - y))/m_dimensions[2];
        Real dzp6 =             (x * y)/m_dimensions[2];
        Real dzp7 =       ((1 - x) * y)/m_dimensions[2];

        KOrtho(0, 0) += weight * (d00*(dxp0*dxp0) + d55*(dyp0*dyp0) + d44*(dzp0*dzp0));
        KOrtho(0, 1) += weight * ((d01 + d55)*dxp0*dyp0);
        KOrtho(0, 2) += weight * ((d02 + d44)*dxp0*dzp0);
        KOrtho(0, 3) += weight * (d00*dxp0*dxp1 + d55*dyp0*dyp1 + d44*dzp0*dzp1);
        KOrtho(0, 4) += weight * (d55*dxp1*dyp0 + d01*dxp0*dyp1);
        KOrtho(0, 5) += weight * (d44*dxp1*dzp0 + d02*dxp0*dzp1);
        KOrtho(0, 6) += weight * (d00*dxp0*dxp2 + d55*dyp0*dyp2 + d44*dzp0*dzp2);
        KOrtho(0, 7) += weight * (d55*dxp2*dyp0 + d01*dxp0*dyp2);
        KOrtho(0, 8) += weight * (d44*dxp2*dzp0 + d02*dxp0*dzp2);
        KOrtho(0, 9) += weight * (d00*dxp0*dxp3 + d55*dyp0*dyp3 + d44*dzp0*dzp3);
        KOrtho(0, 10) += weight * (d55*dxp3*dyp0 + d01*dxp0*dyp3);
        KOrtho(0, 11) += weight * (d44*dxp3*dzp0 + d02*dxp0*dzp3);
        KOrtho(0, 12) += weight * (d00*dxp0*dxp4 + d55*dyp0*dyp4 + d44*dzp0*dzp4);
        KOrtho(0, 13) += weight * (d55*dxp4*dyp0 + d01*dxp0*dyp4);
        KOrtho(0, 14) += weight * (d44*dxp4*dzp0 + d02*dxp0*dzp4);
        KOrtho(0, 15) += weight * (d00*dxp0*dxp5 + d55*dyp0*dyp5 + d44*dzp0*dzp5);
        KOrtho(0, 16) += weight * (d55*dxp5*dyp0 + d01*dxp0*dyp5);
        KOrtho(0, 17) += weight * (d44*dxp5*dzp0 + d02*dxp0*dzp5);
        KOrtho(0, 18) += weight * (d00*dxp0*dxp6 + d55*dyp0*dyp6 + d44*dzp0*dzp6);
        KOrtho(0, 19) += weight * (d55*dxp6*dyp0 + d01*dxp0*dyp6);
        KOrtho(0, 20) += weight * (d44*dxp6*dzp0 + d02*dxp0*dzp6);
        KOrtho(0, 21) += weight * (d00*dxp0*dxp7 + d55*dyp0*dyp7 + d44*dzp0*dzp7);
        KOrtho(0, 22) += weight * (d55*dxp7*dyp0 + d01*dxp0*dyp7);
        KOrtho(0, 23) += weight * (d44*dxp7*dzp0 + d02*dxp0*dzp7);
        KOrtho(1, 1) += weight * (d55*(dxp0*dxp0) + d11*(dyp0*dyp0) + d33*(dzp0*dzp0));
        KOrtho(1, 2) += weight * ((d12 + d33)*dyp0*dzp0);
        KOrtho(1, 3) += weight * (d01*dxp1*dyp0 + d55*dxp0*dyp1);
        KOrtho(1, 4) += weight * (d55*dxp0*dxp1 + d11*dyp0*dyp1 + d33*dzp0*dzp1);
        KOrtho(1, 5) += weight * (d33*dyp1*dzp0 + d12*dyp0*dzp1);
        KOrtho(1, 6) += weight * (d01*dxp2*dyp0 + d55*dxp0*dyp2);
        KOrtho(1, 7) += weight * (d55*dxp0*dxp2 + d11*dyp0*dyp2 + d33*dzp0*dzp2);
        KOrtho(1, 8) += weight * (d33*dyp2*dzp0 + d12*dyp0*dzp2);
        KOrtho(1, 9) += weight * (d01*dxp3*dyp0 + d55*dxp0*dyp3);
        KOrtho(1, 10) += weight * (d55*dxp0*dxp3 + d11*dyp0*dyp3 + d33*dzp0*dzp3);
        KOrtho(1, 11) += weight * (d33*dyp3*dzp0 + d12*dyp0*dzp3);
        KOrtho(1, 12) += weight * (d01*dxp4*dyp0 + d55*dxp0*dyp4);
        KOrtho(1, 13) += weight * (d55*dxp0*dxp4 + d11*dyp0*dyp4 + d33*dzp0*dzp4);
        KOrtho(1, 14) += weight * (d33*dyp4*dzp0 + d12*dyp0*dzp4);
        KOrtho(1, 15) += weight * (d01*dxp5*dyp0 + d55*dxp0*dyp5);
        KOrtho(1, 16) += weight * (d55*dxp0*dxp5 + d11*dyp0*dyp5 + d33*dzp0*dzp5);
        KOrtho(1, 17) += weight * (d33*dyp5*dzp0 + d12*dyp0*dzp5);
        KOrtho(1, 18) += weight * (d01*dxp6*dyp0 + d55*dxp0*dyp6);
        KOrtho(1, 19) += weight * (d55*dxp0*dxp6 + d11*dyp0*dyp6 + d33*dzp0*dzp6);
        KOrtho(1, 20) += weight * (d33*dyp6*dzp0 + d12*dyp0*dzp6);
        KOrtho(1, 21) += weight * (d01*dxp7*dyp0 + d55*dxp0*dyp7);
        KOrtho(1, 22) += weight * (d55*dxp0*dxp7 + d11*dyp0*dyp7 + d33*dzp0*dzp7);
        KOrtho(1, 23) += weight * (d33*dyp7*dzp0 + d12*dyp0*dzp7);
        KOrtho(2, 2) += weight * (d44*(dxp0*dxp0) + d33*(dyp0*dyp0) + d22*(dzp0*dzp0));
        KOrtho(2, 3) += weight * (d02*dxp1*dzp0 + d44*dxp0*dzp1);
        KOrtho(2, 4) += weight * (d12*dyp1*dzp0 + d33*dyp0*dzp1);
        KOrtho(2, 5) += weight * (d44*dxp0*dxp1 + d33*dyp0*dyp1 + d22*dzp0*dzp1);
        KOrtho(2, 6) += weight * (d02*dxp2*dzp0 + d44*dxp0*dzp2);
        KOrtho(2, 7) += weight * (d12*dyp2*dzp0 + d33*dyp0*dzp2);
        KOrtho(2, 8) += weight * (d44*dxp0*dxp2 + d33*dyp0*dyp2 + d22*dzp0*dzp2);
        KOrtho(2, 9) += weight * (d02*dxp3*dzp0 + d44*dxp0*dzp3);
        KOrtho(2, 10) += weight * (d12*dyp3*dzp0 + d33*dyp0*dzp3);
        KOrtho(2, 11) += weight * (d44*dxp0*dxp3 + d33*dyp0*dyp3 + d22*dzp0*dzp3);
        KOrtho(2, 12) += weight * (d02*dxp4*dzp0 + d44*dxp0*dzp4);
        KOrtho(2, 13) += weight * (d12*dyp4*dzp0 + d33*dyp0*dzp4);
        KOrtho(2, 14) += weight * (d44*dxp0*dxp4 + d33*dyp0*dyp4 + d22*dzp0*dzp4);
        KOrtho(2, 15) += weight * (d02*dxp5*dzp0 + d44*dxp0*dzp5);
        KOrtho(2, 16) += weight * (d12*dyp5*dzp0 + d33*dyp0*dzp5);
        KOrtho(2, 17) += weight * (d44*dxp0*dxp5 + d33*dyp0*dyp5 + d22*dzp0*dzp5);
        KOrtho(2, 18) += weight * (d02*dxp6*dzp0 + d44*dxp0*dzp6);
        KOrtho(2, 19) += weight * (d12*dyp6*dzp0 + d33*dyp0*dzp6);
        KOrtho(2, 20) += weight * (d44*dxp0*dxp6 + d33*dyp0*dyp6 + d22*dzp0*dzp6);
        KOrtho(2, 21) += weight * (d02*dxp7*dzp0 + d44*dxp0*dzp7);
        KOrtho(2, 22) += weight * (d12*dyp7*dzp0 + d33*dyp0*dzp7);
        KOrtho(2, 23) += weight * (d44*dxp0*dxp7 + d33*dyp0*dyp7 + d22*dzp0*dzp7);
        KOrtho(3, 3) += weight * (d00*(dxp1*dxp1) + d55*(dyp1*dyp1) + d44*(dzp1*dzp1));
        KOrtho(3, 4) += weight * ((d01 + d55)*dxp1*dyp1);
        KOrtho(3, 5) += weight * ((d02 + d44)*dxp1*dzp1);
        KOrtho(3, 6) += weight * (d00*dxp1*dxp2 + d55*dyp1*dyp2 + d44*dzp1*dzp2);
        KOrtho(3, 7) += weight * (d55*dxp2*dyp1 + d01*dxp1*dyp2);
        KOrtho(3, 8) += weight * (d44*dxp2*dzp1 + d02*dxp1*dzp2);
        KOrtho(3, 9) += weight * (d00*dxp1*dxp3 + d55*dyp1*dyp3 + d44*dzp1*dzp3);
        KOrtho(3, 10) += weight * (d55*dxp3*dyp1 + d01*dxp1*dyp3);
        KOrtho(3, 11) += weight * (d44*dxp3*dzp1 + d02*dxp1*dzp3);
        KOrtho(3, 12) += weight * (d00*dxp1*dxp4 + d55*dyp1*dyp4 + d44*dzp1*dzp4);
        KOrtho(3, 13) += weight * (d55*dxp4*dyp1 + d01*dxp1*dyp4);
        KOrtho(3, 14) += weight * (d44*dxp4*dzp1 + d02*dxp1*dzp4);
        KOrtho(3, 15) += weight * (d00*dxp1*dxp5 + d55*dyp1*dyp5 + d44*dzp1*dzp5);
        KOrtho(3, 16) += weight * (d55*dxp5*dyp1 + d01*dxp1*dyp5);
        KOrtho(3, 17) += weight * (d44*dxp5*dzp1 + d02*dxp1*dzp5);
        KOrtho(3, 18) += weight * (d00*dxp1*dxp6 + d55*dyp1*dyp6 + d44*dzp1*dzp6);
        KOrtho(3, 19) += weight * (d55*dxp6*dyp1 + d01*dxp1*dyp6);
        KOrtho(3, 20) += weight * (d44*dxp6*dzp1 + d02*dxp1*dzp6);
        KOrtho(3, 21) += weight * (d00*dxp1*dxp7 + d55*dyp1*dyp7 + d44*dzp1*dzp7);
        KOrtho(3, 22) += weight * (d55*dxp7*dyp1 + d01*dxp1*dyp7);
        KOrtho(3, 23) += weight * (d44*dxp7*dzp1 + d02*dxp1*dzp7);
        KOrtho(4, 4) += weight * (d55*(dxp1*dxp1) + d11*(dyp1*dyp1) + d33*(dzp1*dzp1));
        KOrtho(4, 5) += weight * ((d12 + d33)*dyp1*dzp1);
        KOrtho(4, 6) += weight * (d01*dxp2*dyp1 + d55*dxp1*dyp2);
        KOrtho(4, 7) += weight * (d55*dxp1*dxp2 + d11*dyp1*dyp2 + d33*dzp1*dzp2);
        KOrtho(4, 8) += weight * (d33*dyp2*dzp1 + d12*dyp1*dzp2);
        KOrtho(4, 9) += weight * (d01*dxp3*dyp1 + d55*dxp1*dyp3);
        KOrtho(4, 10) += weight * (d55*dxp1*dxp3 + d11*dyp1*dyp3 + d33*dzp1*dzp3);
        KOrtho(4, 11) += weight * (d33*dyp3*dzp1 + d12*dyp1*dzp3);
        KOrtho(4, 12) += weight * (d01*dxp4*dyp1 + d55*dxp1*dyp4);
        KOrtho(4, 13) += weight * (d55*dxp1*dxp4 + d11*dyp1*dyp4 + d33*dzp1*dzp4);
        KOrtho(4, 14) += weight * (d33*dyp4*dzp1 + d12*dyp1*dzp4);
        KOrtho(4, 15) += weight * (d01*dxp5*dyp1 + d55*dxp1*dyp5);
        KOrtho(4, 16) += weight * (d55*dxp1*dxp5 + d11*dyp1*dyp5 + d33*dzp1*dzp5);
        KOrtho(4, 17) += weight * (d33*dyp5*dzp1 + d12*dyp1*dzp5);
        KOrtho(4, 18) += weight * (d01*dxp6*dyp1 + d55*dxp1*dyp6);
        KOrtho(4, 19) += weight * (d55*dxp1*dxp6 + d11*dyp1*dyp6 + d33*dzp1*dzp6);
        KOrtho(4, 20) += weight * (d33*dyp6*dzp1 + d12*dyp1*dzp6);
        KOrtho(4, 21) += weight * (d01*dxp7*dyp1 + d55*dxp1*dyp7);
        KOrtho(4, 22) += weight * (d55*dxp1*dxp7 + d11*dyp1*dyp7 + d33*dzp1*dzp7);
        KOrtho(4, 23) += weight * (d33*dyp7*dzp1 + d12*dyp1*dzp7);
        KOrtho(5, 5) += weight * (d44*(dxp1*dxp1) + d33*(dyp1*dyp1) + d22*(dzp1*dzp1));
        KOrtho(5, 6) += weight * (d02*dxp2*dzp1 + d44*dxp1*dzp2);
        KOrtho(5, 7) += weight * (d12*dyp2*dzp1 + d33*dyp1*dzp2);
        KOrtho(5, 8) += weight * (d44*dxp1*dxp2 + d33*dyp1*dyp2 + d22*dzp1*dzp2);
        KOrtho(5, 9) += weight * (d02*dxp3*dzp1 + d44*dxp1*dzp3);
        KOrtho(5, 10) += weight * (d12*dyp3*dzp1 + d33*dyp1*dzp3);
        KOrtho(5, 11) += weight * (d44*dxp1*dxp3 + d33*dyp1*dyp3 + d22*dzp1*dzp3);
        KOrtho(5, 12) += weight * (d02*dxp4*dzp1 + d44*dxp1*dzp4);
        KOrtho(5, 13) += weight * (d12*dyp4*dzp1 + d33*dyp1*dzp4);
        KOrtho(5, 14) += weight * (d44*dxp1*dxp4 + d33*dyp1*dyp4 + d22*dzp1*dzp4);
        KOrtho(5, 15) += weight * (d02*dxp5*dzp1 + d44*dxp1*dzp5);
        KOrtho(5, 16) += weight * (d12*dyp5*dzp1 + d33*dyp1*dzp5);
        KOrtho(5, 17) += weight * (d44*dxp1*dxp5 + d33*dyp1*dyp5 + d22*dzp1*dzp5);
        KOrtho(5, 18) += weight * (d02*dxp6*dzp1 + d44*dxp1*dzp6);
        KOrtho(5, 19) += weight * (d12*dyp6*dzp1 + d33*dyp1*dzp6);
        KOrtho(5, 20) += weight * (d44*dxp1*dxp6 + d33*dyp1*dyp6 + d22*dzp1*dzp6);
        KOrtho(5, 21) += weight * (d02*dxp7*dzp1 + d44*dxp1*dzp7);
        KOrtho(5, 22) += weight * (d12*dyp7*dzp1 + d33*dyp1*dzp7);
        KOrtho(5, 23) += weight * (d44*dxp1*dxp7 + d33*dyp1*dyp7 + d22*dzp1*dzp7);
        KOrtho(6, 6) += weight * (d00*(dxp2*dxp2) + d55*(dyp2*dyp2) + d44*(dzp2*dzp2));
        KOrtho(6, 7) += weight * ((d01 + d55)*dxp2*dyp2);
        KOrtho(6, 8) += weight * ((d02 + d44)*dxp2*dzp2);
        KOrtho(6, 9) += weight * (d00*dxp2*dxp3 + d55*dyp2*dyp3 + d44*dzp2*dzp3);
        KOrtho(6, 10) += weight * (d55*dxp3*dyp2 + d01*dxp2*dyp3);
        KOrtho(6, 11) += weight * (d44*dxp3*dzp2 + d02*dxp2*dzp3);
        KOrtho(6, 12) += weight * (d00*dxp2*dxp4 + d55*dyp2*dyp4 + d44*dzp2*dzp4);
        KOrtho(6, 13) += weight * (d55*dxp4*dyp2 + d01*dxp2*dyp4);
        KOrtho(6, 14) += weight * (d44*dxp4*dzp2 + d02*dxp2*dzp4);
        KOrtho(6, 15) += weight * (d00*dxp2*dxp5 + d55*dyp2*dyp5 + d44*dzp2*dzp5);
        KOrtho(6, 16) += weight * (d55*dxp5*dyp2 + d01*dxp2*dyp5);
        KOrtho(6, 17) += weight * (d44*dxp5*dzp2 + d02*dxp2*dzp5);
        KOrtho(6, 18) += weight * (d00*dxp2*dxp6 + d55*dyp2*dyp6 + d44*dzp2*dzp6);
        KOrtho(6, 19) += weight * (d55*dxp6*dyp2 + d01*dxp2*dyp6);
        KOrtho(6, 20) += weight * (d44*dxp6*dzp2 + d02*dxp2*dzp6);
        KOrtho(6, 21) += weight * (d00*dxp2*dxp7 + d55*dyp2*dyp7 + d44*dzp2*dzp7);
        KOrtho(6, 22) += weight * (d55*dxp7*dyp2 + d01*dxp2*dyp7);
        KOrtho(6, 23) += weight * (d44*dxp7*dzp2 + d02*dxp2*dzp7);
        KOrtho(7, 7) += weight * (d55*(dxp2*dxp2) + d11*(dyp2*dyp2) + d33*(dzp2*dzp2));
        KOrtho(7, 8) += weight * ((d12 + d33)*dyp2*dzp2);
        KOrtho(7, 9) += weight * (d01*dxp3*dyp2 + d55*dxp2*dyp3);
        KOrtho(7, 10) += weight * (d55*dxp2*dxp3 + d11*dyp2*dyp3 + d33*dzp2*dzp3);
        KOrtho(7, 11) += weight * (d33*dyp3*dzp2 + d12*dyp2*dzp3);
        KOrtho(7, 12) += weight * (d01*dxp4*dyp2 + d55*dxp2*dyp4);
        KOrtho(7, 13) += weight * (d55*dxp2*dxp4 + d11*dyp2*dyp4 + d33*dzp2*dzp4);
        KOrtho(7, 14) += weight * (d33*dyp4*dzp2 + d12*dyp2*dzp4);
        KOrtho(7, 15) += weight * (d01*dxp5*dyp2 + d55*dxp2*dyp5);
        KOrtho(7, 16) += weight * (d55*dxp2*dxp5 + d11*dyp2*dyp5 + d33*dzp2*dzp5);
        KOrtho(7, 17) += weight * (d33*dyp5*dzp2 + d12*dyp2*dzp5);
        KOrtho(7, 18) += weight * (d01*dxp6*dyp2 + d55*dxp2*dyp6);
        KOrtho(7, 19) += weight * (d55*dxp2*dxp6 + d11*dyp2*dyp6 + d33*dzp2*dzp6);
        KOrtho(7, 20) += weight * (d33*dyp6*dzp2 + d12*dyp2*dzp6);
        KOrtho(7, 21) += weight * (d01*dxp7*dyp2 + d55*dxp2*dyp7);
        KOrtho(7, 22) += weight * (d55*dxp2*dxp7 + d11*dyp2*dyp7 + d33*dzp2*dzp7);
        KOrtho(7, 23) += weight * (d33*dyp7*dzp2 + d12*dyp2*dzp7);
        KOrtho(8, 8) += weight * (d44*(dxp2*dxp2) + d33*(dyp2*dyp2) + d22*(dzp2*dzp2));
        KOrtho(8, 9) += weight * (d02*dxp3*dzp2 + d44*dxp2*dzp3);
        KOrtho(8, 10) += weight * (d12*dyp3*dzp2 + d33*dyp2*dzp3);
        KOrtho(8, 11) += weight * (d44*dxp2*dxp3 + d33*dyp2*dyp3 + d22*dzp2*dzp3);
        KOrtho(8, 12) += weight * (d02*dxp4*dzp2 + d44*dxp2*dzp4);
        KOrtho(8, 13) += weight * (d12*dyp4*dzp2 + d33*dyp2*dzp4);
        KOrtho(8, 14) += weight * (d44*dxp2*dxp4 + d33*dyp2*dyp4 + d22*dzp2*dzp4);
        KOrtho(8, 15) += weight * (d02*dxp5*dzp2 + d44*dxp2*dzp5);
        KOrtho(8, 16) += weight * (d12*dyp5*dzp2 + d33*dyp2*dzp5);
        KOrtho(8, 17) += weight * (d44*dxp2*dxp5 + d33*dyp2*dyp5 + d22*dzp2*dzp5);
        KOrtho(8, 18) += weight * (d02*dxp6*dzp2 + d44*dxp2*dzp6);
        KOrtho(8, 19) += weight * (d12*dyp6*dzp2 + d33*dyp2*dzp6);
        KOrtho(8, 20) += weight * (d44*dxp2*dxp6 + d33*dyp2*dyp6 + d22*dzp2*dzp6);
        KOrtho(8, 21) += weight * (d02*dxp7*dzp2 + d44*dxp2*dzp7);
        KOrtho(8, 22) += weight * (d12*dyp7*dzp2 + d33*dyp2*dzp7);
        KOrtho(8, 23) += weight * (d44*dxp2*dxp7 + d33*dyp2*dyp7 + d22*dzp2*dzp7);
        KOrtho(9, 9) += weight * (d00*(dxp3*dxp3) + d55*(dyp3*dyp3) + d44*(dzp3*dzp3));
        KOrtho(9, 10) += weight * ((d01 + d55)*dxp3*dyp3);
        KOrtho(9, 11) += weight * ((d02 + d44)*dxp3*dzp3);
        KOrtho(9, 12) += weight * (d00*dxp3*dxp4 + d55*dyp3*dyp4 + d44*dzp3*dzp4);
        KOrtho(9, 13) += weight * (d55*dxp4*dyp3 + d01*dxp3*dyp4);
        KOrtho(9, 14) += weight * (d44*dxp4*dzp3 + d02*dxp3*dzp4);
        KOrtho(9, 15) += weight * (d00*dxp3*dxp5 + d55*dyp3*dyp5 + d44*dzp3*dzp5);
        KOrtho(9, 16) += weight * (d55*dxp5*dyp3 + d01*dxp3*dyp5);
        KOrtho(9, 17) += weight * (d44*dxp5*dzp3 + d02*dxp3*dzp5);
        KOrtho(9, 18) += weight * (d00*dxp3*dxp6 + d55*dyp3*dyp6 + d44*dzp3*dzp6);
        KOrtho(9, 19) += weight * (d55*dxp6*dyp3 + d01*dxp3*dyp6);
        KOrtho(9, 20) += weight * (d44*dxp6*dzp3 + d02*dxp3*dzp6);
        KOrtho(9, 21) += weight * (d00*dxp3*dxp7 + d55*dyp3*dyp7 + d44*dzp3*dzp7);
        KOrtho(9, 22) += weight * (d55*dxp7*dyp3 + d01*dxp3*dyp7);
        KOrtho(9, 23) += weight * (d44*dxp7*dzp3 + d02*dxp3*dzp7);
        KOrtho(10, 10) += weight * (d55*(dxp3*dxp3) + d11*(dyp3*dyp3) + d33*(dzp3*dzp3));
        KOrtho(10, 11) += weight * ((d12 + d33)*dyp3*dzp3);
        KOrtho(10, 12) += weight * (d01*dxp4*dyp3 + d55*dxp3*dyp4);
        KOrtho(10, 13) += weight * (d55*dxp3*dxp4 + d11*dyp3*dyp4 + d33*dzp3*dzp4);
        KOrtho(10, 14) += weight * (d33*dyp4*dzp3 + d12*dyp3*dzp4);
        KOrtho(10, 15) += weight * (d01*dxp5*dyp3 + d55*dxp3*dyp5);
        KOrtho(10, 16) += weight * (d55*dxp3*dxp5 + d11*dyp3*dyp5 + d33*dzp3*dzp5);
        KOrtho(10, 17) += weight * (d33*dyp5*dzp3 + d12*dyp3*dzp5);
        KOrtho(10, 18) += weight * (d01*dxp6*dyp3 + d55*dxp3*dyp6);
        KOrtho(10, 19) += weight * (d55*dxp3*dxp6 + d11*dyp3*dyp6 + d33*dzp3*dzp6);
        KOrtho(10, 20) += weight * (d33*dyp6*dzp3 + d12*dyp3*dzp6);
        KOrtho(10, 21) += weight * (d01*dxp7*dyp3 + d55*dxp3*dyp7);
        KOrtho(10, 22) += weight * (d55*dxp3*dxp7 + d11*dyp3*dyp7 + d33*dzp3*dzp7);
        KOrtho(10, 23) += weight * (d33*dyp7*dzp3 + d12*dyp3*dzp7);
        KOrtho(11, 11) += weight * (d44*(dxp3*dxp3) + d33*(dyp3*dyp3) + d22*(dzp3*dzp3));
        KOrtho(11, 12) += weight * (d02*dxp4*dzp3 + d44*dxp3*dzp4);
        KOrtho(11, 13) += weight * (d12*dyp4*dzp3 + d33*dyp3*dzp4);
        KOrtho(11, 14) += weight * (d44*dxp3*dxp4 + d33*dyp3*dyp4 + d22*dzp3*dzp4);
        KOrtho(11, 15) += weight * (d02*dxp5*dzp3 + d44*dxp3*dzp5);
        KOrtho(11, 16) += weight * (d12*dyp5*dzp3 + d33*dyp3*dzp5);
        KOrtho(11, 17) += weight * (d44*dxp3*dxp5 + d33*dyp3*dyp5 + d22*dzp3*dzp5);
        KOrtho(11, 18) += weight * (d02*dxp6*dzp3 + d44*dxp3*dzp6);
        KOrtho(11, 19) += weight * (d12*dyp6*dzp3 + d33*dyp3*dzp6);
        KOrtho(11, 20) += weight * (d44*dxp3*dxp6 + d33*dyp3*dyp6 + d22*dzp3*dzp6);
        KOrtho(11, 21) += weight * (d02*dxp7*dzp3 + d44*dxp3*dzp7);
        KOrtho(11, 22) += weight * (d12*dyp7*dzp3 + d33*dyp3*dzp7);
        KOrtho(11, 23) += weight * (d44*dxp3*dxp7 + d33*dyp3*dyp7 + d22*dzp3*dzp7);
        KOrtho(12, 12) += weight * (d00*(dxp4*dxp4) + d55*(dyp4*dyp4) + d44*(dzp4*dzp4));
        KOrtho(12, 13) += weight * ((d01 + d55)*dxp4*dyp4);
        KOrtho(12, 14) += weight * ((d02 + d44)*dxp4*dzp4);
        KOrtho(12, 15) += weight * (d00*dxp4*dxp5 + d55*dyp4*dyp5 + d44*dzp4*dzp5);
        KOrtho(12, 16) += weight * (d55*dxp5*dyp4 + d01*dxp4*dyp5);
        KOrtho(12, 17) += weight * (d44*dxp5*dzp4 + d02*dxp4*dzp5);
        KOrtho(12, 18) += weight * (d00*dxp4*dxp6 + d55*dyp4*dyp6 + d44*dzp4*dzp6);
        KOrtho(12, 19) += weight * (d55*dxp6*dyp4 + d01*dxp4*dyp6);
        KOrtho(12, 20) += weight * (d44*dxp6*dzp4 + d02*dxp4*dzp6);
        KOrtho(12, 21) += weight * (d00*dxp4*dxp7 + d55*dyp4*dyp7 + d44*dzp4*dzp7);
        KOrtho(12, 22) += weight * (d55*dxp7*dyp4 + d01*dxp4*dyp7);
        KOrtho(12, 23) += weight * (d44*dxp7*dzp4 + d02*dxp4*dzp7);
        KOrtho(13, 13) += weight * (d55*(dxp4*dxp4) + d11*(dyp4*dyp4) + d33*(dzp4*dzp4));
        KOrtho(13, 14) += weight * ((d12 + d33)*dyp4*dzp4);
        KOrtho(13, 15) += weight * (d01*dxp5*dyp4 + d55*dxp4*dyp5);
        KOrtho(13, 16) += weight * (d55*dxp4*dxp5 + d11*dyp4*dyp5 + d33*dzp4*dzp5);
        KOrtho(13, 17) += weight * (d33*dyp5*dzp4 + d12*dyp4*dzp5);
        KOrtho(13, 18) += weight * (d01*dxp6*dyp4 + d55*dxp4*dyp6);
        KOrtho(13, 19) += weight * (d55*dxp4*dxp6 + d11*dyp4*dyp6 + d33*dzp4*dzp6);
        KOrtho(13, 20) += weight * (d33*dyp6*dzp4 + d12*dyp4*dzp6);
        KOrtho(13, 21) += weight * (d01*dxp7*dyp4 + d55*dxp4*dyp7);
        KOrtho(13, 22) += weight * (d55*dxp4*dxp7 + d11*dyp4*dyp7 + d33*dzp4*dzp7);
        KOrtho(13, 23) += weight * (d33*dyp7*dzp4 + d12*dyp4*dzp7);
        KOrtho(14, 14) += weight * (d44*(dxp4*dxp4) + d33*(dyp4*dyp4) + d22*(dzp4*dzp4));
        KOrtho(14, 15) += weight * (d02*dxp5*dzp4 + d44*dxp4*dzp5);
        KOrtho(14, 16) += weight * (d12*dyp5*dzp4 + d33*dyp4*dzp5);
        KOrtho(14, 17) += weight * (d44*dxp4*dxp5 + d33*dyp4*dyp5 + d22*dzp4*dzp5);
        KOrtho(14, 18) += weight * (d02*dxp6*dzp4 + d44*dxp4*dzp6);
        KOrtho(14, 19) += weight * (d12*dyp6*dzp4 + d33*dyp4*dzp6);
        KOrtho(14, 20) += weight * (d44*dxp4*dxp6 + d33*dyp4*dyp6 + d22*dzp4*dzp6);
        KOrtho(14, 21) += weight * (d02*dxp7*dzp4 + d44*dxp4*dzp7);
        KOrtho(14, 22) += weight * (d12*dyp7*dzp4 + d33*dyp4*dzp7);
        KOrtho(14, 23) += weight * (d44*dxp4*dxp7 + d33*dyp4*dyp7 + d22*dzp4*dzp7);
        KOrtho(15, 15) += weight * (d00*(dxp5*dxp5) + d55*(dyp5*dyp5) + d44*(dzp5*dzp5));
        KOrtho(15, 16) += weight * ((d01 + d55)*dxp5*dyp5);
        KOrtho(15, 17) += weight * ((d02 + d44)*dxp5*dzp5);
        KOrtho(15, 18) += weight * (d00*dxp5*dxp6 + d55*dyp5*dyp6 + d44*dzp5*dzp6);
        KOrtho(15, 19) += weight * (d55*dxp6*dyp5 + d01*dxp5*dyp6);
        KOrtho(15, 20) += weight * (d44*dxp6*dzp5 + d02*dxp5*dzp6);
        KOrtho(15, 21) += weight * (d00*dxp5*dxp7 + d55*dyp5*dyp7 + d44*dzp5*dzp7);
        KOrtho(15, 22) += weight * (d55*dxp7*dyp5 + d01*dxp5*dyp7);
        KOrtho(15, 23) += weight * (d44*dxp7*dzp5 + d02*dxp5*dzp7);
        KOrtho(16, 16) += weight * (d55*(dxp5*dxp5) + d11*(dyp5*dyp5) + d33*(dzp5*dzp5));
        KOrtho(16, 17) += weight * ((d12 + d33)*dyp5*dzp5);
        KOrtho(16, 18) += weight * (d01*dxp6*dyp5 + d55*dxp5*dyp6);
        KOrtho(16, 19) += weight * (d55*dxp5*dxp6 + d11*dyp5*dyp6 + d33*dzp5*dzp6);
        KOrtho(16, 20) += weight * (d33*dyp6*dzp5 + d12*dyp5*dzp6);
        KOrtho(16, 21) += weight * (d01*dxp7*dyp5 + d55*dxp5*dyp7);
        KOrtho(16, 22) += weight * (d55*dxp5*dxp7 + d11*dyp5*dyp7 + d33*dzp5*dzp7);
        KOrtho(16, 23) += weight * (d33*dyp7*dzp5 + d12*dyp5*dzp7);
        KOrtho(17, 17) += weight * (d44*(dxp5*dxp5) + d33*(dyp5*dyp5) + d22*(dzp5*dzp5));
        KOrtho(17, 18) += weight * (d02*dxp6*dzp5 + d44*dxp5*dzp6);
        KOrtho(17, 19) += weight * (d12*dyp6*dzp5 + d33*dyp5*dzp6);
        KOrtho(17, 20) += weight * (d44*dxp5*dxp6 + d33*dyp5*dyp6 + d22*dzp5*dzp6);
        KOrtho(17, 21) += weight * (d02*dxp7*dzp5 + d44*dxp5*dzp7);
        KOrtho(17, 22) += weight * (d12*dyp7*dzp5 + d33*dyp5*dzp7);
        KOrtho(17, 23) += weight * (d44*dxp5*dxp7 + d33*dyp5*dyp7 + d22*dzp5*dzp7);
        KOrtho(18, 18) += weight * (d00*(dxp6*dxp6) + d55*(dyp6*dyp6) + d44*(dzp6*dzp6));
        KOrtho(18, 19) += weight * ((d01 + d55)*dxp6*dyp6);
        KOrtho(18, 20) += weight * ((d02 + d44)*dxp6*dzp6);
        KOrtho(18, 21) += weight * (d00*dxp6*dxp7 + d55*dyp6*dyp7 + d44*dzp6*dzp7);
        KOrtho(18, 22) += weight * (d55*dxp7*dyp6 + d01*dxp6*dyp7);
        KOrtho(18, 23) += weight * (d44*dxp7*dzp6 + d02*dxp6*dzp7);
        KOrtho(19, 19) += weight * (d55*(dxp6*dxp6) + d11*(dyp6*dyp6) + d33*(dzp6*dzp6));
        KOrtho(19, 20) += weight * ((d12 + d33)*dyp6*dzp6);
        KOrtho(19, 21) += weight * (d01*dxp7*dyp6 + d55*dxp6*dyp7);
        KOrtho(19, 22) += weight * (d55*dxp6*dxp7 + d11*dyp6*dyp7 + d33*dzp6*dzp7);
        KOrtho(19, 23) += weight * (d33*dyp7*dzp6 + d12*dyp6*dzp7);
        KOrtho(20, 20) += weight * (d44*(dxp6*dxp6) + d33*(dyp6*dyp6) + d22*(dzp6*dzp6));
        KOrtho(20, 21) += weight * (d02*dxp7*dzp6 + d44*dxp6*dzp7);
        KOrtho(20, 22) += weight * (d12*dyp7*dzp6 + d33*dyp6*dzp7);
        KOrtho(20, 23) += weight * (d44*dxp6*dxp7 + d33*dyp6*dyp7 + d22*dzp6*dzp7);
        KOrtho(21, 21) += weight * (d00*(dxp7*dxp7) + d55*(dyp7*dyp7) + d44*(dzp7*dzp7));
        KOrtho(21, 22) += weight * ((d01 + d55)*dxp7*dyp7);
        KOrtho(21, 23) += weight * ((d02 + d44)*dxp7*dzp7);
        KOrtho(22, 22) += weight * (d55*(dxp7*dxp7) + d11*(dyp7*dyp7) + d33*(dzp7*dzp7));
        KOrtho(22, 23) += weight * ((d12 + d33)*dyp7*dzp7);
        KOrtho(23, 23) += weight * (d44*(dxp7*dxp7) + d33*(dyp7*dyp7) + d22*(dzp7*dzp7));
    }

    // Analytic result for a full cell
    Real fullCellIntegral(size_t i, size_t j) {
        if (!m_fullCellIntegralCached) {
            // Unpack elasticity tensor
            // .5 scaling for off-diagonals  is to account for engineering stress :
            // engineering strain double-counting the off-diagonals.
            Real d00 = m_d[0], d01 = 0.5 * m_d[1], d02 = 0.5 * m_d[ 2], // d03 = 0.5 * m_d[ 3], d04 = .5 * m_d[ 4], d05 = .5 * m_d[ 5],
                               d11 =       m_d[6], d12 = 0.5 * m_d[ 7], // d13 = 0.5 * m_d[ 8], d14 = .5 * m_d[ 9], d15 = .5 * m_d[ 10],
                                                   d22 =       m_d[11], // d23 = 0.5 * m_d[12], d24 = .5 * m_d[13], d25 = .5 * m_d[14],
                                                                        d33 =       m_d[15], // d34 = .5 * m_d[16], d35 = .5 * m_d[17],
                                                                                             d44 =      m_d[18], // d45 = .5 * m_d[19],
                                                                                                                 d55 =      m_d[20];

            Real w = m_dimensions[0];
            Real h = m_dimensions[1];
            Real d = m_dimensions[2];
            Real invVol = 1.0 / (w * h * d);

            Real dSqhSq = d * d * h * h;
            Real dSqwSq = d * d * w * w;
            Real hSqwSq = h * h * w * w;
            Real dSqhw  = d * d * h * w;
            Real wSqdh  = w * w * d * h;
            Real hSqdw  = h * h * d * w;

            KOrthoInt(0, 0) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            KOrthoInt(0, 1) = invVol * ((d01 + d55)*dSqhw)/12.;
            KOrthoInt(0, 2) = invVol * ((d02 + d44)*hSqdw)/12.;
            KOrthoInt(0, 3) = invVol * (-2*d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/18.;
            KOrthoInt(0, 4) = invVol * ((d01 - d55)*dSqhw)/12.;
            KOrthoInt(0, 5) = invVol * ((d02 - d44)*hSqdw)/12.;
            KOrthoInt(0, 6) = invVol * (-2*d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/36.;
            KOrthoInt(0, 7) = invVol * -((d01 + d55)*dSqhw)/12.;
            KOrthoInt(0, 8) = invVol * ((d02 - d44)*hSqdw)/24.;
            KOrthoInt(0, 9) = invVol * (d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/18.;
            KOrthoInt(0, 10) = invVol * ((-d01 + d55)*dSqhw)/12.;
            KOrthoInt(0, 11) = invVol * ((d02 + d44)*hSqdw)/24.;
            KOrthoInt(0, 12) = invVol * (d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/18.;
            KOrthoInt(0, 13) = invVol * ((d01 + d55)*dSqhw)/24.;
            KOrthoInt(0, 14) = invVol * ((-d02 + d44)*hSqdw)/12.;
            KOrthoInt(0, 15) = invVol * (-2*d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/36.;
            KOrthoInt(0, 16) = invVol * ((d01 - d55)*dSqhw)/24.;
            KOrthoInt(0, 17) = invVol * -((d02 + d44)*hSqdw)/12.;
            KOrthoInt(0, 18) = invVol * (-(d00*dSqhSq) - d55*dSqwSq - d44*hSqwSq)/36.;
            KOrthoInt(0, 19) = invVol * -((d01 + d55)*dSqhw)/24.;
            KOrthoInt(0, 20) = invVol * -((d02 + d44)*hSqdw)/24.;
            KOrthoInt(0, 21) = invVol * (d00*dSqhSq - 2*(d55*dSqwSq + d44*hSqwSq))/36.;
            KOrthoInt(0, 22) = invVol * ((-d01 + d55)*dSqhw)/24.;
            KOrthoInt(0, 23) = invVol * ((-d02 + d44)*hSqdw)/24.;
            KOrthoInt(1, 1) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            KOrthoInt(1, 2) = invVol * ((d12 + d33)*wSqdh)/12.;
            KOrthoInt(1, 3) = invVol * ((-d01 + d55)*dSqhw)/12.;
            KOrthoInt(1, 4) = invVol * (-2*d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/18.;
            KOrthoInt(1, 5) = invVol * ((d12 + d33)*wSqdh)/24.;
            KOrthoInt(1, 6) = invVol * -((d01 + d55)*dSqhw)/12.;
            KOrthoInt(1, 7) = invVol * (-2*d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/36.;
            KOrthoInt(1, 8) = invVol * ((d12 - d33)*wSqdh)/24.;
            KOrthoInt(1, 9) = invVol * ((d01 - d55)*dSqhw)/12.;
            KOrthoInt(1, 10) = invVol * (d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/18.;
            KOrthoInt(1, 11) = invVol * ((d12 - d33)*wSqdh)/12.;
            KOrthoInt(1, 12) = invVol * ((d01 + d55)*dSqhw)/24.;
            KOrthoInt(1, 13) = invVol * (d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/18.;
            KOrthoInt(1, 14) = invVol * ((-d12 + d33)*wSqdh)/12.;
            KOrthoInt(1, 15) = invVol * ((-d01 + d55)*dSqhw)/24.;
            KOrthoInt(1, 16) = invVol * (-2*d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/36.;
            KOrthoInt(1, 17) = invVol * ((-d12 + d33)*wSqdh)/24.;
            KOrthoInt(1, 18) = invVol * -((d01 + d55)*dSqhw)/24.;
            KOrthoInt(1, 19) = invVol * (-(d55*dSqhSq) - d11*dSqwSq - d33*hSqwSq)/36.;
            KOrthoInt(1, 20) = invVol * -((d12 + d33)*wSqdh)/24.;
            KOrthoInt(1, 21) = invVol * ((d01 - d55)*dSqhw)/24.;
            KOrthoInt(1, 22) = invVol * (d55*dSqhSq - 2*(d11*dSqwSq + d33*hSqwSq))/36.;
            KOrthoInt(1, 23) = invVol * -((d12 + d33)*wSqdh)/12.;
            KOrthoInt(2, 2) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            KOrthoInt(2, 3) = invVol * ((-d02 + d44)*hSqdw)/12.;
            KOrthoInt(2, 4) = invVol * ((d12 + d33)*wSqdh)/24.;
            KOrthoInt(2, 5) = invVol * (-2*d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/18.;
            KOrthoInt(2, 6) = invVol * ((-d02 + d44)*hSqdw)/24.;
            KOrthoInt(2, 7) = invVol * ((-d12 + d33)*wSqdh)/24.;
            KOrthoInt(2, 8) = invVol * (-2*d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/36.;
            KOrthoInt(2, 9) = invVol * ((d02 + d44)*hSqdw)/24.;
            KOrthoInt(2, 10) = invVol * ((-d12 + d33)*wSqdh)/12.;
            KOrthoInt(2, 11) = invVol * (d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/18.;
            KOrthoInt(2, 12) = invVol * ((d02 - d44)*hSqdw)/12.;
            KOrthoInt(2, 13) = invVol * ((d12 - d33)*wSqdh)/12.;
            KOrthoInt(2, 14) = invVol * (d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/18.;
            KOrthoInt(2, 15) = invVol * -((d02 + d44)*hSqdw)/12.;
            KOrthoInt(2, 16) = invVol * ((d12 - d33)*wSqdh)/24.;
            KOrthoInt(2, 17) = invVol * (-2*d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/36.;
            KOrthoInt(2, 18) = invVol * -((d02 + d44)*hSqdw)/24.;
            KOrthoInt(2, 19) = invVol * -((d12 + d33)*wSqdh)/24.;
            KOrthoInt(2, 20) = invVol * (-(d44*dSqhSq) - d33*dSqwSq - d22*hSqwSq)/36.;
            KOrthoInt(2, 21) = invVol * ((d02 - d44)*hSqdw)/24.;
            KOrthoInt(2, 22) = invVol * -((d12 + d33)*wSqdh)/12.;
            KOrthoInt(2, 23) = invVol * (d44*dSqhSq - 2*(d33*dSqwSq + d22*hSqwSq))/36.;
            KOrthoInt(3, 3) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            KOrthoInt(3, 4) = invVol * -((d01 + d55)*dSqhw)/12.;
            KOrthoInt(3, 5) = invVol * -((d02 + d44)*hSqdw)/12.;
            KOrthoInt(3, 6) = invVol * (d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/18.;
            KOrthoInt(3, 7) = invVol * ((d01 - d55)*dSqhw)/12.;
            KOrthoInt(3, 8) = invVol * -((d02 + d44)*hSqdw)/24.;
            KOrthoInt(3, 9) = invVol * (-2*d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/36.;
            KOrthoInt(3, 10) = invVol * ((d01 + d55)*dSqhw)/12.;
            KOrthoInt(3, 11) = invVol * ((-d02 + d44)*hSqdw)/24.;
            KOrthoInt(3, 12) = invVol * (-2*d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/36.;
            KOrthoInt(3, 13) = invVol * ((-d01 + d55)*dSqhw)/24.;
            KOrthoInt(3, 14) = invVol * ((d02 + d44)*hSqdw)/12.;
            KOrthoInt(3, 15) = invVol * (d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/18.;
            KOrthoInt(3, 16) = invVol * -((d01 + d55)*dSqhw)/24.;
            KOrthoInt(3, 17) = invVol * ((d02 - d44)*hSqdw)/12.;
            KOrthoInt(3, 18) = invVol * (d00*dSqhSq - 2*(d55*dSqwSq + d44*hSqwSq))/36.;
            KOrthoInt(3, 19) = invVol * ((d01 - d55)*dSqhw)/24.;
            KOrthoInt(3, 20) = invVol * ((d02 - d44)*hSqdw)/24.;
            KOrthoInt(3, 21) = invVol * (-(d00*dSqhSq) - d55*dSqwSq - d44*hSqwSq)/36.;
            KOrthoInt(3, 22) = invVol * ((d01 + d55)*dSqhw)/24.;
            KOrthoInt(3, 23) = invVol * ((d02 + d44)*hSqdw)/24.;
            KOrthoInt(4, 4) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            KOrthoInt(4, 5) = invVol * ((d12 + d33)*wSqdh)/12.;
            KOrthoInt(4, 6) = invVol * ((-d01 + d55)*dSqhw)/12.;
            KOrthoInt(4, 7) = invVol * (d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/18.;
            KOrthoInt(4, 8) = invVol * ((d12 - d33)*wSqdh)/12.;
            KOrthoInt(4, 9) = invVol * ((d01 + d55)*dSqhw)/12.;
            KOrthoInt(4, 10) = invVol * (-2*d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/36.;
            KOrthoInt(4, 11) = invVol * ((d12 - d33)*wSqdh)/24.;
            KOrthoInt(4, 12) = invVol * ((d01 - d55)*dSqhw)/24.;
            KOrthoInt(4, 13) = invVol * (-2*d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/36.;
            KOrthoInt(4, 14) = invVol * ((-d12 + d33)*wSqdh)/24.;
            KOrthoInt(4, 15) = invVol * -((d01 + d55)*dSqhw)/24.;
            KOrthoInt(4, 16) = invVol * (d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/18.;
            KOrthoInt(4, 17) = invVol * ((-d12 + d33)*wSqdh)/12.;
            KOrthoInt(4, 18) = invVol * ((-d01 + d55)*dSqhw)/24.;
            KOrthoInt(4, 19) = invVol * (d55*dSqhSq - 2*(d11*dSqwSq + d33*hSqwSq))/36.;
            KOrthoInt(4, 20) = invVol * -((d12 + d33)*wSqdh)/12.;
            KOrthoInt(4, 21) = invVol * ((d01 + d55)*dSqhw)/24.;
            KOrthoInt(4, 22) = invVol * (-(d55*dSqhSq) - d11*dSqwSq - d33*hSqwSq)/36.;
            KOrthoInt(4, 23) = invVol * -((d12 + d33)*wSqdh)/24.;
            KOrthoInt(5, 5) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            KOrthoInt(5, 6) = invVol * -((d02 + d44)*hSqdw)/24.;
            KOrthoInt(5, 7) = invVol * ((-d12 + d33)*wSqdh)/12.;
            KOrthoInt(5, 8) = invVol * (d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/18.;
            KOrthoInt(5, 9) = invVol * ((d02 - d44)*hSqdw)/24.;
            KOrthoInt(5, 10) = invVol * ((-d12 + d33)*wSqdh)/24.;
            KOrthoInt(5, 11) = invVol * (-2*d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/36.;
            KOrthoInt(5, 12) = invVol * ((d02 + d44)*hSqdw)/12.;
            KOrthoInt(5, 13) = invVol * ((d12 - d33)*wSqdh)/24.;
            KOrthoInt(5, 14) = invVol * (-2*d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/36.;
            KOrthoInt(5, 15) = invVol * ((-d02 + d44)*hSqdw)/12.;
            KOrthoInt(5, 16) = invVol * ((d12 - d33)*wSqdh)/12.;
            KOrthoInt(5, 17) = invVol * (d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/18.;
            KOrthoInt(5, 18) = invVol * ((-d02 + d44)*hSqdw)/24.;
            KOrthoInt(5, 19) = invVol * -((d12 + d33)*wSqdh)/12.;
            KOrthoInt(5, 20) = invVol * (d44*dSqhSq - 2*(d33*dSqwSq + d22*hSqwSq))/36.;
            KOrthoInt(5, 21) = invVol * ((d02 + d44)*hSqdw)/24.;
            KOrthoInt(5, 22) = invVol * -((d12 + d33)*wSqdh)/24.;
            KOrthoInt(5, 23) = invVol * (-(d44*dSqhSq) - d33*dSqwSq - d22*hSqwSq)/36.;
            KOrthoInt(6, 6) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            KOrthoInt(6, 7) = invVol * ((d01 + d55)*dSqhw)/12.;
            KOrthoInt(6, 8) = invVol * -((d02 + d44)*hSqdw)/12.;
            KOrthoInt(6, 9) = invVol * (-2*d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/18.;
            KOrthoInt(6, 10) = invVol * ((d01 - d55)*dSqhw)/12.;
            KOrthoInt(6, 11) = invVol * ((-d02 + d44)*hSqdw)/12.;
            KOrthoInt(6, 12) = invVol * (-(d00*dSqhSq) - d55*dSqwSq - d44*hSqwSq)/36.;
            KOrthoInt(6, 13) = invVol * -((d01 + d55)*dSqhw)/24.;
            KOrthoInt(6, 14) = invVol * ((d02 + d44)*hSqdw)/24.;
            KOrthoInt(6, 15) = invVol * (d00*dSqhSq - 2*(d55*dSqwSq + d44*hSqwSq))/36.;
            KOrthoInt(6, 16) = invVol * ((-d01 + d55)*dSqhw)/24.;
            KOrthoInt(6, 17) = invVol * ((d02 - d44)*hSqdw)/24.;
            KOrthoInt(6, 18) = invVol * (d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/18.;
            KOrthoInt(6, 19) = invVol * ((d01 + d55)*dSqhw)/24.;
            KOrthoInt(6, 20) = invVol * ((d02 - d44)*hSqdw)/12.;
            KOrthoInt(6, 21) = invVol * (-2*d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/36.;
            KOrthoInt(6, 22) = invVol * ((d01 - d55)*dSqhw)/24.;
            KOrthoInt(6, 23) = invVol * ((d02 + d44)*hSqdw)/12.;
            KOrthoInt(7, 7) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            KOrthoInt(7, 8) = invVol * -((d12 + d33)*wSqdh)/12.;
            KOrthoInt(7, 9) = invVol * ((-d01 + d55)*dSqhw)/12.;
            KOrthoInt(7, 10) = invVol * (-2*d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/18.;
            KOrthoInt(7, 11) = invVol * -((d12 + d33)*wSqdh)/24.;
            KOrthoInt(7, 12) = invVol * -((d01 + d55)*dSqhw)/24.;
            KOrthoInt(7, 13) = invVol * (-(d55*dSqhSq) - d11*dSqwSq - d33*hSqwSq)/36.;
            KOrthoInt(7, 14) = invVol * ((d12 + d33)*wSqdh)/24.;
            KOrthoInt(7, 15) = invVol * ((d01 - d55)*dSqhw)/24.;
            KOrthoInt(7, 16) = invVol * (d55*dSqhSq - 2*(d11*dSqwSq + d33*hSqwSq))/36.;
            KOrthoInt(7, 17) = invVol * ((d12 + d33)*wSqdh)/12.;
            KOrthoInt(7, 18) = invVol * ((d01 + d55)*dSqhw)/24.;
            KOrthoInt(7, 19) = invVol * (d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/18.;
            KOrthoInt(7, 20) = invVol * ((d12 - d33)*wSqdh)/12.;
            KOrthoInt(7, 21) = invVol * ((-d01 + d55)*dSqhw)/24.;
            KOrthoInt(7, 22) = invVol * (-2*d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/36.;
            KOrthoInt(7, 23) = invVol * ((d12 - d33)*wSqdh)/24.;
            KOrthoInt(8, 8) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            KOrthoInt(8, 9) = invVol * ((d02 - d44)*hSqdw)/12.;
            KOrthoInt(8, 10) = invVol * -((d12 + d33)*wSqdh)/24.;
            KOrthoInt(8, 11) = invVol * (-2*d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/18.;
            KOrthoInt(8, 12) = invVol * ((d02 + d44)*hSqdw)/24.;
            KOrthoInt(8, 13) = invVol * ((d12 + d33)*wSqdh)/24.;
            KOrthoInt(8, 14) = invVol * (-(d44*dSqhSq) - d33*dSqwSq - d22*hSqwSq)/36.;
            KOrthoInt(8, 15) = invVol * ((-d02 + d44)*hSqdw)/24.;
            KOrthoInt(8, 16) = invVol * ((d12 + d33)*wSqdh)/12.;
            KOrthoInt(8, 17) = invVol * (d44*dSqhSq - 2*(d33*dSqwSq + d22*hSqwSq))/36.;
            KOrthoInt(8, 18) = invVol * ((-d02 + d44)*hSqdw)/12.;
            KOrthoInt(8, 19) = invVol * ((-d12 + d33)*wSqdh)/12.;
            KOrthoInt(8, 20) = invVol * (d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/18.;
            KOrthoInt(8, 21) = invVol * ((d02 + d44)*hSqdw)/12.;
            KOrthoInt(8, 22) = invVol * ((-d12 + d33)*wSqdh)/24.;
            KOrthoInt(8, 23) = invVol * (-2*d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/36.;
            KOrthoInt(9, 9) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            KOrthoInt(9, 10) = invVol * -((d01 + d55)*dSqhw)/12.;
            KOrthoInt(9, 11) = invVol * ((d02 + d44)*hSqdw)/12.;
            KOrthoInt(9, 12) = invVol * (d00*dSqhSq - 2*(d55*dSqwSq + d44*hSqwSq))/36.;
            KOrthoInt(9, 13) = invVol * ((d01 - d55)*dSqhw)/24.;
            KOrthoInt(9, 14) = invVol * ((-d02 + d44)*hSqdw)/24.;
            KOrthoInt(9, 15) = invVol * (-(d00*dSqhSq) - d55*dSqwSq - d44*hSqwSq)/36.;
            KOrthoInt(9, 16) = invVol * ((d01 + d55)*dSqhw)/24.;
            KOrthoInt(9, 17) = invVol * -((d02 + d44)*hSqdw)/24.;
            KOrthoInt(9, 18) = invVol * (-2*d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/36.;
            KOrthoInt(9, 19) = invVol * ((-d01 + d55)*dSqhw)/24.;
            KOrthoInt(9, 20) = invVol * -((d02 + d44)*hSqdw)/12.;
            KOrthoInt(9, 21) = invVol * (d00*dSqhSq + d55*dSqwSq - 2*d44*hSqwSq)/18.;
            KOrthoInt(9, 22) = invVol * -((d01 + d55)*dSqhw)/24.;
            KOrthoInt(9, 23) = invVol * ((-d02 + d44)*hSqdw)/12.;
            KOrthoInt(10, 10) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            KOrthoInt(10, 11) = invVol * -((d12 + d33)*wSqdh)/12.;
            KOrthoInt(10, 12) = invVol * ((-d01 + d55)*dSqhw)/24.;
            KOrthoInt(10, 13) = invVol * (d55*dSqhSq - 2*(d11*dSqwSq + d33*hSqwSq))/36.;
            KOrthoInt(10, 14) = invVol * ((d12 + d33)*wSqdh)/12.;
            KOrthoInt(10, 15) = invVol * ((d01 + d55)*dSqhw)/24.;
            KOrthoInt(10, 16) = invVol * (-(d55*dSqhSq) - d11*dSqwSq - d33*hSqwSq)/36.;
            KOrthoInt(10, 17) = invVol * ((d12 + d33)*wSqdh)/24.;
            KOrthoInt(10, 18) = invVol * ((d01 - d55)*dSqhw)/24.;
            KOrthoInt(10, 19) = invVol * (-2*d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/36.;
            KOrthoInt(10, 20) = invVol * ((d12 - d33)*wSqdh)/24.;
            KOrthoInt(10, 21) = invVol * -((d01 + d55)*dSqhw)/24.;
            KOrthoInt(10, 22) = invVol * (d55*dSqhSq + d11*dSqwSq - 2*d33*hSqwSq)/18.;
            KOrthoInt(10, 23) = invVol * ((d12 - d33)*wSqdh)/12.;
            KOrthoInt(11, 11) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            KOrthoInt(11, 12) = invVol * ((d02 - d44)*hSqdw)/24.;
            KOrthoInt(11, 13) = invVol * ((d12 + d33)*wSqdh)/12.;
            KOrthoInt(11, 14) = invVol * (d44*dSqhSq - 2*(d33*dSqwSq + d22*hSqwSq))/36.;
            KOrthoInt(11, 15) = invVol * -((d02 + d44)*hSqdw)/24.;
            KOrthoInt(11, 16) = invVol * ((d12 + d33)*wSqdh)/24.;
            KOrthoInt(11, 17) = invVol * (-(d44*dSqhSq) - d33*dSqwSq - d22*hSqwSq)/36.;
            KOrthoInt(11, 18) = invVol * -((d02 + d44)*hSqdw)/12.;
            KOrthoInt(11, 19) = invVol * ((-d12 + d33)*wSqdh)/24.;
            KOrthoInt(11, 20) = invVol * (-2*d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/36.;
            KOrthoInt(11, 21) = invVol * ((d02 - d44)*hSqdw)/12.;
            KOrthoInt(11, 22) = invVol * ((-d12 + d33)*wSqdh)/12.;
            KOrthoInt(11, 23) = invVol * (d44*dSqhSq + d33*dSqwSq - 2*d22*hSqwSq)/18.;
            KOrthoInt(12, 12) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            KOrthoInt(12, 13) = invVol * ((d01 + d55)*dSqhw)/12.;
            KOrthoInt(12, 14) = invVol * -((d02 + d44)*hSqdw)/12.;
            KOrthoInt(12, 15) = invVol * (-2*d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/18.;
            KOrthoInt(12, 16) = invVol * ((d01 - d55)*dSqhw)/12.;
            KOrthoInt(12, 17) = invVol * ((-d02 + d44)*hSqdw)/12.;
            KOrthoInt(12, 18) = invVol * (-2*d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/36.;
            KOrthoInt(12, 19) = invVol * -((d01 + d55)*dSqhw)/12.;
            KOrthoInt(12, 20) = invVol * ((-d02 + d44)*hSqdw)/24.;
            KOrthoInt(12, 21) = invVol * (d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/18.;
            KOrthoInt(12, 22) = invVol * ((-d01 + d55)*dSqhw)/12.;
            KOrthoInt(12, 23) = invVol * -((d02 + d44)*hSqdw)/24.;
            KOrthoInt(13, 13) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            KOrthoInt(13, 14) = invVol * -((d12 + d33)*wSqdh)/12.;
            KOrthoInt(13, 15) = invVol * ((-d01 + d55)*dSqhw)/12.;
            KOrthoInt(13, 16) = invVol * (-2*d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/18.;
            KOrthoInt(13, 17) = invVol * -((d12 + d33)*wSqdh)/24.;
            KOrthoInt(13, 18) = invVol * -((d01 + d55)*dSqhw)/12.;
            KOrthoInt(13, 19) = invVol * (-2*d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/36.;
            KOrthoInt(13, 20) = invVol * ((-d12 + d33)*wSqdh)/24.;
            KOrthoInt(13, 21) = invVol * ((d01 - d55)*dSqhw)/12.;
            KOrthoInt(13, 22) = invVol * (d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/18.;
            KOrthoInt(13, 23) = invVol * ((-d12 + d33)*wSqdh)/12.;
            KOrthoInt(14, 14) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            KOrthoInt(14, 15) = invVol * ((d02 - d44)*hSqdw)/12.;
            KOrthoInt(14, 16) = invVol * -((d12 + d33)*wSqdh)/24.;
            KOrthoInt(14, 17) = invVol * (-2*d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/18.;
            KOrthoInt(14, 18) = invVol * ((d02 - d44)*hSqdw)/24.;
            KOrthoInt(14, 19) = invVol * ((d12 - d33)*wSqdh)/24.;
            KOrthoInt(14, 20) = invVol * (-2*d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/36.;
            KOrthoInt(14, 21) = invVol * -((d02 + d44)*hSqdw)/24.;
            KOrthoInt(14, 22) = invVol * ((d12 - d33)*wSqdh)/12.;
            KOrthoInt(14, 23) = invVol * (d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/18.;
            KOrthoInt(15, 15) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            KOrthoInt(15, 16) = invVol * -((d01 + d55)*dSqhw)/12.;
            KOrthoInt(15, 17) = invVol * ((d02 + d44)*hSqdw)/12.;
            KOrthoInt(15, 18) = invVol * (d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/18.;
            KOrthoInt(15, 19) = invVol * ((d01 - d55)*dSqhw)/12.;
            KOrthoInt(15, 20) = invVol * ((d02 + d44)*hSqdw)/24.;
            KOrthoInt(15, 21) = invVol * (-2*d00*dSqhSq - 2*d55*dSqwSq + d44*hSqwSq)/36.;
            KOrthoInt(15, 22) = invVol * ((d01 + d55)*dSqhw)/12.;
            KOrthoInt(15, 23) = invVol * ((d02 - d44)*hSqdw)/24.;
            KOrthoInt(16, 16) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            KOrthoInt(16, 17) = invVol * -((d12 + d33)*wSqdh)/12.;
            KOrthoInt(16, 18) = invVol * ((-d01 + d55)*dSqhw)/12.;
            KOrthoInt(16, 19) = invVol * (d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/18.;
            KOrthoInt(16, 20) = invVol * ((-d12 + d33)*wSqdh)/12.;
            KOrthoInt(16, 21) = invVol * ((d01 + d55)*dSqhw)/12.;
            KOrthoInt(16, 22) = invVol * (-2*d55*dSqhSq - 2*d11*dSqwSq + d33*hSqwSq)/36.;
            KOrthoInt(16, 23) = invVol * ((-d12 + d33)*wSqdh)/24.;
            KOrthoInt(17, 17) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            KOrthoInt(17, 18) = invVol * ((d02 + d44)*hSqdw)/24.;
            KOrthoInt(17, 19) = invVol * ((d12 - d33)*wSqdh)/12.;
            KOrthoInt(17, 20) = invVol * (d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/18.;
            KOrthoInt(17, 21) = invVol * ((-d02 + d44)*hSqdw)/24.;
            KOrthoInt(17, 22) = invVol * ((d12 - d33)*wSqdh)/24.;
            KOrthoInt(17, 23) = invVol * (-2*d44*dSqhSq - 2*d33*dSqwSq + d22*hSqwSq)/36.;
            KOrthoInt(18, 18) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            KOrthoInt(18, 19) = invVol * ((d01 + d55)*dSqhw)/12.;
            KOrthoInt(18, 20) = invVol * ((d02 + d44)*hSqdw)/12.;
            KOrthoInt(18, 21) = invVol * (-2*d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/18.;
            KOrthoInt(18, 22) = invVol * ((d01 - d55)*dSqhw)/12.;
            KOrthoInt(18, 23) = invVol * ((d02 - d44)*hSqdw)/12.;
            KOrthoInt(19, 19) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            KOrthoInt(19, 20) = invVol * ((d12 + d33)*wSqdh)/12.;
            KOrthoInt(19, 21) = invVol * ((-d01 + d55)*dSqhw)/12.;
            KOrthoInt(19, 22) = invVol * (-2*d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/18.;
            KOrthoInt(19, 23) = invVol * ((d12 + d33)*wSqdh)/24.;
            KOrthoInt(20, 20) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;
            KOrthoInt(20, 21) = invVol * ((-d02 + d44)*hSqdw)/12.;
            KOrthoInt(20, 22) = invVol * ((d12 + d33)*wSqdh)/24.;
            KOrthoInt(20, 23) = invVol * (-2*d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/18.;
            KOrthoInt(21, 21) = invVol * (d00*dSqhSq + d55*dSqwSq + d44*hSqwSq)/9.;
            KOrthoInt(21, 22) = invVol * -((d01 + d55)*dSqhw)/12.;
            KOrthoInt(21, 23) = invVol * -((d02 + d44)*hSqdw)/12.;
            KOrthoInt(22, 22) = invVol * (d55*dSqhSq + d11*dSqwSq + d33*hSqwSq)/9.;
            KOrthoInt(22, 23) = invVol * ((d12 + d33)*wSqdh)/12.;
            KOrthoInt(23, 23) = invVol * (d44*dSqhSq + d33*dSqwSq + d22*hSqwSq)/9.;

            m_fullCellIntegralCached = true;
        }

        return (i <= j) ? KOrthoInt(i, j) : KOrthoInt(j, i);
    }

    Real operator()(size_t i, size_t j) const {
        assert((i < 24) && (j < 24));
        return (i <= j) ? KOrtho(i, j) : KOrtho(j, i);
    }

private:
    const Model &m_model;
    const DType &m_d;
    Vector m_dimensions;
    bool m_fullCellIntegralCached;

    value_type KOrtho, KOrthoInt;
};

////////////////////////////////////////////////////////////////////////////////
/*! Compute and assemble each 24x24 per-element stiffness matrix into the full
//  3N x 3N stiffness matrix.
//  @param[out] K   Stiffness matrix in sparse triplet format.
*///////////////////////////////////////////////////////////////////////////////
template<typename _Model>
void MeshlessFEM3D<_Model>::m_assembleStiffnessMatrix(TMatrix &K) {
    K.m = K.n = 3 * m_elementGrid.numNodes();
    PerElementOrthotropicStiffnessDensity stiff(m_d, m_model);
    CornerVec cornerIndices;

    K.clear();
    K.reserve(24 * 24 * m_elementGrid.numElements());

    for (size_t e = 0; e < m_elementGrid.numElements(); ++e) {
         BBox b = m_elementGrid.elementBoundingBox(e);
         m_elementGrid.elementCorners(e, cornerIndices);
         stiff.setDimensions(b.dimensions());

         if (m_exactFullElements && m_elementGrid.elementIsFull(e)) {
             for (size_t i = 0; i < 8; ++i) {
                 size_t vi = cornerIndices[i];
                 for (size_t j = 0; j < 8; ++j) {
                     size_t vj = cornerIndices[j];
                     // xx, xy, xz, yx, yy, yz, zx, zy, zz
                     K.addNZ(3 * vi    , 3 * vj    , stiff.fullCellIntegral(3 * i    , 3 * j    ));
                     K.addNZ(3 * vi    , 3 * vj + 1, stiff.fullCellIntegral(3 * i    , 3 * j + 1));
                     K.addNZ(3 * vi    , 3 * vj + 2, stiff.fullCellIntegral(3 * i    , 3 * j + 2));
                     K.addNZ(3 * vi + 1, 3 * vj    , stiff.fullCellIntegral(3 * i + 1, 3 * j    ));
                     K.addNZ(3 * vi + 1, 3 * vj + 1, stiff.fullCellIntegral(3 * i + 1, 3 * j + 1));
                     K.addNZ(3 * vi + 1, 3 * vj + 2, stiff.fullCellIntegral(3 * i + 1, 3 * j + 2));
                     K.addNZ(3 * vi + 2, 3 * vj    , stiff.fullCellIntegral(3 * i + 2, 3 * j    ));
                     K.addNZ(3 * vi + 2, 3 * vj + 1, stiff.fullCellIntegral(3 * i + 2, 3 * j + 1));
                     K.addNZ(3 * vi + 2, 3 * vj + 2, stiff.fullCellIntegral(3 * i + 2, 3 * j + 2));
                 }
             }
         }
         else {
             stiff.clear();
             m_quadrature.integrate(stiff, b);
             for (size_t i = 0; i < 8; ++i) {
                 size_t vi = cornerIndices[i];
                 for (size_t j = 0; j < 8; ++j) {
                     size_t vj = cornerIndices[j];
                     // xx, xy, xz, yx, yy, yz, zx, zy, zz
                     K.addNZ(3 * vi    , 3 * vj    , stiff(3 * i    , 3 * j    ));
                     K.addNZ(3 * vi    , 3 * vj + 1, stiff(3 * i    , 3 * j + 1));
                     K.addNZ(3 * vi    , 3 * vj + 2, stiff(3 * i    , 3 * j + 2));
                     K.addNZ(3 * vi + 1, 3 * vj    , stiff(3 * i + 1, 3 * j    ));
                     K.addNZ(3 * vi + 1, 3 * vj + 1, stiff(3 * i + 1, 3 * j + 1));
                     K.addNZ(3 * vi + 1, 3 * vj + 2, stiff(3 * i + 1, 3 * j + 2));
                     K.addNZ(3 * vi + 2, 3 * vj    , stiff(3 * i + 2, 3 * j    ));
                     K.addNZ(3 * vi + 2, 3 * vj + 1, stiff(3 * i + 2, 3 * j + 1));
                     K.addNZ(3 * vi + 2, 3 * vj + 2, stiff(3 * i + 2, 3 * j + 2));
                 }
             }
         }
    }
}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix whose rows span the space of translations.
//  This matrix can also compute the total force of a load.
//  @param[out] T   Translation mode matrix in sparse triplet format.
*///////////////////////////////////////////////////////////////////////////////
template<typename _Model>
void MeshlessFEM3D<_Model>::m_assembleTranslationMatrix(TMatrix &T) {
    size_t nNodes = m_elementGrid.numNodes();

    T.m = 3;
    T.n = 3 * nNodes;

    T.clear();
    T.reserve(3 * nNodes);
    
    for (size_t k = 0; k < nNodes; ++k) {
        T.addNz(0, 3 * k    , 1.0);
        T.addNz(1, 3 * k + 1, 1.0);
        T.addNz(2, 3 * k + 2, 1.0);
    }
}

template<typename _Model>
void MeshlessFEM3D<_Model>::m_computePerElementDisplacementStrainMap() {

}

////////////////////////////////////////////////////////////////////////////////
/*! Create a sparse matrix mapping a flattened per-node displacement vector to a 
//  flattened per-element (non-engineering) strain tensor. The strain tensor for
//  element e is computed by rows 6 * e + [0..5].
//  @param[out]  B      displacement->strain matrix in sparse triplet format
*///////////////////////////////////////////////////////////////////////////////
template<typename _Model>
void MeshlessFEM3D<_Model>::m_assembleBMatrix(TMatrix &B) {
    if (!m_displacementStrainCached)
        m_computePerElementDisplacementStrainMap();

    B.m = 6 * m_elementGrid.numElements();
    B.n = 3 * m_elementGrid.numNodes();

    B.clear();
    // 3 normal strain rows have  8 nonzeros
    // 3  shear strain rows have 16 nonzeros
    B.reserve(72 * m_elementGrid.numElements());

    CornerVec cornerIndices;
    for (size_t e = 0; e < m_elementGrid.numElements(); ++e) {
        const ElementData &data = m_elementData[e];
        m_elementGrid.elementCorners(e, cornerIndices);
        for (size_t c = 0; c < 8; ++c) {
            size_t vtx = cornerIndices[c];
            // Rows of B are given by Voigt flattening:
            // First normal stresses: e_xx, e_yy, e_zz...
            B.addNZ(6 * e    , 3 * vtx    , data.gradPhi(c, 0));
            B.addNZ(6 * e + 1, 3 * vtx + 1, data.gradPhi(c, 1));
            B.addNZ(6 * e + 2, 3 * vtx + 2, data.gradPhi(c, 2));
            // then shear stresses: e_yz, e_xz, e_xy
            B.addNZ(6 * e + 3, 3 * vtx + 1, 0.5 * data.gradPhi(c, 2));
            B.addNZ(6 * e + 3, 3 * vtx + 2, 0.5 * data.gradPhi(c, 1));
            B.addNZ(6 * e + 4, 3 * vtx    , 0.5 * data.gradPhi(c, 2));
            B.addNZ(6 * e + 4, 3 * vtx + 2, 0.5 * data.gradPhi(c, 0));
            B.addNZ(6 * e + 5, 3 * vtx    , 0.5 * data.gradPhi(c, 1));
            B.addNZ(6 * e + 5, 3 * vtx + 1, 0.5 * data.gradPhi(c, 0));
        }
    }
}

template<typename _Model>
void MeshlessFEM3D<_Model>::m_assembleVDMatrix(TMatrix &VD) {
}
