#if defined __cplusplus
#include <Eigen/Dense>
#include <Eigen/Sparse>
#include <Eigen/UmfPackSupport>
#include <FTGL/ftgl.h>
#include <OpenGL/OpenGL.h>
#include <OpenGL/gl.h>
#include <QAbstractItemModel>
#include <QApplication>
#include <QBasicTimer>
#include <QCheckBox>
#include <QColor>
#include <QComboBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDoubleSpinBox>
#include <QFileDialog>
#include <QFormLayout>
#include <QGLWidget>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QImage>
#include <QImageWriter>
#include <QItemSelection>
#include <QKeyEvent>
#include <QLabel>
#include <QLineEdit>
#include <QList>
#include <QListWidget>
#include <QMainWindow>
#include <QMenu>
#include <QMenuBar>
#include <QMessageBox>
#include <QModelIndex>
#include <QObject>
#include <QPushButton>
#include <QScrollArea>
#include <QSlider>
#include <QSpinBox>
#include <QSplitter>
#include <QTabWidget>
#include <QTextEdit>
#include <QTimerEvent>
#include <QTreeView>
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <QTreeview>
#include <QVBoxLayout>
#include <QVariant>
#include <QWidget>
#include <QtCore/qbytearray.h>
#include <QtCore/qmetatype.h>
#include <QtGui>
#include <algorithm>
#include <boost/algorithm/string.hpp>
#include <boost/foreach.hpp>
#include <boost/format.hpp>
#include <boost/math/special_functions/ellint_2.hpp>
#include <boost/program_options.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/variant.hpp>
#include <cassert>
#include <cmath>
#include <complex>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctype.h>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <queue>
#include <readline/history.h>
#include <readline/readline.h>
// #include <regex>
#include <sstream>
#include <stack>
#include <stdarg.h>
#include <stdexcept>
#include <string>
#include <sys/stat.h>
#include <sys/time.h>
#include <time.h>
#include <vector>
#else
#include <OpenCL/OpenCL.h>
#include <gurobi_c.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#endif
