if (INCLUDE_TINYAD)
    pybind11_add_module(tinyad_parametrization tinyad_parametrization.cc)
    set_target_properties(tinyad_parametrization PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${PROJECT_SOURCE_DIR}/python>)
    target_link_libraries(tinyad_parametrization PUBLIC MeshFEM)
    target_link_libraries(tinyad_parametrization PUBLIC TinyAD)
    target_compile_options(tinyad_parametrization PRIVATE -ftemplate-backtrace-limit=0)
endif()

pybind11_add_module(dirichlet_demo dirichlet_demo.cc)
set_target_properties(dirichlet_demo PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${PROJECT_SOURCE_DIR}/python>)
target_link_libraries(dirichlet_demo PUBLIC MeshFEM)
target_compile_options(dirichlet_demo PRIVATE -ftemplate-backtrace-limit=0)

pybind11_add_module(custom_energy_demo custom_energy_demo.cc)
set_target_properties(custom_energy_demo PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${PROJECT_SOURCE_DIR}/python>)
target_link_libraries(custom_energy_demo PUBLIC MeshFEM)
target_compile_options(custom_energy_demo PRIVATE -ftemplate-backtrace-limit=0)

pybind11_add_module(symdir_test symdir_test.cc)
set_target_properties(symdir_test PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${PROJECT_SOURCE_DIR}/python>)
target_link_libraries(symdir_test PUBLIC MeshFEM)
target_compile_options(symdir_test PRIVATE -ftemplate-backtrace-limit=0)

pybind11_add_module(flip_avoiding_step_length flip_avoiding_step_length.cc)
set_target_properties(flip_avoiding_step_length PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${PROJECT_SOURCE_DIR}/python>)
target_link_libraries(flip_avoiding_step_length PUBLIC MeshFEM)
target_compile_options(flip_avoiding_step_length PRIVATE -ftemplate-backtrace-limit=0)

pybind11_add_module(continuation_parametrization continuation_parametrization.cc)
set_target_properties(continuation_parametrization PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${PROJECT_SOURCE_DIR}/python>)
target_link_libraries(continuation_parametrization PUBLIC MeshFEM)
target_compile_options(continuation_parametrization PRIVATE -ftemplate-backtrace-limit=0)

pybind11_add_module(newton_flow newton_flow.cc)
set_target_properties(newton_flow PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${PROJECT_SOURCE_DIR}/python>)
target_link_libraries(newton_flow PUBLIC MeshFEM)
target_compile_options(newton_flow PRIVATE -ftemplate-backtrace-limit=0)

pybind11_add_module(fast_newton_flow fast_newton_flow.cc)
set_target_properties(fast_newton_flow PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${PROJECT_SOURCE_DIR}/python>)
target_link_libraries(fast_newton_flow PUBLIC MeshFEM)
target_compile_options(fast_newton_flow PRIVATE -ftemplate-backtrace-limit=0)

pybind11_add_module(poisson_gradient_integration poisson_gradient_integration.cc)
set_target_properties(poisson_gradient_integration PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${PROJECT_SOURCE_DIR}/python>)
target_link_libraries(poisson_gradient_integration PUBLIC MeshFEM)
target_compile_options(poisson_gradient_integration PRIVATE -ftemplate-backtrace-limit=0)

pybind11_add_module(rotation_strain_extrapolation rotation_strain_extrapolation.cc)
set_target_properties(rotation_strain_extrapolation PROPERTIES LIBRARY_OUTPUT_DIRECTORY $<1:${PROJECT_SOURCE_DIR}/python>)
target_link_libraries(rotation_strain_extrapolation PUBLIC MeshFEM)
target_compile_options(rotation_strain_extrapolation PRIVATE -ftemplate-backtrace-limit=0)
