#ifndef CHOLMODFACTORIZER_HH
#define CHOLMODFACTORIZER_HH

extern "C" {
#include <cholmod.h>
}

#include "CholeskyFactorizerBase.hh"

inline cholmod_dense cholmod_dense_wrap_vector_ptr(const size_t n, double *data) {
    cholmod_dense result;
    result.nrow = n;
    result.ncol = 1;
    result.nzmax = n;
    result.d = n; // leading dimension
    result.x = (void *) (data);
    result.z = NULL;
    result.xtype = CHOLMOD_REAL;
    result.dtype = CHOLMOD_DOUBLE;
    return result;
}

// Wrapper for a cholmod_sparse object allocated generated by Cholmod.
// Provides RAII resource management and supports matvecs.
struct CholmodSparseWrapper {
    CholmodSparseWrapper(size_t cols, cholmod_sparse *mat, std::shared_ptr<cholmod_common> c)
        : n(cols), m_mat(mat), m_c(c) {
            if (mat == nullptr) throw std::runtime_error("CholmodSparseWrapper constructed from null matrix");
            if (m_c == nullptr) throw std::runtime_error("CholmodSparseWrapper constructed with null cholmod_common");
        }

    CholmodSparseWrapper(const CholmodSparseWrapper &b) = delete;
    CholmodSparseWrapper(CholmodSparseWrapper &&b) : n(b.n), m_mat(b.m_mat), m_c(b.m_c) { b.m_mat = nullptr; }

    // Matrix-vector multiply
    template<typename _Vector>
    _Vector apply(const _Vector &x) const {
        if (x.size() != n) throw std::runtime_error("Sparse matvec size mismatch.");
        _Vector result(n);
        applyRaw(x.data(), result.data());
        return result;
    }

    // y = mat * x
    void applyRaw(const double *x, double *y, const bool transpose = false) const {
        if (m_mat == nullptr) throw std::runtime_error("No matrix to apply");

        // Wrap x, y values into a cholmod_dense struct
        auto cholx = cholmod_dense_wrap_vector_ptr(n, const_cast<double *>(x)); // Suitesparse won't actually modify the input vector data, so this const_cast should be safe.
        auto choly = cholmod_dense_wrap_vector_ptr(n, y);
        double alpha[2] = { 1.0, 0.0 };
        double beta [2] = { 0.0, 0.0 }; // y = alpha * mat * x + beta * y_init
        cholmod_l_sdmult(m_mat, transpose, alpha, beta, &cholx, &choly, m_c.get());
    }

    CholmodSparseWrapper &operator=(const CholmodSparseWrapper  &b) = delete;
    CholmodSparseWrapper &operator=(      CholmodSparseWrapper &&b) {
        n = b.n; m_mat = b.m_mat; m_c = std::move(b.m_c);
        b.m_mat = nullptr;
        return *this;
    }

    ~CholmodSparseWrapper() { if (m_mat != nullptr) cholmod_l_free_sparse(&m_mat, m_c.get()); }
private:
    size_t n;
    cholmod_sparse *m_mat;
    std::shared_ptr<cholmod_common> m_c; // Guaranteed non-null by construction/move assignment
};


struct CholmodFactorizer final : public CholeskyFactorizerBase {
    // Size of the factorized matrix.
    size_t m() const override { return m_A.nrow; }
    size_t n() const override { return m_A.ncol; }

    // Assumes matrix is stored in the upper triangle!
    template<typename _Triplet>
    CholmodFactorizer(const TripletMatrix<_Triplet> &tmat, bool forceSupernodal = false, bool force_ll = false, bool suppressWarnings = false) : m_AStorage(TripletMatrix<_Triplet>(tmat)) { m_init(forceSupernodal, force_ll, suppressWarnings); }

    // Warning: modifies the passed triplet matrix, tmat!
    template<typename _Triplet>
    CholmodFactorizer(TripletMatrix<_Triplet> &tmat, bool forceSupernodal = false, bool force_ll = false, bool suppressWarnings = false) : m_AStorage(tmat)           { m_init(forceSupernodal, force_ll, suppressWarnings); }
    CholmodFactorizer(const SuiteSparseMatrix &mat,  bool forceSupernodal = false, bool force_ll = false, bool suppressWarnings = false) : m_AStorage(mat)            { m_init(forceSupernodal, force_ll, suppressWarnings); }
    CholmodFactorizer(SuiteSparseMatrix &mat,        bool forceSupernodal = false, bool force_ll = false, bool suppressWarnings = false) : m_AStorage(mat)            { m_init(forceSupernodal, force_ll, suppressWarnings); }
    CholmodFactorizer(SuiteSparseMatrix &&mat,       bool forceSupernodal = false, bool force_ll = false, bool suppressWarnings = false) : m_AStorage(std::move(mat)) { m_init(forceSupernodal, force_ll, suppressWarnings); }

    // Delete unsafe copy constructors/assignment.
    // This will also suppress creation of default move constructors/assignment.
    CholmodFactorizer(const CholmodFactorizer  &b) = delete;
    CholmodFactorizer &operator=(const CholmodFactorizer  &b) = delete;

    void factorize() override {
        clearFactors();
        factorizeSymbolic();
        BENCHMARK_START_TIMER("CHOLMOD Numeric Factorize");
        int success = cholmod_l_factorize(&m_A, m_L, m_c.get());
        BENCHMARK_STOP_TIMER("CHOLMOD Numeric Factorize");
        if (!success)
            throw std::runtime_error("Factorize failed.");
        if (m_c->status == CHOLMOD_NOT_POSDEF)
            throw std::runtime_error("CHOLMOD detected non-positive definite matrix!");
        BENCHMARK_ADD_MESSAGE("Peak factorization memory (MB):\t" +
                              std::to_string(peakMemoryMB()));
    }

    // Perform only the symbolic factorization with the current system matrix
    // (useful this matrix holds the sparsity pattern that will be used for
    // many numeric factorizations).
    void factorizeSymbolic() override {
        BENCHMARK_START_TIMER("CHOLMOD Symbolic Factorize");
        clearFactors();
        m_L = cholmod_l_analyze(&m_A, m_c.get());
        BENCHMARK_STOP_TIMER("CHOLMOD Symbolic Factorize");
    }

    // Update the symbolic factorization for with a different sparsity pattern.
    void updateSymbolicFactorization(SuiteSparseMatrix mat) override {
        m_AStorage = std::move(mat);
        m_matrixUpdated();
        factorizeSymbolic();
    }

    // Recompute the numeric factorization using the new system matrix "tmat",
    // reusing the symbolic factorization. For this to work, it must have the same
    // sparsity pattern as the matrix for which the symbolic factorization was computed.
    // NOTE: The positive definiteness check inside this function is not sufficient,
    //       since it just uses CHOLMOD's return status. If the diagonal entry of L
    //       is negative, CHOLMOD will not complain about it. Use checkPosDef() to
    //       further ensure it is spd.
    void updateFactorization(SuiteSparseMatrix mat, bool isInTryCatch=false) override {
        if ((m_L != nullptr) && ((size_t(m_L->n) != size_t(mat.m)) || (size_t(m_L->n) != size_t(mat.n)))) {
            // Necessary, but not sufficient! Sparsity pattern must be a subset of original A's
            throw std::runtime_error("Wrong matrix size; " + std::to_string(int(m_L != nullptr))
                    + ", " + std::to_string(m_L ? m_L->n : 0)
                    + ", " + std::to_string(mat.m)
                    + ", " + std::to_string(mat.n));
        }
        if (m_A.nzmax == 0) throw std::runtime_error("Cholmod matrix wasn't allocated.");
        if (mat.nnz() > size_t(m_A.nzmax)) throw std::runtime_error("Matrix has more nonzeros than the one passed to the constructor"); // again, necessary but not sufficient!

        m_AStorage = std::move(mat);
        m_matrixUpdated();

        if (!hasFactorization()) return; // no symbolic factorization was computed yet; nothing needs to be updated.

        BENCHMARK_START_TIMER("CHOLMOD Numeric Factorize");
        bool oldTryCatch = m_c->try_catch;
        m_c->try_catch = isInTryCatch;
        int success = cholmod_l_factorize(&m_A, m_L, m_c.get());
        m_c->try_catch = oldTryCatch;
        BENCHMARK_STOP_TIMER("CHOLMOD Numeric Factorize");
        if (!success)
            throw std::runtime_error("Factor update failed");
        // NOTE: Be careful. This check is not sufficient for ensuring positive definite.
        if (m_c->status == CHOLMOD_NOT_POSDEF)
            throw std::runtime_error("CHOLMOD detected non-positive definite matrix!");
    }


    // Raw pointer version (Use with care! Caller must allocate/own both pointers)
    void solveRawExistingFactorization(const Real *b, Real *x, CholeskySys sys = CholeskySys::A) const override {
        if (!hasFactorization()) throw std::runtime_error("Factorization doesn't exist");
        static_assert(std::is_same<Real, double>::value, "Right-hand side must be an array of doubles");

        const size_t m = m_A.nrow, n = m_A.ncol;

        // Wrap b values into a cholmod_dense struct
        auto cholb = cholmod_dense_wrap_vector_ptr(m, const_cast<Real *>(b)); // Suitesparse won't actually modify the RHS data, so this const_cast should be safe.
        auto cholx = cholmod_dense_wrap_vector_ptr(n, x);
        auto cholx_ptr = &cholx;

        // Decode CholeskySys
        int chol_sys;

        switch (sys) {
            case CholeskySys::A:  chol_sys = CHOLMOD_A;  break;
            case CholeskySys::L:  chol_sys = CHOLMOD_L;  break;
            case CholeskySys::Lt: chol_sys = CHOLMOD_Lt; break;
            case CholeskySys::P:  chol_sys = CHOLMOD_P;  break;
            case CholeskySys::Pt: chol_sys = CHOLMOD_Pt; break;
            default: throw std::runtime_error("Unknown sys parameter");
        }

        BENCHMARK_START_TIMER("CHOLMOD Backsub");
        // Solve A x = b re-using the workspace vectors x, Y, and E
        cholmod_l_solve2(chol_sys, m_L, &cholb, NULL, &cholx_ptr, NULL, &m_Y, &m_E, m_c.get());

        if (cholx_ptr != &cholx) throw std::runtime_error("Cholmod reallocated x vector.");

        BENCHMARK_STOP_TIMER("CHOLMOD Backsub");
    }

    bool hasFactorization() const override { return m_L != nullptr; }

    // Store a copy of the current factorization so that it can be applied again
    // even after updateFactorization is called.
    void stashFactorization() override {
        if (m_L_stashed != nullptr) cholmod_l_free_factor(&m_L_stashed, m_c.get());
        m_L_stashed = cholmod_l_copy_factor(m_L, m_c.get());
    }

    bool hasStashedFactorization() const override { return m_L_stashed != nullptr; }

    // Exchange the roles of m_L and m_L_stashed, making the stash the active factorization.
    void swapStashedFactorization() override { std::swap(m_L, m_L_stashed); }

    void clearStashedFactorization() override {
        if (m_L_stashed) { cholmod_l_free_factor(&m_L_stashed, m_c.get()); m_L_stashed = nullptr; }
    }

    // Get the (unpermuted) Cholesky factor L as a sparse matrix that can be applied
    // to a vector.
    CholmodSparseWrapper getL() {
        // According to the documentation, cholmod_copy_factor will convert our numeric
        // factorization m_L back into a symbolic one, which will break future solves.
        // So we operate on a copy of m_L.
        if (!hasFactorization()) throw std::runtime_error("Factorization doesn't exist");
        cholmod_factor *factorCopy = cholmod_l_copy_factor(m_L, m_c.get());
        if (factorCopy == nullptr) throw std::runtime_error("Factor copy failed");
        auto result = CholmodSparseWrapper(m_A.nrow, cholmod_l_factor_to_sparse(factorCopy, m_c.get()), m_c);
        cholmod_l_free_factor(&factorCopy, m_c.get());
        return result;
    }

    double peakMemoryMB() const {
        return ((double) m_c->memory_usage) / (1 << 20);
    }

    void clearFactors() override {
        if (m_L) { cholmod_l_free_factor(&m_L, m_c.get()); m_L = nullptr; }
        clearStashedFactorization();
    }

    virtual ~CholmodFactorizer() {
        clearFactors();

        if (m_Y) cholmod_l_free_dense(&m_Y, m_c.get());
        if (m_E) cholmod_l_free_dense(&m_E, m_c.get());

        cholmod_l_finish(m_c.get());
    }

    static void error_handler(int status, const char *file, int line, const char *message) {
        std::cout << "Caught error." << std::endl;
        if (status < 0)
            throw std::runtime_error("Cholmod error in " + std::string(file) + ", line " +
                    std::to_string(line) + ": " + message + "( status " +
                    std::to_string(status) + ")");
        if (status > 0)
            std::cout << "Cholmod warning in " << file << ", line " << line
                      << ": " << message << "( status "
                      << std::to_string(status) << ")" << std::endl;
    }

    // Check if the matrix for which factor "L" was computed is positive definite.
    bool checkPosDef() const override {
        if (!m_L) throw std::runtime_error("Matrix wasn't factorized");
        if (m_L->is_ll) return true; // LL^T factorization only succeeds if the matrix was positive definite
        // We have an LDL^T factorization; we need to check that all entries of D are positive.
        // Cholmod stores these entries on the diagonal of "L"
        const size_t numCols = m_L->n;
        assert(numCols == n());
        SuiteSparse_long *colPointers = (SuiteSparse_long *) m_L->p;
        double *values = (double *) m_L->x;
        assert((colPointers != nullptr) && (values != nullptr));
        for (size_t j = 0; j < numCols; ++j) {
            auto colBegin = colPointers[j];
            assert(colBegin < colPointers[j + 1]); // column better be nonempty!
            // Diagonal entry is the first entry of this column
            if (values[colBegin] <= 1e-16) {
                return false;
            }
        }
        return true;
    }

    void setSuppressWarnings(bool suppressWarnings) override {
        m_c->print = suppressWarnings ? 0 : 2;
    }

    virtual CholeskyProvider provider() const override { return CholeskyProvider::CHOLMOD; }

private:
    std::shared_ptr<cholmod_common> m_c;
    cholmod_sparse m_A;
    cholmod_factor *m_L = nullptr, *m_L_stashed = nullptr;

    mutable cholmod_dense *m_Y = nullptr, *m_E = nullptr; // result/workspace for cholmod_l_solve2

    SuiteSparseMatrix m_AStorage;

    void m_matrixUpdated() {
        // static size_t i = 0;
        // m_AStorage.dumpBinary("spmat_" + std::to_string(i++) + ".bin");

        m_A.p = m_AStorage.Ap.data();
        m_A.i = m_AStorage.Ai.data();
        m_A.x = m_AStorage.Ax.data();

        m_A.nrow   = m_AStorage.m;
        m_A.ncol   = m_AStorage.n;
        m_A.nzmax  = m_AStorage.nnz();
    }

    void m_init(bool forceSupernodal, bool force_ll, bool suppressWarnings = false) {
        if (m_c) { cholmod_l_finish(m_c.get()); }
        m_c = std::make_shared<cholmod_common>();
        cholmod_l_start(m_c.get());

#ifdef TOO_LARGE_FOR_METIS
         // Use NESDIS since plain Metis is failing on large matrices.
         // This can be slower for some matrices, so we make this an option.
        m_c->default_nesdis = 1.0;
#endif

        if (forceSupernodal) m_c->supernodal = CHOLMOD_SUPERNODAL;
        m_c->final_ll = force_ll;

        m_c->print = suppressWarnings ? 0 : 2;

#if 0
        // Try many different orderings searching for the best.
        m_c->nmethods = 9;
#else
        // NESDIS seems to give best performance...
        m_c->nmethods = 1;
        m_c->method[0].ordering = CHOLMOD_NESDIS;
#endif

        // Completely bypass Metis/NESDIS (for large matrices, this fails...)
        // Note: this shouldn't be done for smaller matrices because it results in slower solves.
        //// This version avoids Metis, but fails for even more matrices due to fill-in.
        //// m_c->nmethods = 1;
        //// m_c->method[0].ordering = CHOLMOD_AMD;
        //// m_c->postorder = 1; // TRUE
        //// m_c->error_handler = error_handler;
        //
        // // This puts us in LDL' mode
        // // "To factorize a large indefinite matrix, set Common->supernodal to
        // // CHOLMOD_SIMPLICIAL, and the simplicial LDL' method will always be
        // // used. This will be significantly slower than a supernodal LL'
        // // factorization, however.
        // m_c->supernodal = CHOLMOD_SIMPLICIAL;
        m_c->grow2 = 0; // We don't plan to use the modify routines
        m_c->quick_return_if_not_posdef = true;

        m_A.nz     = nullptr; /* not needed because m_A is packed. */
        m_A.z      = nullptr; /* not needed because m_A is real. */
        m_A.stype  = 1; // upper triangle stored.
        m_A.itype  = CHOLMOD_LONG;
        m_A.xtype  = CHOLMOD_REAL;
        m_A.dtype  = CHOLMOD_DOUBLE;
        m_A.sorted = true;
        m_A.packed = true;

        m_matrixUpdated();
    }
};

#endif /* end of include guard: CHOLMODFACTORIZER_HH */
