#ifndef CHOLMODFACTORIZER_HH
#define CHOLMODFACTORIZER_HH

#if QUOTIENT_USE_64BIT
#define CHOLMOD_USE_INT64
#endif

#ifdef CHOLMOD_USE_INT64
#  define CHOLMOD_CALL(name) cholmod_l_##name
#else
#  define CHOLMOD_CALL(name) cholmod_##name
#endif

#if MESHFEM_WITH_CHOLMOD

extern "C" {
#include <cholmod.h>
}

#include "CholeskyFactorizerBase.hh"
#include <MeshFEMCore/TemplateHacks.hh>

namespace MeshFEM {

inline cholmod_dense cholmod_dense_wrap_vector_ptr(const size_t n, double *data) {
    cholmod_dense result;
    result.nrow = n;
    result.ncol = 1;
    result.nzmax = n;
    result.d = n; // leading dimension
    result.x = (void *) (data);
    result.z = NULL;
    result.xtype = CHOLMOD_REAL;
    result.dtype = CHOLMOD_DOUBLE;
    return result;
}

template<typename IndexType>
double *dummy_values_ptr(const IndexType *ind_ptr, size_t size, Eigen::VectorXd &conditional_storage) {
    if constexpr (sizeof(IndexType) != sizeof(double)) {
        conditional_storage.resize(size);
        return conditional_storage.data();
    }
    else { UNUSED(size); return const_cast<double *>((const double *) ind_ptr); } // This hack only works when the indices in `Ai` are 64 bit...
}

// Wrapper for a cholmod_sparse object allocated generated by Cholmod.
// Provides RAII resource management and supports matvecs.
struct CholmodSparseWrapper {
    CholmodSparseWrapper(size_t cols, cholmod_sparse *mat, std::shared_ptr<cholmod_common> c)
        : n(cols), m_mat(mat), m_c(c) {
            if (mat == nullptr) throw std::runtime_error("CholmodSparseWrapper constructed from null matrix");
            if (m_c == nullptr) throw std::runtime_error("CholmodSparseWrapper constructed with null cholmod_common");
        }

    CholmodSparseWrapper(const CholmodSparseWrapper &b) = delete;
    CholmodSparseWrapper(CholmodSparseWrapper &&b) : n(b.n), m_mat(b.m_mat), m_c(b.m_c) { b.m_mat = nullptr; }

    // Matrix-vector multiply
    template<typename _Vector>
    _Vector apply(const _Vector &x) const {
        if (x.size() != n) throw std::runtime_error("Sparse matvec size mismatch.");
        _Vector result(n);
        applyRaw(x.data(), result.data());
        return result;
    }

    // y = mat * x
    void applyRaw(const double *x, double *y, const bool transpose = false) const {
        if (!exists()) throw std::runtime_error("No matrix to apply");

        // Wrap x, y values into a cholmod_dense struct
        auto cholx = cholmod_dense_wrap_vector_ptr(n, const_cast<double *>(x)); // Suitesparse won't actually modify the input vector data, so this const_cast should be safe.
        auto choly = cholmod_dense_wrap_vector_ptr(n, y);
        double alpha[2] = { 1.0, 0.0 };
        double beta [2] = { 0.0, 0.0 }; // y = alpha * mat * x + beta * y_init
        CHOLMOD_CALL(sdmult)(m_mat, transpose, alpha, beta, &cholx, &choly, m_c.get());
    }

    CholmodSparseWrapper &operator=(const CholmodSparseWrapper  &b) = delete;
    CholmodSparseWrapper &operator=(      CholmodSparseWrapper &&b) {
        n = b.n; m_mat = b.m_mat; m_c = std::move(b.m_c);
        b.m_mat = nullptr;
        return *this;
    }

    bool exists() const { return m_mat != nullptr; }
    operator bool() const { return exists(); }

    ~CholmodSparseWrapper() { if (exists()) CHOLMOD_CALL(free_sparse)(&m_mat, m_c.get()); }
private:
    size_t n;
    cholmod_sparse *m_mat;
    std::shared_ptr<cholmod_common> m_c; // Guaranteed non-null by construction/move assignment
};

// Construct a `cholmod_sparse` object pointing at the data stored in `SuiteSparseMatrix`.
template<typename Real, typename IndexI, typename IndexP>
cholmod_sparse cholmod_sparse_view(size_t m, size_t n, size_t nnz, Real *x, IndexI *i, IndexP *p) {
    cholmod_sparse result;
    result.x = x;
    result.i = i;
    result.p = p;

    result.nrow   = m;
    result.ncol   = n;
    result.nzmax  = nnz;

    result.nz     = nullptr; /* not needed because `result` is packed. */
    result.z      = nullptr; /* not needed because `result` is real. */
    result.stype  = 1; // upper triangle stored.
    result.xtype  = CHOLMOD_REAL;

    result.itype  = std::is_same_v<IndexI, SuiteSparse_long> ? CHOLMOD_LONG : CHOLMOD_INT;
    // TODO: reenable
    // static_assert(std::is_same_v<IndexP, IndexI>, "Mixed p and i types are not yet supported by Cholmod...");
    //              // Apparently CHOLMOD_INTLONG is not yet supported :(
    //              // : (std::is_same_v<IndexP, SuiteSparse_long> ? CHOLMOD_INTLONG : CHOLMOD_INT);
    result.dtype  = std::is_same_v<Real, double> ? CHOLMOD_DOUBLE : CHOLMOD_SINGLE;
    result.sorted = true;
    result.packed = true;

    return result;
}

// Construct a `cholmod_sparse` object pointing at the data stored in `SuiteSparseMatrix`.
inline cholmod_sparse cholmod_sparse_view(const SuiteSparseMatrix &A) {
    return cholmod_sparse_view(A.m, A.n, A.nnz(), const_cast_ptr(A.Ax.data()), const_cast_ptr(A.Ai.data()), const_cast_ptr(A.Ap.data()));
}

struct CholmodFactorizer final : public CholeskyFactorizerBase {
    // Size of the factorized matrix.
    size_t m_reduced() const override { assertFactorization(FactorizationType::Symbolic); return m_L->n; }
    size_t n_reduced() const override { assertFactorization(FactorizationType::Symbolic); return m_L->n; }

    CholmodFactorizer(bool forceSupernodal = false, bool force_ll = false, bool suppressWarnings = false) {
        m_c = std::make_shared<cholmod_common>();
        CHOLMOD_CALL(start)(m_c.get());

#ifdef TOO_LARGE_FOR_METIS
         // Use NESDIS since plain Metis is failing on large matrices.
         // This can be slower for some matrices, so we make this an option.
        m_c->default_nesdis = 1.0;
#endif

        if (forceSupernodal) m_c->supernodal = CHOLMOD_SUPERNODAL;
        m_c->final_ll = force_ll;

        m_c->print = suppressWarnings ? 0 : 2;

#if 0
        // Try many different orderings searching for the best.
        m_c->nmethods = 9;
#else
        // NESDIS seems to give best performance...
        m_c->nmethods = 1;
        m_c->method[0].ordering = CHOLMOD_NESDIS;
        // m_c->method[0].ordering = CHOLMOD_AMD;
        // m_c->method[0].ordering = CHOLMOD_METIS;
#endif

        // Completely bypass Metis/NESDIS (for large matrices, this fails...)
        // Note: this shouldn't be done for smaller matrices because it results in slower solves.
        //// This version avoids Metis, but fails for even more matrices due to fill-in.
        //// m_c->nmethods = 1;
        //// m_c->method[0].ordering = CHOLMOD_AMD;
        //// m_c->postorder = 1; // TRUE
        //// m_c->error_handler = error_handler;
        //
        // // This puts us in LDL' mode
        // // "To factorize a large indefinite matrix, set Common->supernodal to
        // // CHOLMOD_SIMPLICIAL, and the simplicial LDL' method will always be
        // // used. This will be significantly slower than a supernodal LL'
        // // factorization, however.
        // m_c->supernodal = CHOLMOD_SIMPLICIAL;
        m_c->grow2 = 0; // We don't plan to use the modify routines
        m_c->quick_return_if_not_posdef = true;
    }

    // Delete unsafe copy constructors/assignment.
    // This will also suppress creation of default move constructors/assignment.
    CholmodFactorizer(const CholmodFactorizer  &b) = delete;
    CholmodFactorizer &operator=(const CholmodFactorizer  &b) = delete;

    using CholeskyFactorizerBase::factorizeSymbolic; // Don't shadow
    using CholeskyFactorizerBase::factorizeNumeric;
    using CholeskyFactorizerBase::factorizeNumericWithShift;

    enum class OrderingMethod { Nesdis, Metis, AMD };

    void setOrderingMethod(OrderingMethod method) {
        if (method == OrderingMethod::Nesdis)     m_c->method[0].ordering = CHOLMOD_NESDIS;
        else if (method == OrderingMethod::Metis) m_c->method[0].ordering = CHOLMOD_METIS;
        else if (method == OrderingMethod::AMD)   m_c->method[0].ordering = CHOLMOD_AMD;
        else throw std::runtime_error("Unknown ordering method");
    }

    // Perform only the symbolic factorization for the given matrix `mat`.
    void factorizeSymbolic(const SuiteSparseMatrix &mat, const std::vector<size_t> &pinnedVars) override {
        const SuiteSparseMatrix *A_reduced = m_initRowColRemoval(mat, pinnedVars);

#ifdef CHOLMOD_USE_INT64
        auto A_cholmod = cholmod_sparse_view(*A_reduced);
#else
        m_Ai_downcast = Eigen::Map<const VecX_T<std::decay_t<decltype(A_reduced->Ai[0])>>>(A_reduced->Ai.data(), A_reduced->Ai.size()).template cast<int>();
        m_Ap_downcast = Eigen::Map<const VecX_T<std::decay_t<decltype(A_reduced->Ap[0])>>>(A_reduced->Ap.data(), A_reduced->Ap.size()).template cast<int>();
        auto A_cholmod = cholmod_sparse_view(A_reduced->m, A_reduced->n, A_reduced->nz, const_cast_ptr(A_reduced->Ax.data()),
                                             m_Ai_downcast.data(), m_Ap_downcast.data());
#endif
        // Note: the array `cholmat.x` apparently must be valid or cholmod_nested_dissection fails
        // (even though the Nested dissection algorithm should not be
        // looking at its entries...)
        if (A_reduced->isSparsityOnly())
            A_cholmod.x = dummy_values_ptr(A_reduced->Ai.data(), A_reduced->Ai.size(), m_valuesDummy);

        m_factorizeSymbolicImpl(A_cholmod);
        m_valuesDummy.resize(0);
    }

    // (Re)compute the numeric factorization, reusing the symbolic factorization
    // if it exists; otherwise a symbolic factorization is computed.
    // For symbolic factorization reuse to work, `mat` must have the same
    // sparsity pattern as the matrix for which the symbolic factorization was computed.
    // NOTE: The positive definiteness check inside this function is not sufficient,
    //       since it just uses CHOLMOD's return status. If the diagonal entry of L
    //       is negative, CHOLMOD will not complain about it. Use checkPosDef() to
    //       further ensure it is spd.
    void factorizeNumeric(const SuiteSparseMatrix &fullMat, bool isInTryCatch=false) override {
        assertFactorization(FactorizationType::Symbolic);

        const SuiteSparseMatrix &mat = *m_rowColRemoval(fullMat);
#ifdef CHOLMOD_USE_INT64
        cholmod_sparse A = cholmod_sparse_view(mat);
#else
        cholmod_sparse A = cholmod_sparse_view(mat.m, mat.n, mat.nz, const_cast_ptr(mat.Ax.data()), m_Ai_downcast.data(), m_Ap_downcast.data());
#endif
        if (m_L == nullptr) m_factorizeSymbolicImpl(A);

        // {
        //     static size_t i = 0;
        //     size_t n_zero = 4;
        //     std::string padded_num = std::to_string(i++);
        //     padded_num = std::string(n_zero - std::min(n_zero, padded_num.length()), '0') + padded_num;
        //     mat.dumpBinary("numeric_mat_" + padded_num + ".bin");
        // }

        if ((size_t(m_L->n) != size_t(mat.m)) || (size_t(m_L->n) != size_t(mat.n))) {
            // Necessary, but not sufficient! Sparsity pattern must match original A's
            throw std::runtime_error("Symbolic factorization does not match size of matrix passed to `factorize`: "
                    + std::to_string(m_L->n) + " vs " + std::to_string(mat.m) + ", " + std::to_string(mat.n));
        }

        BENCHMARK_START_TIMER("CHOLMOD Numeric Factorize");
        bool oldTryCatch = m_c->try_catch;
        m_c->try_catch = isInTryCatch;
        int success = CHOLMOD_CALL(factorize)(&A, m_L, m_c.get());
        m_c->try_catch = oldTryCatch;
        BENCHMARK_STOP_TIMER("CHOLMOD Numeric Factorize");
        if (!success) throw std::runtime_error("Numeric factorization failed");
        // Careful: This check is not sufficient to guarantee positive definiteness.
        if (m_c->status == CHOLMOD_NOT_POSDEF) throw std::runtime_error("CHOLMOD detected non-positive definite matrix!");
        m_factorizationType = FactorizationType::Numeric;
    }

    // Compute the numeric factorization of `A + sigma * B`, reusing the
    // symbolic factorization if it exists.
    void factorizeNumericWithShift(const SuiteSparseMatrix &A, Real sigma, const SuiteSparseMatrix &B, bool isInTryCatch=false) override {
        if (!m_Ashift) {
            m_Ashift = std::make_unique<SuiteSparseMatrix>(A);
            m_Ashift->data() += sigma * B.data();
        }
        else {
            m_Ashift->data() = A.data() + sigma * B.data();
        }

        factorizeNumeric(*m_Ashift, isInTryCatch);
    }

    // Compute the numeric factorization of `A + sigma * B`, reusing the
    // symbolic factorization if it exists.
    void factorizeNumericWithShift(const SuiteSparseMatrix &A, Real sigma, bool isInTryCatch=false) override {
        if (!m_Ashift) {
            m_Ashift = std::make_unique<SuiteSparseMatrix>(A);
        }
        else {
            m_Ashift->data() = A.data();
        }
        m_Ashift->addScaledIdentity(sigma);

        factorizeNumeric(*m_Ashift, isInTryCatch);
    }

    using CholeskyFactorizerBase::factorize; // Don't hide.
    void factorize(const SuiteSparseMatrix &mat, const std::vector<size_t> &fixedVars = std::vector<size_t>(), bool isInTryCatch = false) override {
        clearFactors();
        factorizeSymbolic(mat, fixedVars);
        factorizeNumeric(mat, isInTryCatch);
    }

    // Raw pointer version (Use with care! Caller must allocate/own both pointers)
    void solveRawReduced(const Real *b, Real *x, CholeskySys sys = CholeskySys::A, bool alreadyPermuted = false) const override {
        assertFactorization(sys);
        static_assert(std::is_same<Real, double>::value, "Right-hand side must be an array of doubles");
        if (alreadyPermuted) throw std::runtime_error("Unimplemented");

        const size_t m = m_L->n, n = m_L->n;

        // Wrap b values into a cholmod_dense struct
        auto cholb = cholmod_dense_wrap_vector_ptr(m, const_cast<Real *>(b)); // Suitesparse won't actually modify the RHS data, so this const_cast should be safe.
        auto cholx = cholmod_dense_wrap_vector_ptr(n, x);
        auto cholx_ptr = &cholx;

        // Decode CholeskySys
        int chol_sys;

        switch (sys) {
            case CholeskySys::A:  chol_sys = CHOLMOD_A;  break;
            case CholeskySys::L:  chol_sys = CHOLMOD_L;  break;
            case CholeskySys::Lt: chol_sys = CHOLMOD_Lt; break;
            case CholeskySys::P:  chol_sys = CHOLMOD_P;  break;
            case CholeskySys::Pt: chol_sys = CHOLMOD_Pt; break;
            default: throw std::runtime_error("Unknown sys parameter");
        }

        BENCHMARK_START_TIMER("CHOLMOD Solve");
        // Solve A x = b re-using the workspace vectors x, Y, and E
        CHOLMOD_CALL(solve2)(chol_sys, m_L, &cholb, /* Bset = */ NULL, &cholx_ptr, /* Xset = */ NULL, &m_Y, &m_E, m_c.get());

        if (cholx_ptr != &cholx) throw std::runtime_error("Cholmod reallocated x vector.");

        BENCHMARK_STOP_TIMER("CHOLMOD Solve");
    }

    bool preferInPlaceSolve() const override { return false; }
    bool supportsPrePermutation() const override { return false; }

    // Store a copy of the current factorization so that it can be applied again
    // even after updateFactorization is called.
    void stashFactorization() override {
        if (m_L_stashed != nullptr) CHOLMOD_CALL(free_factor)(&m_L_stashed, m_c.get());
        m_L_stashed = CHOLMOD_CALL(copy_factor)(m_L, m_c.get());
    }

    bool hasStashedFactorization() const override { return m_L_stashed != nullptr; }

    // Exchange the roles of m_L and m_L_stashed, making the stash the active factorization.
    void swapStashedFactorization() override { std::swap(m_L, m_L_stashed); }

    void clearStashedFactorization() override {
        if (m_L_stashed) { CHOLMOD_CALL(free_factor)(&m_L_stashed, m_c.get()); m_L_stashed = nullptr; }
    }

    // Get the (unpermuted) Cholesky factor L as a sparse matrix that can be applied
    // to a vector.
    CholmodSparseWrapper getL() const {
        // According to the documentation, cholmod_copy_factor will convert our numeric
        // factorization m_L back into a symbolic one, which will break future solves.
        // So we operate on a copy of m_L.
        assertFactorization();
        cholmod_factor *factorCopy = CHOLMOD_CALL(copy_factor)(m_L, m_c.get());
        if (factorCopy == nullptr) throw std::runtime_error("Factor copy failed");
        auto result = CholmodSparseWrapper(m_L->n, CHOLMOD_CALL(factor_to_sparse)(factorCopy, m_c.get()), m_c);
        CHOLMOD_CALL(free_factor)(&factorCopy, m_c.get());
        return result;
    }

    double peakMemoryMB() const {
        return ((double) m_c->memory_usage) / (1 << 20);
    }

    void clearFactors() override {
        if (m_L) { CHOLMOD_CALL(free_factor)(&m_L, m_c.get()); m_L = nullptr; }
        m_Ashift.reset();
        m_factorizationType = FactorizationType::None;
        clearStashedFactorization();
    }

    static void error_handler(int status, const char *file, int line, const char *message) {
        std::cout << "Caught error." << std::endl;
        if (status < 0)
            throw std::runtime_error("Cholmod error in " + std::string(file) + ", line " +
                    std::to_string(line) + ": " + message + "( status " +
                    std::to_string(status) + ")");
        if (status > 0)
            std::cout << "Cholmod warning in " << file << ", line " << line
                      << ": " << message << "( status "
                      << std::to_string(status) << ")" << std::endl;
    }

    // Check if the matrix for which factor "L" was computed is positive definite.
    bool checkPosDef() const override {
        if (!m_L) throw std::runtime_error("Matrix wasn't factorized");
        if (m_L->is_ll) return true; // LL^T factorization only succeeds if the matrix was positive definite
        // We have an LDL^T factorization; we need to check that all entries of D are positive.
        // Cholmod stores these entries on the diagonal of "L"
        const size_t numCols = m_L->n;
        assert(numCols == n_reduced());
#ifdef CHOLMOD_USE_INT64
        using index_type = SuiteSparse_long;
#else
        using index_type = int;
#endif
        const index_type *colPointers = (index_type *) m_L->p;
        double *values = (double *) m_L->x;
        assert((colPointers != nullptr) && (values != nullptr));
        for (size_t j = 0; j < numCols; ++j) {
            auto colBegin = colPointers[j];
            assert(colBegin < colPointers[j + 1]); // column better be nonempty!
            // Diagonal entry is the first entry of this column
            if (values[colBegin] <= 1e-16) {
                return false;
            }
        }
        return true;
    }

    void setSuppressWarnings(bool suppressWarnings) override {
        m_c->print = suppressWarnings ? 0 : 2;
    }

    virtual CholeskyProvider provider() const override { return CholeskyProvider::CHOLMOD; }

    virtual ~CholmodFactorizer() {
        clearFactors();

        if (m_Y) CHOLMOD_CALL(free_dense)(&m_Y, m_c.get());
        if (m_E) CHOLMOD_CALL(free_dense)(&m_E, m_c.get());

        CHOLMOD_CALL(finish)(m_c.get());
    }

private:
    std::unique_ptr<SuiteSparseMatrix> m_Ashift;
    std::shared_ptr<cholmod_common> m_c;
    cholmod_factor *m_L = nullptr, *m_L_stashed = nullptr;

    mutable cholmod_dense *m_Y = nullptr, *m_E = nullptr; // result/workspace for cholmod_solve2
    Eigen::VectorXd m_valuesDummy; // Needed to run `cholmod_nested_dissection` without values.

#ifndef CHOLMOD_USE_INT64
    Eigen::VectorXi m_Ai_downcast, m_Ap_downcast; // TODO: remove this when we make the BlockCSCHessian/assembly index type configurable match catamari::Int.
#endif

    void m_factorizeSymbolicImpl(const cholmod_sparse &A) {
        BENCHMARK_START_TIMER("CHOLMOD Symbolic Factorize");
        clearFactors();
        m_L = CHOLMOD_CALL(analyze)(const_cast<cholmod_sparse *>(&A), m_c.get());
        m_factorizationType = FactorizationType::Symbolic;
        BENCHMARK_STOP_TIMER("CHOLMOD Symbolic Factorize");
    }
};

} // namespace MeshFEM

#else

namespace MeshFEM {

struct CholmodSparseWrapper {
    template<typename... Args>
    CholmodSparseWrapper(Args&&...) {
        throw std::runtime_error("CHOLMOD support not compiled");
    }

    template<typename _Vector>
    _Vector apply(const _Vector &) const { throw std::runtime_error("CHOLMOD support not compiled"); }
    void applyRaw(const double *, double *, const bool = false) const { throw std::runtime_error("CHOLMOD support not compiled"); }
};

struct CholmodFactorizer final : public CholeskyFactorizerBase {
    size_t m_reduced() const override { return 0; }
    size_t n_reduced() const override { return 0; }

    CholmodFactorizer(bool = false, bool = false, bool = false) {
        throw std::runtime_error("CHOLMOD support not compiled");
    }

    using CholeskyFactorizerBase::factorizeSymbolic; // Don't shadow
    using CholeskyFactorizerBase::factorizeNumeric;
    using CholeskyFactorizerBase::factorizeNumericWithShift;

    // Perform only the symbolic factorization for the given matrix `mat`.
    void factorizeSymbolic(const SuiteSparseMatrix &, const std::vector<size_t> &) override {
        throw std::runtime_error("CHOLMOD support not compiled");
    }

    void factorizeNumeric(const SuiteSparseMatrix &, bool =false) override {
        throw std::runtime_error("CHOLMOD support not compiled");
    }

    // Compute the numeric factorization of `A + sigma * B`, reusing the
    // symbolic factorization if it exists.
    void factorizeNumericWithShift(const SuiteSparseMatrix &, Real, const SuiteSparseMatrix &, bool =false) override {
        throw std::runtime_error("CHOLMOD support not compiled");
    }

    void factorizeNumericWithShift(const SuiteSparseMatrix &, Real, bool =false) override {
        throw std::runtime_error("CHOLMOD support not compiled");
    }

    void factorize(const SuiteSparseMatrix &, const std::vector<size_t> & = std::vector<size_t>(), bool = false) override {
        throw std::runtime_error("CHOLMOD support not compiled");
    }

    // Raw pointer version (Use with care! Caller must allocate/own both pointers)
    void solveRawReduced(const Real *, Real *, CholeskySys = CholeskySys::A, bool = false) const override {
        throw std::runtime_error("CHOLMOD support not compiled");
    }

    void        stashFactorization()       override { throw std::runtime_error("CHOLMOD support not compiled"); }
    bool   hasStashedFactorization() const override { throw std::runtime_error("CHOLMOD support not compiled"); }
    void  swapStashedFactorization()       override { throw std::runtime_error("CHOLMOD support not compiled"); }
    void clearStashedFactorization()       override { throw std::runtime_error("CHOLMOD support not compiled"); }

    bool preferInPlaceSolve() const override { return false; }
    bool supportsPrePermutation() const override { return false; }

    CholmodSparseWrapper getL() const { return CholmodSparseWrapper(); }

    void clearFactors() override { }

    bool checkPosDef() const override { return false; }

    virtual CholeskyProvider provider() const override { return CholeskyProvider::CHOLMOD; }

    virtual ~CholmodFactorizer() { }
};

} // namespace MeshFEM

#endif

#endif /* end of include guard: CHOLMODFACTORIZER_HH */
